import type {
    OperatorActionDefinition,
    OperatorConsoleTile,
    OperatorRunbook,
} from './types';

export const OPERATOR_CONSOLE_TILES = [
    {
        id: 'tenant-health',
        domain: 'TENANTS',
        label: 'Tenant Health',
        description: 'Provisioning, suspension, contract, and tenant-wide health posture.',
        availableScopes: ['PLATFORM'],
        requiredPermission: 'platform:read',
        requiredScope: 'platform',
        dataFreshness: 'NEAR_REAL_TIME',
        sourceTables: ['tenants', 'observability_events', 'sre_incidents'],
        drilldownRoute: '/platform/tenants',
        runbookCodes: ['tenant-health.degraded'],
        actionTypes: ['SUSPEND_TENANT', 'OPEN_RUNBOOK'],
        ownerRoles: ['PLATFORM_ADMIN'],
    },
    {
        id: 'job-queue',
        domain: 'JOBS',
        label: 'Job Queue',
        description: 'Background job backlog, failures, stale locks, and dead-letter queues.',
        availableScopes: ['PLATFORM', 'TENANT'],
        requiredPermission: 'jobs:read',
        requiredScope: 'tenant',
        dataFreshness: 'NEAR_REAL_TIME',
        sourceTables: ['background_jobs', 'background_job_attempts'],
        drilldownRoute: '/operator/jobs',
        runbookCodes: ['jobs.dead-letter', 'jobs.stale-locks'],
        actionTypes: ['RETRY_JOB', 'OPEN_RUNBOOK'],
        ownerRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN'],
    },
    {
        id: 'notification-outbox',
        domain: 'NOTIFICATIONS',
        label: 'Notification Outbox',
        description: 'Email, SMS, WhatsApp, and in-app delivery queues and failures.',
        availableScopes: ['PLATFORM', 'TENANT'],
        requiredPermission: 'notifications:read',
        requiredScope: 'tenant',
        dataFreshness: 'NEAR_REAL_TIME',
        sourceTables: ['notification_outbox', 'notification_delivery_events'],
        drilldownRoute: '/operator/notifications',
        runbookCodes: ['notifications.dead-letter'],
        actionTypes: ['REPLAY_NOTIFICATION', 'OPEN_RUNBOOK'],
        ownerRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'SCHOOL_ADMIN'],
    },
    {
        id: 'payment-reconciliation',
        domain: 'PAYMENTS',
        label: 'Payment Reconciliation',
        description: 'Provider events, payment orders, refunds, and invoice reconciliation.',
        availableScopes: ['PLATFORM', 'TENANT'],
        requiredPermission: 'payments:read',
        requiredScope: 'tenant',
        dataFreshness: 'NEAR_REAL_TIME',
        sourceTables: ['payment_orders', 'payment_provider_events', 'payment_audit_logs'],
        drilldownRoute: '/platform/billing',
        runbookCodes: ['payments.reconciliation'],
        actionTypes: ['RECONCILE_PAYMENT', 'OPEN_RUNBOOK'],
        ownerRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'FINANCE_LEAD'],
    },
    {
        id: 'integration-delivery',
        domain: 'INTEGRATIONS',
        label: 'Integration Delivery',
        description: 'Partner connections, API keys, webhook delivery, and integration audit failures.',
        availableScopes: ['PLATFORM', 'TENANT'],
        requiredPermission: 'integrations:read',
        requiredScope: 'tenant',
        dataFreshness: 'NEAR_REAL_TIME',
        sourceTables: ['integration_connections', 'integration_api_keys', 'integration_audit_logs'],
        drilldownRoute: '/integrations',
        runbookCodes: ['integrations.delivery-failures'],
        actionTypes: ['RETRY_WEBHOOK', 'ROTATE_API_KEY', 'OPEN_RUNBOOK'],
        ownerRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'SCHOOL_ADMIN'],
    },
    {
        id: 'approval-queue',
        domain: 'APPROVALS',
        label: 'Approval Queue',
        description: 'Pending, overdue, and escalated workflow approvals.',
        availableScopes: ['PLATFORM', 'TENANT'],
        requiredPermission: 'audit:read',
        requiredScope: 'tenant',
        dataFreshness: 'NEAR_REAL_TIME',
        sourceTables: ['workflow_approval_requests', 'workflow_approval_reviews'],
        drilldownRoute: '/operator/approvals',
        runbookCodes: ['approvals.sla-breach'],
        actionTypes: ['REVIEW_APPROVAL', 'OPEN_RUNBOOK'],
        ownerRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'SCHOOL_ADMIN'],
    },
    {
        id: 'incident-command',
        domain: 'INCIDENTS',
        label: 'Incident Command',
        description: 'Open SRE incidents, acknowledgement state, and critical incident posture.',
        availableScopes: ['PLATFORM', 'TENANT'],
        requiredPermission: 'audit:read',
        requiredScope: 'tenant',
        dataFreshness: 'REAL_TIME',
        sourceTables: ['sre_incidents', 'observability_events'],
        drilldownRoute: '/operator/incidents',
        runbookCodes: ['incidents.critical'],
        actionTypes: ['ACKNOWLEDGE_INCIDENT', 'RESOLVE_INCIDENT', 'OPEN_RUNBOOK'],
        ownerRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN'],
    },
    {
        id: 'slo-observability',
        domain: 'OBSERVABILITY',
        label: 'SLO Observability',
        description: 'SLO breaches, noisy error sources, and platform telemetry health.',
        availableScopes: ['PLATFORM', 'TENANT'],
        requiredPermission: 'audit:read',
        requiredScope: 'tenant',
        dataFreshness: 'BATCH',
        sourceTables: ['slo_definitions', 'slo_measurements', 'observability_events'],
        drilldownRoute: '/operator/observability',
        runbookCodes: ['observability.slo-breach'],
        actionTypes: ['OPEN_RUNBOOK'],
        ownerRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN'],
    },
    {
        id: 'security-posture',
        domain: 'SECURITY',
        label: 'Security Posture',
        description: 'Security findings, suspicious events, and secret-rotation debt.',
        availableScopes: ['PLATFORM', 'TENANT'],
        requiredPermission: 'audit:read',
        requiredScope: 'tenant',
        dataFreshness: 'BATCH',
        sourceTables: ['audit_logs', 'observability_events', 'integration_api_keys'],
        drilldownRoute: '/hq/compliance',
        runbookCodes: ['security.secret-rotation'],
        actionTypes: ['ROTATE_API_KEY', 'OPEN_RUNBOOK'],
        ownerRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'SCHOOL_ADMIN'],
    },
    {
        id: 'data-platform',
        domain: 'DATA_PLATFORM',
        label: 'Data Platform',
        description: 'Metadata lifecycle, migration drift, and dynamic object safety.',
        availableScopes: ['PLATFORM', 'TENANT'],
        requiredPermission: 'metadata:read',
        requiredScope: 'tenant',
        dataFreshness: 'BATCH',
        sourceTables: ['metadata_objects', 'metadata_fields', 'metadata_migrations'],
        drilldownRoute: '/settings/metadata',
        runbookCodes: ['metadata.migration-drift'],
        actionTypes: ['OPEN_RUNBOOK'],
        ownerRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'SCHOOL_ADMIN'],
    },
] as const satisfies readonly OperatorConsoleTile[];

export const OPERATOR_ACTIONS = [
    {
        type: 'ACKNOWLEDGE_INCIDENT',
        domain: 'INCIDENTS',
        label: 'Acknowledge incident',
        description: 'Mark an incident as acknowledged and assign operator ownership.',
        requiredPermission: 'platform:update',
        requiredScope: 'platform',
        targetScope: 'PLATFORM',
        auditAction: 'operator.incident.acknowledge',
        requiresReason: false,
    },
    {
        type: 'RESOLVE_INCIDENT',
        domain: 'INCIDENTS',
        label: 'Resolve incident',
        description: 'Resolve an incident after remediation evidence exists.',
        requiredPermission: 'platform:update',
        requiredScope: 'platform',
        targetScope: 'PLATFORM',
        auditAction: 'operator.incident.resolve',
        requiresReason: true,
    },
    {
        type: 'RETRY_JOB',
        domain: 'JOBS',
        label: 'Retry job',
        description: 'Requeue a failed or dead-lettered background job.',
        requiredPermission: 'jobs:update',
        requiredScope: 'tenant',
        targetScope: 'TENANT',
        auditAction: 'operator.job.retry',
        requiresReason: true,
    },
    {
        type: 'REPLAY_NOTIFICATION',
        domain: 'NOTIFICATIONS',
        label: 'Replay notification',
        description: 'Replay a failed notification from the outbox.',
        requiredPermission: 'notifications:update',
        requiredScope: 'tenant',
        targetScope: 'TENANT',
        auditAction: 'operator.notification.replay',
        requiresReason: true,
    },
    {
        type: 'RETRY_WEBHOOK',
        domain: 'INTEGRATIONS',
        label: 'Retry webhook',
        description: 'Retry a failed outbound webhook delivery.',
        requiredPermission: 'webhooks:update',
        requiredScope: 'tenant',
        targetScope: 'TENANT',
        auditAction: 'operator.webhook.retry',
        requiresReason: true,
    },
    {
        type: 'RECONCILE_PAYMENT',
        domain: 'PAYMENTS',
        label: 'Reconcile payment',
        description: 'Run a reconciliation action against payment orders and provider events.',
        requiredPermission: 'payments:update',
        requiredScope: 'tenant',
        targetScope: 'TENANT',
        auditAction: 'operator.payment.reconcile',
        requiresReason: true,
        approvalPolicyId: 'payments.refund',
    },
    {
        type: 'REVIEW_APPROVAL',
        domain: 'APPROVALS',
        label: 'Review approval',
        description: 'Open the human approval review workflow.',
        requiredPermission: 'settings:update',
        requiredScope: 'tenant',
        targetScope: 'TENANT',
        auditAction: 'operator.approval.review',
        requiresReason: false,
    },
    {
        type: 'ROTATE_API_KEY',
        domain: 'SECURITY',
        label: 'Rotate API key',
        description: 'Revoke or rotate a tenant integration API key.',
        requiredPermission: 'integrations:update',
        requiredScope: 'tenant',
        targetScope: 'TENANT',
        auditAction: 'operator.integration_key.rotate',
        requiresReason: true,
    },
    {
        type: 'SUSPEND_TENANT',
        domain: 'TENANTS',
        label: 'Suspend tenant',
        description: 'Suspend a tenant after billing, security, or operational review.',
        requiredPermission: 'platform:update',
        requiredScope: 'platform',
        targetScope: 'PLATFORM',
        auditAction: 'operator.tenant.suspend',
        requiresReason: true,
    },
    {
        type: 'OPEN_RUNBOOK',
        domain: 'OBSERVABILITY',
        label: 'Open runbook',
        description: 'Open the linked runbook without mutating state.',
        requiredPermission: 'audit:read',
        requiredScope: 'tenant',
        targetScope: 'TENANT',
        auditAction: 'operator.runbook.open',
        requiresReason: false,
    },
] as const satisfies readonly OperatorActionDefinition[];

export const OPERATOR_RUNBOOKS = [
    {
        code: 'tenant-health.degraded',
        domain: 'TENANTS',
        title: 'Tenant Health Degraded',
        severity: 'WARNING',
        ownerRole: 'PLATFORM_ADMIN',
        summary: 'Triage tenant provisioning, suspension, and contract health before customer impact expands.',
        steps: [
            'Confirm whether the tenant is platform-wide, suspended, or provisioning-failed.',
            'Review the latest tenant-scoped observability events and audit logs.',
            'Escalate to billing, security, or support based on the dominant signal.',
        ],
        escalation: 'Page platform owner if more than one tenant is affected.',
    },
    {
        code: 'jobs.dead-letter',
        domain: 'JOBS',
        title: 'Job Dead Letter Queue',
        severity: 'CRITICAL',
        ownerRole: 'SUPER_ADMIN',
        summary: 'Dead-lettered jobs need operator review before retry because payloads may be stale.',
        steps: [
            'Inspect the job payload, tenant, task name, and latest attempt error.',
            'Check whether the target entity still exists and belongs to the same tenant.',
            'Retry only after the root cause is fixed or cancel with an audit reason.',
        ],
        escalation: 'Escalate to platform engineering if the same task fails across tenants.',
    },
    {
        code: 'jobs.stale-locks',
        domain: 'JOBS',
        title: 'Stale Job Locks',
        severity: 'WARNING',
        ownerRole: 'PLATFORM_ADMIN',
        summary: 'Locked jobs older than their processing window can block tenant workflows.',
        steps: [
            'Identify the worker lock owner and last heartbeat.',
            'Verify the worker is no longer running before releasing the lock.',
            'Requeue with the original idempotency key.',
        ],
        escalation: 'Escalate when stale locks recur for the same queue.',
    },
    {
        code: 'notifications.dead-letter',
        domain: 'NOTIFICATIONS',
        title: 'Notification Delivery Failure',
        severity: 'CRITICAL',
        ownerRole: 'SUPER_ADMIN',
        summary: 'Dead-lettered notifications may hide parent, payment, or compliance communication failures.',
        steps: [
            'Group failures by provider, channel, and template.',
            'Confirm recipient data and provider credentials.',
            'Replay only tenant-scoped messages after provider health is confirmed.',
        ],
        escalation: 'Escalate to provider support if failures are provider-wide.',
    },
    {
        code: 'payments.reconciliation',
        domain: 'PAYMENTS',
        title: 'Payment Reconciliation Drift',
        severity: 'CRITICAL',
        ownerRole: 'FINANCE_LEAD',
        summary: 'Money movement must reconcile across orders, invoices, provider events, and audit logs.',
        steps: [
            'Compare provider event status with the local payment order.',
            'Verify invoice and student ownership before mutating payment state.',
            'Record the reconciliation reason and link provider evidence.',
        ],
        escalation: 'Escalate to finance leadership for refunds, chargebacks, or mismatched amounts.',
    },
    {
        code: 'integrations.delivery-failures',
        domain: 'INTEGRATIONS',
        title: 'Integration Delivery Failures',
        severity: 'WARNING',
        ownerRole: 'SCHOOL_ADMIN',
        summary: 'Partner integration failures need idempotent retries and tenant-safe payload review.',
        steps: [
            'Review the integration audit log and request idempotency key.',
            'Validate that the partner connection and API key are active.',
            'Retry only after signature, scope, and payload ownership checks pass.',
        ],
        escalation: 'Escalate to platform engineering for repeated signature or mapping failures.',
    },
    {
        code: 'approvals.sla-breach',
        domain: 'APPROVALS',
        title: 'Approval SLA Breach',
        severity: 'WARNING',
        ownerRole: 'SUPER_ADMIN',
        summary: 'Overdue approvals block high-risk business actions and need escalation.',
        steps: [
            'Identify the policy, requester, required approver roles, and due time.',
            'Notify eligible approvers or delegate according to policy.',
            'Escalate once the SLA window has passed.',
        ],
        escalation: 'Escalate to tenant owner when overdue approvals affect payments or PII export.',
    },
    {
        code: 'incidents.critical',
        domain: 'INCIDENTS',
        title: 'Critical Incident',
        severity: 'CRITICAL',
        ownerRole: 'PLATFORM_ADMIN',
        summary: 'Critical incidents require acknowledgement, owner assignment, and post-resolution evidence.',
        steps: [
            'Acknowledge the incident and identify affected tenants.',
            'Open the linked source logs, SLOs, and recent deploy history.',
            'Resolve only after the customer-facing symptom and root cause are addressed.',
        ],
        escalation: 'Page platform owner immediately for production critical incidents.',
    },
    {
        code: 'observability.slo-breach',
        domain: 'OBSERVABILITY',
        title: 'SLO Breach',
        severity: 'WARNING',
        ownerRole: 'PLATFORM_ADMIN',
        summary: 'SLO breaches show user-facing risk even when no incident is open yet.',
        steps: [
            'Compare current breach window with active incidents.',
            'Identify the dominant error source and affected tenant scope.',
            'Create an incident if the breach continues beyond the burn-rate threshold.',
        ],
        escalation: 'Escalate when two consecutive windows breach the same SLO.',
    },
    {
        code: 'security.secret-rotation',
        domain: 'SECURITY',
        title: 'Secret Rotation Required',
        severity: 'WARNING',
        ownerRole: 'PLATFORM_ADMIN',
        summary: 'Expired or stale API keys must be rotated without exposing raw secrets.',
        steps: [
            'Identify key prefix, owner, scopes, and last-used timestamp.',
            'Create a replacement key with minimal scopes.',
            'Revoke the old key after partner confirmation and audit the rotation.',
        ],
        escalation: 'Escalate to security owner if a key was exposed or used suspiciously.',
    },
    {
        code: 'metadata.migration-drift',
        domain: 'DATA_PLATFORM',
        title: 'Metadata Migration Drift',
        severity: 'WARNING',
        ownerRole: 'SCHOOL_ADMIN',
        summary: 'Metadata drift can break dynamic objects, forms, and tenant-specific customizations.',
        steps: [
            'Check draft metadata versions and failed migrations.',
            'Validate field constraints before publishing.',
            'Apply tenant-safe migrations through the metadata lifecycle.',
        ],
        escalation: 'Escalate to platform engineering if drift affects multiple tenants.',
    },
] as const satisfies readonly OperatorRunbook[];

export function listOperatorConsoleTiles(): readonly OperatorConsoleTile[] {
    return OPERATOR_CONSOLE_TILES;
}

export function getOperatorConsoleTile(id: string): OperatorConsoleTile | null {
    return OPERATOR_CONSOLE_TILES.find((tile) => tile.id === id) ?? null;
}

export function listOperatorActions(): readonly OperatorActionDefinition[] {
    return OPERATOR_ACTIONS;
}

export function getOperatorAction(type: string): OperatorActionDefinition | null {
    return OPERATOR_ACTIONS.find((action) => action.type === type) ?? null;
}

export function listOperatorRunbooks(): readonly OperatorRunbook[] {
    return OPERATOR_RUNBOOKS;
}

export function getOperatorRunbook(code: string): OperatorRunbook | null {
    return OPERATOR_RUNBOOKS.find((runbook) => runbook.code === code) ?? null;
}
