import {
    AUTHORIZATION_ROLE_VALUES,
    type ApprovalPolicy,
    type AuthorizationRole,
    type AuthorizationScope,
    type FieldPolicy,
    type PermissionGrant,
    type RoutePolicy,
} from './types';

export const AUTHORIZATION_ROLES = AUTHORIZATION_ROLE_VALUES;

export const ADMIN_AUTHORIZATION_ROLES = [
    'PLATFORM_ADMIN',
    'SUPER_ADMIN',
    'SCHOOL_ADMIN',
    'PRINCIPAL',
] as const satisfies readonly AuthorizationRole[];

export const STAFF_AUTHORIZATION_ROLES = [
    'PLATFORM_ADMIN',
    'SUPER_ADMIN',
    'GROUP_EXECUTIVE',
    'SCHOOL_ADMIN',
    'PRINCIPAL',
    'REGISTRAR',
    'FINANCE_LEAD',
    'ACCOUNTANT',
    'ADMISSION_COUNSELOR',
    'STUDENT_SUCCESS_COUNSELOR',
    'TEACHER',
    'TRANSPORT_MANAGER',
    'TRUST_OFFICER',
    'CREDENTIAL_OFFICER',
] as const satisfies readonly AuthorizationRole[];

const SCOPE_VALUES = new Set<AuthorizationScope>([
    'platform',
    'tenant',
    'department',
    'class',
    'assigned',
    'own',
]);

function isScope(value: string | undefined): value is AuthorizationScope {
    return Boolean(value && SCOPE_VALUES.has(value as AuthorizationScope));
}

export function grant(permission: string, scope: AuthorizationScope = 'tenant', description?: string): PermissionGrant {
    const [resource, action, requestedScope] = permission.split(':');
    const hasExplicitScope = isScope(requestedScope);

    return {
        permission: hasExplicitScope ? `${resource}:${action}` : permission,
        scope: hasExplicitScope ? requestedScope : scope,
        description,
        requiresExplicitScope: hasExplicitScope,
    };
}

function grants(permissions: readonly string[], scope: AuthorizationScope = 'tenant'): PermissionGrant[] {
    return permissions.map((permission) => grant(permission, scope));
}

const COMMON_STAFF_READ_PERMISSIONS = grants([
    'dashboard:read',
    'students:read',
    'academic:read',
    'calendar:read',
    'messages:read',
    'messaging:read',
    'notifications:read',
]);

const CORE_SCHOOL_ADMIN_PERMISSIONS = grants([
    'admissions:*',
    'students:*',
    'guardians:*',
    'enrollment:*',
    'academic:*',
    'attendance:*',
    'fees:*',
    'invoices:*',
    'payments:*',
    'receipts:*',
    'concessions:*',
    'timetable:*',
    'substitution:*',
    'exams:*',
    'gradebook:*',
    'transport:*',
    'routes:*',
    'vehicles:*',
    'hostel:*',
    'library:*',
    'hr:*',
    'staff:*',
    'communications:*',
    'communication:*',
    'messages:*',
    'messaging:*',
    'homework:*',
    'lessonplan:*',
    'quiz:*',
    'calendar:*',
    'documents:*',
    'certificate:*',
    'credentials:*',
    'digilocker:*',
    'health:*',
    'consent:*',
    'inventory:*',
    'visitor:*',
    'alumni:*',
    'webhooks:*',
    'integrations:*',
    'workflow_approvals:*',
    'metadata:*',
    'settings:*',
    'reports:*',
    'audit:read',
]);

export const AUTHORIZATION_ROLE_PERMISSIONS = {
    PLATFORM_ADMIN: [
        grant('*', 'platform', 'Full platform operator access across tenants.'),
    ],

    SUPER_ADMIN: [
        grant('*', 'tenant', 'Full tenant operator access inside the active tenant.'),
    ],

    GROUP_EXECUTIVE: [
        ...grants(['dashboard:read', 'reports:*', 'hq:*', 'analytics:*', 'policy:read', 'audit:read']),
        grant('tenants:read', 'tenant'),
    ],

    SCHOOL_ADMIN: CORE_SCHOOL_ADMIN_PERMISSIONS,

    PRINCIPAL: [
        ...COMMON_STAFF_READ_PERMISSIONS,
        ...grants([
            'admissions:read',
            'students:read',
            'guardians:read',
            'staff:read',
            'hr:read',
            'attendance:read',
            'attendance:lock',
            'fees:read',
            'invoices:read',
            'payments:read',
            'timetable:read',
            'timetable:approve',
            'transport:read',
            'hostel:read',
            'library:read',
            'exams:read',
            'exams:review',
            'exams:publish',
            'gradebook:read',
            'gradebook:publish',
            'communications:read',
            'communications:send',
            'communication:write',
            'reports:*',
            'audit:read',
            'workflow_approvals:review',
        ]),
    ],

    REGISTRAR: [
        ...COMMON_STAFF_READ_PERMISSIONS,
        ...grants([
            'students:*',
            'guardians:*',
            'enrollment:*',
            'academic:*',
            'admissions:read',
            'admissions:update',
            'admissions:write',
            'exams:read',
            'credentials:*',
            'certificate:*',
            'digilocker:*',
            'transfer:*',
            'documents:*',
            'reports:students',
            'workflow_approvals:review',
        ]),
    ],

    FINANCE_LEAD: [
        ...COMMON_STAFF_READ_PERMISSIONS,
        ...grants([
            'fees:*',
            'invoices:*',
            'payments:*',
            'receipts:*',
            'concessions:*',
            'treasury:*',
            'reports:finance',
            'reports:fees',
            'students:read',
            'guardians:read',
            'webhooks:read',
            'audit:read',
            'workflow_approvals:*',
        ]),
    ],

    ACCOUNTANT: [
        ...COMMON_STAFF_READ_PERMISSIONS,
        ...grants([
            'fees:*',
            'invoices:*',
            'payments:*',
            'receipts:*',
            'concessions:*',
            'reports:fees',
            'students:read',
            'guardians:read',
            'workflow_approvals:create',
        ]),
    ],

    ADMISSION_COUNSELOR: [
        ...COMMON_STAFF_READ_PERMISSIONS,
        ...grants([
            'admissions:*',
            'leads:*',
            'applications:*',
            'students:read',
            'guardians:read',
            'documents:read',
            'documents:write',
            'communications:send',
            'communication:write',
            'reports:admissions',
        ]),
    ],

    STUDENT_SUCCESS_COUNSELOR: [
        ...COMMON_STAFF_READ_PERMISSIONS,
        ...grants([
            'students:read',
            'guardians:read',
            'attendance:read',
            'gradebook:read',
            'health:read',
            'welfare:*',
            'interventions:*',
            'communications:send',
            'reports:students',
        ]),
    ],

    TEACHER: [
        ...COMMON_STAFF_READ_PERMISSIONS,
        grant('profile:read', 'own'),
        grant('timetable:read', 'assigned'),
        grant('substitution:read', 'assigned'),
        grant('attendance:read', 'class'),
        grant('attendance:write', 'class'),
        grant('attendance:create', 'class'),
        grant('attendance:update', 'class'),
        grant('students:read', 'class'),
        grant('guardians:read', 'class'),
        grant('gradebook:read', 'class'),
        grant('gradebook:write', 'class'),
        grant('gradebook:update', 'class'),
        grant('diary:read', 'class'),
        grant('diary:write', 'class'),
        grant('homework:read', 'class'),
        grant('homework:write', 'class'),
        grant('lessonplan:read', 'assigned'),
        grant('lessonplan:write', 'assigned'),
        grant('quiz:read', 'class'),
        grant('quiz:write', 'class'),
        grant('appointments:read', 'assigned'),
        grant('appointments:write', 'assigned'),
        grant('messaging:write', 'assigned'),
    ],

    TRANSPORT_MANAGER: [
        ...COMMON_STAFF_READ_PERMISSIONS,
        ...grants([
            'transport:*',
            'routes:*',
            'vehicles:*',
            'students:read',
            'guardians:read',
            'reports:transport',
            'webhooks:read',
        ]),
    ],

    TRUST_OFFICER: [
        ...grants([
            'dashboard:read',
            'audit:read',
            'reports:*',
            'procurement:*',
            'policy:*',
            'fees:read',
            'payments:read',
            'treasury:read',
            'inventory:read',
        ]),
    ],

    CREDENTIAL_OFFICER: [
        ...COMMON_STAFF_READ_PERMISSIONS,
        ...grants([
            'credentials:issue',
            'credentials:revoke',
            'credentials:read',
            'certificate:read',
            'certificate:write',
            'digilocker:read',
            'digilocker:write',
            'students:read',
            'documents:read',
        ]),
    ],

    PARENT: [
        grant('dashboard:read', 'own'),
        grant('profile:read:own'),
        grant('parent:read', 'own'),
        grant('student:read:own'),
        grant('students:read:own'),
        grant('guardians:read:own'),
        grant('fees:read:own'),
        grant('invoices:read:own'),
        grant('payments:create:own'),
        grant('payments:read:own'),
        grant('receipts:read:own'),
        grant('transport:read:own'),
        grant('attendance:read:own'),
        grant('gradebook:read:own'),
        grant('homework:read:own'),
        grant('timetable:read:own'),
        grant('messages:read:own'),
        grant('messaging:read:own'),
        grant('appointments:read:own'),
        grant('documents:read:own'),
        grant('health:read:own'),
        grant('consent:read:own'),
        grant('consent:write:own'),
    ],

    STUDENT: [
        grant('dashboard:read', 'own'),
        grant('profile:read:own'),
        grant('student:read:own'),
        grant('students:read:own'),
        grant('timetable:read:own'),
        grant('attendance:read:own'),
        grant('gradebook:read:own'),
        grant('homework:read:own'),
        grant('lessonplan:read:own'),
        grant('quiz:read:own'),
        grant('library:read:own'),
        grant('hostel:read:own'),
        grant('transport:read:own'),
        grant('messages:read:own'),
        grant('messaging:read:own'),
        grant('documents:read:own'),
        grant('health:read:own'),
    ],
} as const satisfies Record<AuthorizationRole, readonly PermissionGrant[]>;

export const AUTHORIZATION_FIELD_POLICIES = [
    {
        resource: 'students',
        fields: ['aadhaarNumber', 'apaarId', 'dateOfBirth', 'medicalNotes', 'address', 'category', 'bloodGroup'],
        readRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'SCHOOL_ADMIN', 'PRINCIPAL', 'REGISTRAR', 'STUDENT_SUCCESS_COUNSELOR'],
        writeRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'SCHOOL_ADMIN', 'REGISTRAR'],
        classification: 'student_pii',
        description: 'Sensitive student identity and health fields require registrar-grade access.',
    },
    {
        resource: 'guardians',
        fields: ['email', 'phone', 'address', 'annualIncome', 'occupation', 'relationship'],
        readRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'SCHOOL_ADMIN', 'PRINCIPAL', 'REGISTRAR', 'ACCOUNTANT', 'FINANCE_LEAD'],
        writeRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'SCHOOL_ADMIN', 'REGISTRAR'],
        classification: 'student_pii',
        description: 'Guardian contact and socioeconomic data is visible only where operationally required.',
    },
    {
        resource: 'staff_profiles',
        fields: ['salary', 'bankAccountNumber', 'ifscCode', 'panNumber', 'aadhaarNumber', 'emergencyContact'],
        readRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'SCHOOL_ADMIN', 'FINANCE_LEAD'],
        writeRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'SCHOOL_ADMIN'],
        classification: 'staff_pii',
        description: 'Staff compensation and identity data is restricted to administrators and finance leadership.',
    },
    {
        resource: 'payments',
        fields: ['providerPaymentId', 'providerOrderId', 'providerSignature', 'gatewayResponse', 'refundReference'],
        readRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'SCHOOL_ADMIN', 'FINANCE_LEAD', 'ACCOUNTANT'],
        writeRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'FINANCE_LEAD'],
        classification: 'financial',
        description: 'Payment provider identifiers and signatures are financial control data.',
    },
    {
        resource: 'invoices',
        fields: ['concessionReason', 'waiverReason', 'internalNotes', 'reconciliationStatus'],
        readRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'SCHOOL_ADMIN', 'FINANCE_LEAD', 'ACCOUNTANT'],
        writeRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'FINANCE_LEAD', 'ACCOUNTANT'],
        classification: 'financial',
        description: 'Invoice adjustments and reconciliation notes require finance access.',
    },
    {
        resource: 'integrations',
        fields: ['apiKeyHash', 'webhookSecretHash', 'providerSecretRef', 'lastPayload'],
        readRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'SCHOOL_ADMIN'],
        writeRoles: ['PLATFORM_ADMIN', 'SUPER_ADMIN', 'SCHOOL_ADMIN'],
        classification: 'secret',
        description: 'Integration secrets and payloads are restricted to tenant administrators.',
    },
] as const satisfies readonly FieldPolicy[];

export const AUTHORIZATION_APPROVAL_POLICIES = [
    {
        id: 'fees.invoice.waive',
        label: 'Waive invoice balance',
        permission: 'fees:approve',
        requiredApproverRoles: ['FINANCE_LEAD', 'SCHOOL_ADMIN', 'SUPER_ADMIN'],
        minApprovals: 1,
        requiresReason: true,
        auditAction: 'fees.invoice.waive',
        description: 'Fee waivers require a finance leader or tenant administrator and an auditable reason.',
    },
    {
        id: 'fees.invoice.cancel',
        label: 'Cancel invoice',
        permission: 'fees:approve',
        requiredApproverRoles: ['FINANCE_LEAD', 'SCHOOL_ADMIN', 'SUPER_ADMIN'],
        minApprovals: 1,
        requiresReason: true,
        auditAction: 'fees.invoice.cancel',
        description: 'Invoice cancellation is a controlled finance mutation.',
    },
    {
        id: 'payments.refund',
        label: 'Refund payment',
        permission: 'payments:refund',
        requiredApproverRoles: ['FINANCE_LEAD', 'SUPER_ADMIN'],
        minApprovals: 1,
        requiresReason: true,
        auditAction: 'payments.refund',
        description: 'Refunds require finance leadership review before provider execution.',
    },
    {
        id: 'students.transfer',
        label: 'Transfer student',
        permission: 'students:update',
        requiredApproverRoles: ['REGISTRAR', 'SCHOOL_ADMIN', 'SUPER_ADMIN'],
        minApprovals: 1,
        requiresReason: true,
        auditAction: 'students.transfer',
        description: 'Transfers alter enrollment state and require registrar-level accountability.',
    },
    {
        id: 'students.archive',
        label: 'Archive student',
        permission: 'students:archive',
        requiredApproverRoles: ['REGISTRAR', 'SCHOOL_ADMIN', 'SUPER_ADMIN'],
        minApprovals: 1,
        requiresReason: true,
        auditAction: 'students.archive',
        description: 'Student archival is a terminal lifecycle action.',
    },
    {
        id: 'exams.results.publish',
        label: 'Publish exam results',
        permission: 'exams:publish',
        requiredApproverRoles: ['PRINCIPAL', 'SCHOOL_ADMIN', 'SUPER_ADMIN'],
        minApprovals: 1,
        requiresReason: false,
        auditAction: 'exams.results.publish',
        description: 'Result publication requires academic leadership approval.',
    },
    {
        id: 'users.role_change',
        label: 'Change user role',
        permission: 'settings:write',
        requiredApproverRoles: ['SCHOOL_ADMIN', 'SUPER_ADMIN'],
        minApprovals: 1,
        requiresReason: true,
        auditAction: 'users.role_change',
        description: 'Role changes alter the authorization boundary and must be reviewed.',
    },
    {
        id: 'data.export_pii',
        label: 'Export PII',
        permission: 'reports:export',
        requiredApproverRoles: ['SCHOOL_ADMIN', 'SUPER_ADMIN', 'PLATFORM_ADMIN'],
        minApprovals: 1,
        requiresReason: true,
        auditAction: 'data.export_pii',
        description: 'Bulk PII export requires administrator approval and audit context.',
    },
    {
        id: 'metadata.publish',
        label: 'Publish metadata model',
        permission: 'metadata:publish',
        requiredApproverRoles: ['SCHOOL_ADMIN', 'SUPER_ADMIN'],
        minApprovals: 1,
        requiresReason: true,
        auditAction: 'metadata.publish',
        description: 'Metadata model publication can change runtime schema behavior.',
    },
    {
        id: 'agents.approval.review',
        label: 'Review AI agent approval',
        permission: 'agents:approve',
        requiredApproverRoles: ['SCHOOL_ADMIN', 'SUPER_ADMIN', 'PLATFORM_ADMIN'],
        minApprovals: 1,
        requiresReason: true,
        auditAction: 'agents.approval.review',
        description: 'Agent actions that touch tenant data require a human approval trail.',
    },
] as const satisfies readonly ApprovalPolicy[];

export const AUTHORIZATION_ROUTE_POLICIES = [
    { prefix: '/platform', permission: 'platform:read', scope: 'platform', description: 'Platform operator area.' },
    { prefix: '/hq', permission: 'hq:read', scope: 'tenant', description: 'Group executive and tenant HQ area.' },
    { prefix: '/dashboard', permission: 'dashboard:read', scope: 'tenant', description: 'Authenticated tenant dashboard.' },
    { prefix: '/fees', permission: 'fees:read', scope: 'tenant', description: 'Tenant finance workspace.' },
    { prefix: '/my-fees', permission: 'fees:read', scope: 'own', description: 'Parent or student owned fee view.' },
    { prefix: '/students', permission: 'students:read', scope: 'tenant', description: 'Tenant enrollment workspace.' },
    { prefix: '/admissions', permission: 'admissions:read', scope: 'tenant', description: 'Admissions workspace.' },
    { prefix: '/attendance', permission: 'attendance:read', scope: 'tenant', description: 'Attendance workspace.' },
    { prefix: '/my-attendance', permission: 'attendance:read', scope: 'own', description: 'Student attendance view.' },
    { prefix: '/teacher', permission: 'timetable:read', scope: 'assigned', description: 'Teacher assigned workload area.' },
    { prefix: '/transport', permission: 'transport:read', scope: 'tenant', description: 'Transport operations.' },
    { prefix: '/my-transport', permission: 'transport:read', scope: 'own', description: 'Owned transport assignment view.' },
    { prefix: '/hostel', permission: 'hostel:read', scope: 'tenant', description: 'Hostel operations.' },
    { prefix: '/library', permission: 'library:read', scope: 'tenant', description: 'Library operations.' },
    { prefix: '/exams', permission: 'exams:read', scope: 'tenant', description: 'Exam operations.' },
    { prefix: '/analytics', permission: 'reports:read', scope: 'tenant', description: 'Tenant analytics workspace.' },
    { prefix: '/reports', permission: 'reports:read', scope: 'tenant', description: 'Tenant reports.' },
    { prefix: '/settings', permission: 'settings:read', scope: 'tenant', description: 'Tenant settings.' },
    { prefix: '/operator', permission: 'audit:read', scope: 'tenant', description: 'Tenant operator console boundary.' },
    { prefix: '/api/platform', permission: 'platform:read', scope: 'platform', description: 'Platform API boundary.' },
    { prefix: '/api/analytics', permission: 'reports:read', scope: 'tenant', description: 'Tenant analytics API boundary.' },
    { prefix: '/api/workflow-approvals', permission: 'workflow_approvals:read', scope: 'tenant', description: 'Tenant workflow approval API boundary.' },
    { prefix: '/api/operator', permission: 'audit:read', scope: 'tenant', description: 'Operator console API boundary.' },
    { prefix: '/api/integrations', permission: 'integrations:read', scope: 'tenant', description: 'Tenant integrations API boundary.' },
    { prefix: '/api/webhooks', permission: 'webhooks:read', scope: 'tenant', description: 'Tenant webhook API boundary.' },
] as const satisfies readonly RoutePolicy[];
