import { CORE_SIS_DOMAIN_EVENTS } from './events';
import type { CoreSisBoundedContext, CoreSisModuleId } from './types';

export const CORE_SIS_MODULES = [
    {
        id: 'admissions',
        label: 'Admissions',
        ownerRole: 'ADMISSION_OFFICER',
        description: 'Lead capture, application review, document collection, interviews, offers, and enrollment handoff.',
        primaryEntities: ['Admission Lead', 'Admission Application', 'Admission Document'],
        primaryTables: ['admission_leads', 'admission_applications', 'admission_documents'],
        routes: ['/admissions', '/admissions/new', '/admissions/[id]', '/admissions/[id]/documents'],
        services: ['admissions actions', 'storage service', 'notifications service'],
        stateMachines: ['admissionLead'],
        dependsOn: ['enrollment', 'communications'],
        permissions: ['admissions:read', 'admissions:create', 'admissions:update', 'admissions:review'],
        emittedEvents: CORE_SIS_DOMAIN_EVENTS.admissions.map((event) => event.name),
        invariants: [
            'Admission leads and applications are always tenant-scoped.',
            'Enrollment conversion can only happen from ACCEPTED.',
            'Rejection and withdrawal transitions require a reason.',
        ],
        asyncWorkflows: ['document verification notifications', 'offer acceptance reminders', 'enrollment conversion jobs'],
        operationalReports: ['admission pipeline', 'application conversion funnel', 'document pending queue'],
        dataClassification: ['student_pii', 'operational'],
        tenantScoped: true,
        auditRequired: true,
    },
    {
        id: 'enrollment',
        label: 'Enrollment',
        ownerRole: 'ACADEMIC_ADMIN',
        description: 'Student lifecycle, guardians, class placement, roll numbers, and academic-year enrollment state.',
        primaryEntities: ['Student', 'Guardian', 'Grade', 'Section', 'Academic Year'],
        primaryTables: ['students', 'guardians', 'grades', 'sections', 'academic_years'],
        routes: ['/students', '/schools', '/settings/school'],
        services: ['student actions', 'tenant isolation primitives', 'storage service'],
        stateMachines: ['studentEnrollment'],
        dependsOn: ['admissions', 'fees', 'transport', 'hostel'],
        permissions: ['students:read', 'students:create', 'students:update', 'students:archive'],
        emittedEvents: CORE_SIS_DOMAIN_EVENTS.enrollment.map((event) => event.name),
        invariants: [
            'Student status changes use the studentEnrollment transition matrix.',
            'Guardian and student tenant IDs must always match.',
            'Transferred and alumni students are terminal enrollment states.',
        ],
        asyncWorkflows: ['guardian account provisioning', 'student document indexing', 'class roster refresh'],
        operationalReports: ['active enrollment by class', 'gender/category mix', 'withdrawal and transfer report'],
        dataClassification: ['student_pii', 'academic'],
        tenantScoped: true,
        auditRequired: true,
    },
    {
        id: 'attendance',
        label: 'Attendance',
        ownerRole: 'ATTENDANCE_COORDINATOR',
        description: 'Daily section attendance, corrections, IoT ingest, parent notifications, and attendance analytics.',
        primaryEntities: ['Attendance Record'],
        primaryTables: ['attendance_records'],
        routes: ['/attendance', '/attendance/mark/[classId]', '/attendance/reports', '/my-attendance'],
        services: ['attendance API', 'IoT ingest API', 'notifications service'],
        stateMachines: ['attendanceRecord'],
        dependsOn: ['enrollment', 'communications'],
        permissions: ['attendance:read', 'attendance:create', 'attendance:update', 'attendance:lock'],
        emittedEvents: CORE_SIS_DOMAIN_EVENTS.attendance.map((event) => event.name),
        invariants: [
            'Attendance is marked for an existing tenant-scoped student and section.',
            'Corrections after initial marking require a reason and audit entry.',
            'Parent notifications are emitted from trusted attendance events only.',
        ],
        asyncWorkflows: ['absence notifications', 'attendance rollup refresh', 'IoT scan reconciliation'],
        operationalReports: ['daily attendance', 'monthly attendance percentage', 'absence trends'],
        dataClassification: ['student_pii', 'operational'],
        tenantScoped: true,
        auditRequired: true,
    },
    {
        id: 'timetable',
        label: 'Timetable',
        ownerRole: 'ACADEMIC_ADMIN',
        description: 'Periods, class schedules, teacher assignments, room usage, conflict detection, and substitutions.',
        primaryEntities: ['Period', 'Timetable Entry', 'Substitution Request', 'Substitution'],
        primaryTables: ['periods', 'timetable_entries', 'substitution_requests', 'substitutions'],
        routes: ['/timetable', '/timetable/grid', '/timetable/new', '/timetable/substitution'],
        services: ['timetable service', 'conflict detector'],
        stateMachines: ['substitutionRequest'],
        dependsOn: ['enrollment', 'hr', 'communications'],
        permissions: ['timetable:read', 'timetable:create', 'timetable:update', 'timetable:approve'],
        emittedEvents: CORE_SIS_DOMAIN_EVENTS.timetable.map((event) => event.name),
        invariants: [
            'Teacher, room, section, day, and period conflicts must be checked before persistence.',
            'Substitution requests can be approved, rejected, or cancelled only from pending.',
            'Timetable entries must reference tenant-compatible sections, periods, subjects, and teachers.',
        ],
        asyncWorkflows: ['substitution notifications', 'teacher schedule refresh', 'conflict alert dispatch'],
        operationalReports: ['teacher load', 'room utilization', 'substitution history'],
        dataClassification: ['operational', 'staff_pii'],
        tenantScoped: true,
        auditRequired: true,
    },
    {
        id: 'exams',
        label: 'Exams',
        ownerRole: 'EXAM_CONTROLLER',
        description: 'Exam planning, schedules, marks entry windows, result review, publishing, and compliance locks.',
        primaryEntities: ['Exam', 'Exam Schedule', 'Student Result', 'Exam Result Hash'],
        primaryTables: ['exams', 'exam_schedules', 'student_results', 'exam_result_hashes'],
        routes: ['/exams', '/exams/create', '/exams/[examId]', '/exams/report-cards', '/exams/verification'],
        services: ['rank computation service', 'report card generator', 'exam APIs'],
        stateMachines: ['examLifecycle'],
        dependsOn: ['enrollment', 'gradebook', 'communications'],
        permissions: ['exams:read', 'exams:create', 'exams:update', 'exams:review', 'exams:publish'],
        emittedEvents: CORE_SIS_DOMAIN_EVENTS.exams.map((event) => event.name),
        invariants: [
            'Marks cannot be published before result review.',
            'Published results are hash-locked for tamper evidence.',
            'Cancelled exams cannot accept marks.',
        ],
        asyncWorkflows: ['report-card generation', 'result publish notifications', 'hash verification exports'],
        operationalReports: ['exam schedule', 'marks entry progress', 'result publication status'],
        dataClassification: ['student_pii', 'academic'],
        tenantScoped: true,
        auditRequired: true,
    },
    {
        id: 'gradebook',
        label: 'Gradebook',
        ownerRole: 'EXAM_CONTROLLER',
        description: 'Continuous assessments, teacher score entry, grade computation, and report-card source data.',
        primaryEntities: ['Assessment', 'Score', 'Gradebook Entry'],
        primaryTables: ['student_results', 'grades', 'subjects'],
        routes: ['/teacher/gradebook', '/teacher/my-classes', '/my-results'],
        services: ['gradebook service', 'rank computation service'],
        stateMachines: [],
        dependsOn: ['enrollment', 'exams'],
        permissions: ['gradebook:read', 'gradebook:update', 'gradebook:publish'],
        emittedEvents: CORE_SIS_DOMAIN_EVENTS.gradebook.map((event) => event.name),
        invariants: [
            'Score entry must be scoped to teacher, class, subject, and tenant.',
            'Published scores must feed the exams/report-card workflow through controlled events.',
            'Grade computation must be deterministic for the same grading policy version.',
        ],
        asyncWorkflows: ['rank recomputation', 'report-card rebuild', 'parent result notification'],
        operationalReports: ['class performance', 'subject performance', 'teacher completion status'],
        dataClassification: ['student_pii', 'academic'],
        tenantScoped: true,
        auditRequired: true,
    },
    {
        id: 'fees',
        label: 'Fees',
        ownerRole: 'FEE_MANAGER',
        description: 'Fee plans, invoices, payments, concessions, receipts, cashflow, and collections follow-up.',
        primaryEntities: ['Fee Plan', 'Invoice', 'Payment', 'Receipt', 'Concession'],
        primaryTables: ['fee_plans', 'invoices', 'payments', 'receipts', 'concessions'],
        routes: ['/fees', '/fees/generate', '/fees/cashflow', '/fees/defaulters', '/my-fees'],
        services: ['fee engine service', 'cashflow service', 'payment ledger'],
        stateMachines: ['invoiceLifecycle'],
        dependsOn: ['enrollment', 'communications'],
        permissions: ['fees:read', 'fees:create', 'fees:update', 'fees:approve'],
        emittedEvents: CORE_SIS_DOMAIN_EVENTS.fees.map((event) => event.name),
        invariants: [
            'Invoice ownership is tenant and student scoped.',
            'Money movement must be reconciled with payment provider events.',
            'Waivers and cancellations require approval and audit evidence.',
        ],
        asyncWorkflows: ['receipt generation', 'payment reconciliation', 'defaulter notifications'],
        operationalReports: ['cashflow forecast', 'outstanding summary', 'defaulter list'],
        dataClassification: ['student_pii', 'financial'],
        tenantScoped: true,
        auditRequired: true,
    },
    {
        id: 'transport',
        label: 'Transport',
        ownerRole: 'TRANSPORT_MANAGER',
        description: 'Vehicles, routes, stops, student assignments, driver compliance, maintenance, and GPS pings.',
        primaryEntities: ['Vehicle', 'Route', 'Stop', 'Student Transport Assignment', 'GPS Ping'],
        primaryTables: ['vehicles', 'routes', 'stops', 'student_transport', 'live_gps_pings'],
        routes: ['/transport', '/transport/new', '/transport/[id]', '/my-transport'],
        services: ['transport service'],
        stateMachines: [],
        dependsOn: ['enrollment', 'fees', 'communications'],
        permissions: ['transport:read', 'transport:create', 'transport:update', 'transport:assign'],
        emittedEvents: CORE_SIS_DOMAIN_EVENTS.transport.map((event) => event.name),
        invariants: [
            'Student transport assignment must reference tenant-compatible route and stop.',
            'Vehicle capacity should not be exceeded by active assignments.',
            'Driver compliance and vehicle maintenance events must be auditable.',
        ],
        asyncWorkflows: ['GPS location ingest', 'maintenance reminders', 'route assignment notifications'],
        operationalReports: ['route occupancy', 'vehicle maintenance due', 'student route list'],
        dataClassification: ['student_pii', 'operational'],
        tenantScoped: true,
        auditRequired: true,
    },
    {
        id: 'library',
        label: 'Library',
        ownerRole: 'LIBRARIAN',
        description: 'Books, issue/return lifecycle, reservations, overdue tracking, fines, and inventory counts.',
        primaryEntities: ['Book', 'Book Issue', 'Book Reservation'],
        primaryTables: ['books', 'book_issues', 'book_reservations'],
        routes: ['/library', '/library/issue', '/library/history'],
        services: ['library service'],
        stateMachines: ['libraryIssue'],
        dependsOn: ['enrollment', 'fees', 'communications'],
        permissions: ['library:read', 'library:create', 'library:update', 'library:fine'],
        emittedEvents: CORE_SIS_DOMAIN_EVENTS.library.map((event) => event.name),
        invariants: [
            'Available copies cannot go below zero.',
            'Book issue lifecycle must use libraryIssue transitions.',
            'Lost or overdue fines must be tied back to fee/ledger workflows when charged.',
        ],
        asyncWorkflows: ['overdue reminders', 'fine posting', 'reservation expiry'],
        operationalReports: ['issued books', 'overdue books', 'inventory utilization'],
        dataClassification: ['student_pii', 'operational'],
        tenantScoped: true,
        auditRequired: true,
    },
    {
        id: 'hostel',
        label: 'Hostel',
        ownerRole: 'HOSTEL_WARDEN',
        description: 'Hostels, rooms, bed allocation, mess menu, occupancy, hostel fee ownership, and vacating lifecycle.',
        primaryEntities: ['Hostel', 'Hostel Room', 'Hostel Allocation', 'Mess Menu', 'Hostel Fee'],
        primaryTables: ['hostels', 'hostel_rooms', 'hostel_allocations', 'mess_menus', 'hostel_fees'],
        routes: ['/hostel', '/hostel/fees'],
        services: ['hostel service'],
        stateMachines: ['hostelAllocation'],
        dependsOn: ['enrollment', 'fees', 'communications'],
        permissions: ['hostel:read', 'hostel:create', 'hostel:update', 'hostel:assign'],
        emittedEvents: CORE_SIS_DOMAIN_EVENTS.hostel.map((event) => event.name),
        invariants: [
            'Occupied beds cannot exceed total beds.',
            'Only one active hostel allocation should exist for a student in a date range.',
            'Vacating an allocation must release room occupancy.',
        ],
        asyncWorkflows: ['allocation notifications', 'occupancy rollups', 'hostel fee posting'],
        operationalReports: ['hostel occupancy', 'room availability', 'hostel fee dues'],
        dataClassification: ['student_pii', 'operational', 'financial'],
        tenantScoped: true,
        auditRequired: true,
    },
    {
        id: 'hr',
        label: 'HR',
        ownerRole: 'HR_MANAGER',
        description: 'Staff profiles, departments, designations, leave policies, leave approvals, and teacher staffing data.',
        primaryEntities: ['Staff Profile', 'Department', 'Designation', 'Leave Policy', 'Leave Request'],
        primaryTables: ['staff_profiles', 'staff_departments', 'designations', 'leave_policies', 'leave_requests'],
        routes: ['/settings/users', '/teacher/profile', '/teacher/schedule'],
        services: ['hr service'],
        stateMachines: ['leaveRequest'],
        dependsOn: ['timetable', 'communications'],
        permissions: ['hr:read', 'hr:create', 'hr:update', 'hr:approve'],
        emittedEvents: CORE_SIS_DOMAIN_EVENTS.hr.map((event) => event.name),
        invariants: [
            'Staff profile user and tenant must match.',
            'Leave approvals must follow leaveRequest transitions.',
            'Teacher availability affects timetable and substitution workflows.',
        ],
        asyncWorkflows: ['leave balance updates', 'substitution request creation', 'staff onboarding notifications'],
        operationalReports: ['staff directory', 'leave approval queue', 'department staffing'],
        dataClassification: ['staff_pii', 'operational'],
        tenantScoped: true,
        auditRequired: true,
    },
    {
        id: 'communications',
        label: 'Communications',
        ownerRole: 'COMMUNICATIONS_ADMIN',
        description: 'Tenant-scoped notices, parent/staff/student messages, templates, delivery tracking, and notification outbox.',
        primaryEntities: ['Message', 'Message Template', 'Message Log', 'Notification Outbox Item'],
        primaryTables: ['messages', 'message_templates', 'message_logs', 'notification_outbox'],
        routes: ['/messages', '/messages/templates', '/alerts'],
        services: ['messages service', 'notifications service', 'outbox dispatcher'],
        stateMachines: [],
        dependsOn: ['enrollment'],
        permissions: ['communications:read', 'communications:create', 'communications:update', 'communications:send'],
        emittedEvents: CORE_SIS_DOMAIN_EVENTS.communications.map((event) => event.name),
        invariants: [
            'Communication recipients must resolve from tenant-scoped context.',
            'Delivery provider payloads must not leak cross-tenant identifiers.',
            'Failed sends must be retryable and auditable.',
        ],
        asyncWorkflows: ['outbox dispatch', 'delivery retry', 'template rendering'],
        operationalReports: ['message delivery status', 'failed delivery queue', 'template usage'],
        dataClassification: ['student_pii', 'staff_pii', 'operational'],
        tenantScoped: true,
        auditRequired: true,
    },
] as const satisfies readonly CoreSisBoundedContext[];

export const CORE_SIS_MODULE_IDS = CORE_SIS_MODULES.map((module) => module.id);

export function listCoreSisModules(): readonly CoreSisBoundedContext[] {
    return CORE_SIS_MODULES;
}

export function getCoreSisModule(moduleId: CoreSisModuleId): CoreSisBoundedContext {
    const module = CORE_SIS_MODULES.find((candidate) => candidate.id === moduleId);
    if (!module) {
        throw new Error(`Unknown Core SIS module: ${moduleId}`);
    }
    return module;
}

export function findCoreSisModuleByRoute(route: string): CoreSisBoundedContext | null {
    return CORE_SIS_MODULES.find((module) => module.routes.some((prefix) => route === prefix || route.startsWith(`${prefix}/`))) ?? null;
}
