// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { default as EventType } from './EventType';
import type { default as AudienceType } from './AudienceType';
import type { UsersId } from './Users';

/** Identifier type for public.academic_events */
export type AcademicEventsId = string & { __brand: 'public.academic_events' };

/** Represents the table public.academic_events */
export default interface AcademicEvents {
  id: AcademicEventsId;

  tenant_id: TenantsId;

  title: string;

  description: string | null;

  event_type: EventType;

  start_date: Date;

  end_date: Date | null;

  is_all_day: boolean;

  start_time: string | null;

  end_time: string | null;

  venue: string | null;

  audience_type: AudienceType;

  created_by: UsersId | null;

  is_recurring: boolean;

  color: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.academic_events */
export interface AcademicEventsInitializer {
  /** Default value: gen_random_uuid() */
  id?: AcademicEventsId;

  tenant_id: TenantsId;

  title: string;

  description?: string | null;

  event_type: EventType;

  start_date: Date;

  end_date?: Date | null;

  /** Default value: true */
  is_all_day?: boolean;

  start_time?: string | null;

  end_time?: string | null;

  venue?: string | null;

  /** Default value: 'ALL'::audience_type */
  audience_type?: AudienceType;

  created_by?: UsersId | null;

  /** Default value: false */
  is_recurring?: boolean;

  color?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.academic_events */
export interface AcademicEventsMutator {
  id?: AcademicEventsId;

  tenant_id?: TenantsId;

  title?: string;

  description?: string | null;

  event_type?: EventType;

  start_date?: Date;

  end_date?: Date | null;

  is_all_day?: boolean;

  start_time?: string | null;

  end_time?: string | null;

  venue?: string | null;

  audience_type?: AudienceType;

  created_by?: UsersId | null;

  is_recurring?: boolean;

  color?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
