// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';

/** Identifier type for public.academic_years */
export type AcademicYearsId = string & { __brand: 'public.academic_years' };

/** Represents the table public.academic_years */
export default interface AcademicYears {
  id: AcademicYearsId;

  tenant_id: TenantsId;

  name: string;

  start_date: Date;

  end_date: Date;

  is_current: boolean;

  created_at: Date;
}

/** Represents the initializer for the table public.academic_years */
export interface AcademicYearsInitializer {
  /** Default value: gen_random_uuid() */
  id?: AcademicYearsId;

  tenant_id: TenantsId;

  name: string;

  start_date: Date;

  end_date: Date;

  /** Default value: false */
  is_current?: boolean;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.academic_years */
export interface AcademicYearsMutator {
  id?: AcademicYearsId;

  tenant_id?: TenantsId;

  name?: string;

  start_date?: Date;

  end_date?: Date;

  is_current?: boolean;

  created_at?: Date;
}
