// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { AdmissionLeadsId } from './AdmissionLeads';

/** Identifier type for public.admission_applications */
export type AdmissionApplicationsId = string & { __brand: 'public.admission_applications' };

/** Represents the table public.admission_applications */
export default interface AdmissionApplications {
  id: AdmissionApplicationsId;

  tenant_id: TenantsId;

  lead_id: AdmissionLeadsId;

  application_number: string;

  form_data: unknown | null;

  submitted_at: Date | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.admission_applications */
export interface AdmissionApplicationsInitializer {
  /** Default value: gen_random_uuid() */
  id?: AdmissionApplicationsId;

  tenant_id: TenantsId;

  lead_id: AdmissionLeadsId;

  application_number: string;

  form_data?: unknown | null;

  submitted_at?: Date | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.admission_applications */
export interface AdmissionApplicationsMutator {
  id?: AdmissionApplicationsId;

  tenant_id?: TenantsId;

  lead_id?: AdmissionLeadsId;

  application_number?: string;

  form_data?: unknown | null;

  submitted_at?: Date | null;

  created_at?: Date;

  updated_at?: Date;
}
