// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CompaniesId } from './Companies';
import type { TenantsId } from './Tenants';

/** Identifier type for public.ai_token_logs */
export type AiTokenLogsId = string & { __brand: 'public.ai_token_logs' };

/** Represents the table public.ai_token_logs */
export default interface AiTokenLogs {
  id: AiTokenLogsId;

  company_id: CompaniesId;

  tenant_id: TenantsId;

  agent_type: string;

  model: string;

  tokens_used: number;

  compute_cost_ms: number;

  query_cost_usd: string;

  created_at: Date;
}

/** Represents the initializer for the table public.ai_token_logs */
export interface AiTokenLogsInitializer {
  /** Default value: gen_random_uuid() */
  id?: AiTokenLogsId;

  company_id: CompaniesId;

  tenant_id: TenantsId;

  agent_type: string;

  model: string;

  tokens_used: number;

  compute_cost_ms: number;

  /** Default value: '0'::numeric */
  query_cost_usd?: string;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.ai_token_logs */
export interface AiTokenLogsMutator {
  id?: AiTokenLogsId;

  company_id?: CompaniesId;

  tenant_id?: TenantsId;

  agent_type?: string;

  model?: string;

  tokens_used?: number;

  compute_cost_ms?: number;

  query_cost_usd?: string;

  created_at?: Date;
}
