// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { default as AlumniEventType } from './AlumniEventType';
import type { UsersId } from './Users';
import type { default as AlumniEventStatus } from './AlumniEventStatus';

/** Identifier type for public.alumni_events */
export type AlumniEventsId = string & { __brand: 'public.alumni_events' };

/** Represents the table public.alumni_events */
export default interface AlumniEvents {
  id: AlumniEventsId;

  tenant_id: TenantsId;

  title: string;

  description: string | null;

  date: Date;

  time: string | null;

  venue: string | null;

  type: AlumniEventType;

  organizer_id: UsersId | null;

  max_capacity: number | null;

  status: AlumniEventStatus;

  created_at: Date;
}

/** Represents the initializer for the table public.alumni_events */
export interface AlumniEventsInitializer {
  /** Default value: gen_random_uuid() */
  id?: AlumniEventsId;

  tenant_id: TenantsId;

  title: string;

  description?: string | null;

  date: Date;

  time?: string | null;

  venue?: string | null;

  type: AlumniEventType;

  organizer_id?: UsersId | null;

  max_capacity?: number | null;

  /** Default value: 'UPCOMING'::alumni_event_status */
  status?: AlumniEventStatus;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.alumni_events */
export interface AlumniEventsMutator {
  id?: AlumniEventsId;

  tenant_id?: TenantsId;

  title?: string;

  description?: string | null;

  date?: Date;

  time?: string | null;

  venue?: string | null;

  type?: AlumniEventType;

  organizer_id?: UsersId | null;

  max_capacity?: number | null;

  status?: AlumniEventStatus;

  created_at?: Date;
}
