// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.alumni_event_type */
enum AlumniEventType {
  REUNION = 'REUNION',
  NETWORKING = 'NETWORKING',
  CAREER_TALK = 'CAREER_TALK',
  WORKSHOP = 'WORKSHOP',
  FUNDRAISER = 'FUNDRAISER',
};

export default AlumniEventType;
