// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { AlumniEventsId } from './AlumniEvents';
import type { AlumniProfilesId } from './AlumniProfiles';

/** Identifier type for public.alumni_registrations */
export type AlumniRegistrationsId = string & { __brand: 'public.alumni_registrations' };

/** Represents the table public.alumni_registrations */
export default interface AlumniRegistrations {
  id: AlumniRegistrationsId;

  tenant_id: TenantsId;

  event_id: AlumniEventsId;

  alumni_id: AlumniProfilesId;

  registered_at: Date;
}

/** Represents the initializer for the table public.alumni_registrations */
export interface AlumniRegistrationsInitializer {
  /** Default value: gen_random_uuid() */
  id?: AlumniRegistrationsId;

  tenant_id: TenantsId;

  event_id: AlumniEventsId;

  alumni_id: AlumniProfilesId;

  /** Default value: now() */
  registered_at?: Date;
}

/** Represents the mutator for the table public.alumni_registrations */
export interface AlumniRegistrationsMutator {
  id?: AlumniRegistrationsId;

  tenant_id?: TenantsId;

  event_id?: AlumniEventsId;

  alumni_id?: AlumniProfilesId;

  registered_at?: Date;
}
