// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.asset_category */
enum AssetCategory {
  FURNITURE = 'FURNITURE',
  IT_EQUIPMENT = 'IT_EQUIPMENT',
  SPORTS = 'SPORTS',
  LAB_EQUIPMENT = 'LAB_EQUIPMENT',
  AUDIO_VISUAL = 'AUDIO_VISUAL',
  OTHER = 'OTHER',
};

export default AssetCategory;
