// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { StudentsId } from './Students';
import type { SectionsId } from './Sections';
import type { default as AttendanceStatus } from './AttendanceStatus';
import type { UsersId } from './Users';

/** Identifier type for public.attendance_records */
export type AttendanceRecordsId = string & { __brand: 'public.attendance_records' };

/** Represents the table public.attendance_records */
export default interface AttendanceRecords {
  id: AttendanceRecordsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  section_id: SectionsId;

  date: Date;

  status: AttendanceStatus;

  marked_by: UsersId;

  remarks: string | null;

  is_notified: boolean;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.attendance_records */
export interface AttendanceRecordsInitializer {
  /** Default value: gen_random_uuid() */
  id?: AttendanceRecordsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  section_id: SectionsId;

  date: Date;

  status: AttendanceStatus;

  marked_by: UsersId;

  remarks?: string | null;

  /** Default value: false */
  is_notified?: boolean;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.attendance_records */
export interface AttendanceRecordsMutator {
  id?: AttendanceRecordsId;

  tenant_id?: TenantsId;

  student_id?: StudentsId;

  section_id?: SectionsId;

  date?: Date;

  status?: AttendanceStatus;

  marked_by?: UsersId;

  remarks?: string | null;

  is_notified?: boolean;

  created_at?: Date;

  updated_at?: Date;
}
