// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.attendance_status */
enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LATE = 'LATE',
  HALF_DAY = 'HALF_DAY',
  EXCUSED = 'EXCUSED',
  HOLIDAY = 'HOLIDAY',
};

export default AttendanceStatus;
