// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { UsersId } from './Users';
import type { default as AuditAction } from './AuditAction';

/** Identifier type for public.audit_logs */
export type AuditLogsId = string & { __brand: 'public.audit_logs' };

/** Represents the table public.audit_logs */
export default interface AuditLogs {
  id: AuditLogsId;

  tenant_id: TenantsId;

  user_id: UsersId | null;

  action: AuditAction;

  entity_type: string;

  entity_id: string | null;

  description: string | null;

  before_state: unknown | null;

  after_state: unknown | null;

  ip_address: string | null;

  user_agent: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.audit_logs */
export interface AuditLogsInitializer {
  /** Default value: gen_random_uuid() */
  id?: AuditLogsId;

  tenant_id: TenantsId;

  user_id?: UsersId | null;

  action: AuditAction;

  entity_type: string;

  entity_id?: string | null;

  description?: string | null;

  before_state?: unknown | null;

  after_state?: unknown | null;

  ip_address?: string | null;

  user_agent?: string | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.audit_logs */
export interface AuditLogsMutator {
  id?: AuditLogsId;

  tenant_id?: TenantsId;

  user_id?: UsersId | null;

  action?: AuditAction;

  entity_type?: string;

  entity_id?: string | null;

  description?: string | null;

  before_state?: unknown | null;

  after_state?: unknown | null;

  ip_address?: string | null;

  user_agent?: string | null;

  created_at?: Date;
}
