// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.audience_type */
enum AudienceType {
  ALL = 'ALL',
  STUDENTS = 'STUDENTS',
  STAFF = 'STAFF',
  PARENTS = 'PARENTS',
};

export default AudienceType;
