// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.audit_action */
enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  EXPORT = 'EXPORT',
  PAYMENT = 'PAYMENT',
  ROLE_CHANGE = 'ROLE_CHANGE',
  READ = 'READ',
};

export default AuditAction;
