// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.blood_group */
enum BloodGroup {
  'A+' = 'A+',
  'A-' = 'A-',
  'B+' = 'B+',
  'B-' = 'B-',
  'AB+' = 'AB+',
  'AB-' = 'AB-',
  'O+' = 'O+',
  'O-' = 'O-',
};

export default BloodGroup;
