// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { StudentsId } from './Students';
import type { FeePlansId } from './FeePlans';
import type { default as ConcessionType } from './ConcessionType';

/** Identifier type for public.concessions */
export type ConcessionsId = string & { __brand: 'public.concessions' };

/** Represents the table public.concessions */
export default interface Concessions {
  id: ConcessionsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  fee_plan_id: FeePlansId;

  type: ConcessionType;

  value: string;

  reason: string | null;

  approved_by: TenantsId | null;

  is_active: boolean;

  start_date: Date;

  end_date: Date | null;

  created_at: Date;
}

/** Represents the initializer for the table public.concessions */
export interface ConcessionsInitializer {
  /** Default value: gen_random_uuid() */
  id?: ConcessionsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  fee_plan_id: FeePlansId;

  type: ConcessionType;

  value: string;

  reason?: string | null;

  approved_by?: TenantsId | null;

  /** Default value: true */
  is_active?: boolean;

  start_date: Date;

  end_date?: Date | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.concessions */
export interface ConcessionsMutator {
  id?: ConcessionsId;

  tenant_id?: TenantsId;

  student_id?: StudentsId;

  fee_plan_id?: FeePlansId;

  type?: ConcessionType;

  value?: string;

  reason?: string | null;

  approved_by?: TenantsId | null;

  is_active?: boolean;

  start_date?: Date;

  end_date?: Date | null;

  created_at?: Date;
}
