// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { UsersId } from './Users';
import type { default as ConsentChannel } from './ConsentChannel';

/** Identifier type for public.consents */
export type ConsentsId = string & { __brand: 'public.consents' };

/** Represents the table public.consents */
export default interface Consents {
  id: ConsentsId;

  tenant_id: TenantsId;

  user_id: UsersId;

  channel: ConsentChannel;

  is_opted_in: boolean;

  opt_in_at: Date | null;

  opt_out_at: Date | null;

  ip_address: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.consents */
export interface ConsentsInitializer {
  /** Default value: gen_random_uuid() */
  id?: ConsentsId;

  tenant_id: TenantsId;

  user_id: UsersId;

  channel: ConsentChannel;

  /** Default value: true */
  is_opted_in?: boolean;

  opt_in_at?: Date | null;

  opt_out_at?: Date | null;

  ip_address?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.consents */
export interface ConsentsMutator {
  id?: ConsentsId;

  tenant_id?: TenantsId;

  user_id?: UsersId;

  channel?: ConsentChannel;

  is_opted_in?: boolean;

  opt_in_at?: Date | null;

  opt_out_at?: Date | null;

  ip_address?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
