// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { ConsentFormsId } from './ConsentForms';
import type { StudentsId } from './Students';
import type { default as ConsentResponse } from './ConsentResponse';

/** Identifier type for public.consent_responses */
export type ConsentResponsesId = string & { __brand: 'public.consent_responses' };

/** Represents the table public.consent_responses */
export default interface ConsentResponses {
  id: ConsentResponsesId;

  tenant_id: TenantsId;

  form_id: ConsentFormsId;

  student_id: StudentsId;

  respondent_name: string | null;

  response: ConsentResponse;

  responded_at: Date;

  notes: string | null;
}

/** Represents the initializer for the table public.consent_responses */
export interface ConsentResponsesInitializer {
  /** Default value: gen_random_uuid() */
  id?: ConsentResponsesId;

  tenant_id: TenantsId;

  form_id: ConsentFormsId;

  student_id: StudentsId;

  respondent_name?: string | null;

  response: ConsentResponse;

  /** Default value: now() */
  responded_at?: Date;

  notes?: string | null;
}

/** Represents the mutator for the table public.consent_responses */
export interface ConsentResponsesMutator {
  id?: ConsentResponsesId;

  tenant_id?: TenantsId;

  form_id?: ConsentFormsId;

  student_id?: StudentsId;

  respondent_name?: string | null;

  response?: ConsentResponse;

  responded_at?: Date;

  notes?: string | null;
}
