// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { StaffDepartmentsId } from './StaffDepartments';

/** Identifier type for public.designations */
export type DesignationsId = string & { __brand: 'public.designations' };

/** Represents the table public.designations */
export default interface Designations {
  id: DesignationsId;

  tenant_id: TenantsId;

  name: string;

  grade: string | null;

  department_id: StaffDepartmentsId | null;

  display_order: number;

  created_at: Date;
}

/** Represents the initializer for the table public.designations */
export interface DesignationsInitializer {
  /** Default value: gen_random_uuid() */
  id?: DesignationsId;

  tenant_id: TenantsId;

  name: string;

  grade?: string | null;

  department_id?: StaffDepartmentsId | null;

  /** Default value: 0 */
  display_order?: number;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.designations */
export interface DesignationsMutator {
  id?: DesignationsId;

  tenant_id?: TenantsId;

  name?: string;

  grade?: string | null;

  department_id?: StaffDepartmentsId | null;

  display_order?: number;

  created_at?: Date;
}
