// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { VehiclesId } from './Vehicles';

/** Identifier type for public.driver_background_checks */
export type DriverBackgroundChecksId = string & { __brand: 'public.driver_background_checks' };

/** Represents the table public.driver_background_checks */
export default interface DriverBackgroundChecks {
  id: DriverBackgroundChecksId;

  tenant_id: TenantsId;

  vehicle_id: VehiclesId | null;

  driver_name: string;

  license_number: string;

  check_date: Date;

  agency_name: string | null;

  status: string;

  clearance_expiry: Date | null;

  notes: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.driver_background_checks */
export interface DriverBackgroundChecksInitializer {
  /** Default value: gen_random_uuid() */
  id?: DriverBackgroundChecksId;

  tenant_id: TenantsId;

  vehicle_id?: VehiclesId | null;

  driver_name: string;

  license_number: string;

  /** Default value: now() */
  check_date?: Date;

  agency_name?: string | null;

  status: string;

  clearance_expiry?: Date | null;

  notes?: string | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.driver_background_checks */
export interface DriverBackgroundChecksMutator {
  id?: DriverBackgroundChecksId;

  tenant_id?: TenantsId;

  vehicle_id?: VehiclesId | null;

  driver_name?: string;

  license_number?: string;

  check_date?: Date;

  agency_name?: string | null;

  status?: string;

  clearance_expiry?: Date | null;

  notes?: string | null;

  created_at?: Date;
}
