// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.fee_frequency */
enum FeeFrequency {
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  TERM_WISE = 'TERM_WISE',
  ANNUAL = 'ANNUAL',
  ONE_TIME = 'ONE_TIME',
};

export default FeeFrequency;
