// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { FeePlansId } from './FeePlans';

/** Identifier type for public.fine_rules */
export type FineRulesId = string & { __brand: 'public.fine_rules' };

/** Represents the table public.fine_rules */
export default interface FineRules {
  id: FineRulesId;

  tenant_id: TenantsId;

  fee_plan_id: FeePlansId;

  name: string;

  days_after_due: number;

  fine_amount: string;

  is_percentage: boolean;

  max_fine: string | null;

  is_active: boolean;

  created_at: Date;
}

/** Represents the initializer for the table public.fine_rules */
export interface FineRulesInitializer {
  /** Default value: gen_random_uuid() */
  id?: FineRulesId;

  tenant_id: TenantsId;

  fee_plan_id: FeePlansId;

  name: string;

  days_after_due: number;

  fine_amount: string;

  /** Default value: false */
  is_percentage?: boolean;

  max_fine?: string | null;

  /** Default value: true */
  is_active?: boolean;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.fine_rules */
export interface FineRulesMutator {
  id?: FineRulesId;

  tenant_id?: TenantsId;

  fee_plan_id?: FeePlansId;

  name?: string;

  days_after_due?: number;

  fine_amount?: string;

  is_percentage?: boolean;

  max_fine?: string | null;

  is_active?: boolean;

  created_at?: Date;
}
