// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { GradesId } from './Grades';
import type { SubjectsId } from './Subjects';

/** Identifier type for public.grade_subjects */
export type GradeSubjectsId = string & { __brand: 'public.grade_subjects' };

/** Represents the table public.grade_subjects */
export default interface GradeSubjects {
  id: GradeSubjectsId;

  grade_id: GradesId;

  subject_id: SubjectsId;

  periods_per_week: number | null;
}

/** Represents the initializer for the table public.grade_subjects */
export interface GradeSubjectsInitializer {
  /** Default value: gen_random_uuid() */
  id?: GradeSubjectsId;

  grade_id: GradesId;

  subject_id: SubjectsId;

  /** Default value: 5 */
  periods_per_week?: number | null;
}

/** Represents the mutator for the table public.grade_subjects */
export interface GradeSubjectsMutator {
  id?: GradeSubjectsId;

  grade_id?: GradesId;

  subject_id?: SubjectsId;

  periods_per_week?: number | null;
}
