// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.guardian_relation */
enum GuardianRelation {
  FATHER = 'FATHER',
  MOTHER = 'MOTHER',
  GUARDIAN = 'GUARDIAN',
  OTHER = 'OTHER',
};

export default GuardianRelation;
