// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { StudentsId } from './Students';
import type { default as HealthIncidentType } from './HealthIncidentType';
import type { UsersId } from './Users';

/** Identifier type for public.health_incidents */
export type HealthIncidentsId = string & { __brand: 'public.health_incidents' };

/** Represents the table public.health_incidents */
export default interface HealthIncidents {
  id: HealthIncidentsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  incident_date: Date;

  type: HealthIncidentType;

  description: string;

  action_taken: string | null;

  reported_by: UsersId | null;

  parent_notified: boolean;

  parent_notified_at: Date | null;

  follow_up_required: boolean;

  follow_up_notes: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.health_incidents */
export interface HealthIncidentsInitializer {
  /** Default value: gen_random_uuid() */
  id?: HealthIncidentsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  /** Default value: now() */
  incident_date?: Date;

  type: HealthIncidentType;

  description: string;

  action_taken?: string | null;

  reported_by?: UsersId | null;

  /** Default value: false */
  parent_notified?: boolean;

  parent_notified_at?: Date | null;

  /** Default value: false */
  follow_up_required?: boolean;

  follow_up_notes?: string | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.health_incidents */
export interface HealthIncidentsMutator {
  id?: HealthIncidentsId;

  tenant_id?: TenantsId;

  student_id?: StudentsId;

  incident_date?: Date;

  type?: HealthIncidentType;

  description?: string;

  action_taken?: string | null;

  reported_by?: UsersId | null;

  parent_notified?: boolean;

  parent_notified_at?: Date | null;

  follow_up_required?: boolean;

  follow_up_notes?: string | null;

  created_at?: Date;
}
