// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { SubjectsId } from './Subjects';
import type { GradesId } from './Grades';
import type { SectionsId } from './Sections';
import type { UsersId } from './Users';

/** Identifier type for public.homework_assignments */
export type HomeworkAssignmentsId = string & { __brand: 'public.homework_assignments' };

/** Represents the table public.homework_assignments */
export default interface HomeworkAssignments {
  id: HomeworkAssignmentsId;

  tenant_id: TenantsId;

  subject_id: SubjectsId | null;

  grade_id: GradesId | null;

  section_id: SectionsId | null;

  title: string;

  description: string | null;

  due_date: Date;

  assigned_by: UsersId | null;

  attachments: unknown | null;

  max_marks: number | null;

  created_at: Date;
}

/** Represents the initializer for the table public.homework_assignments */
export interface HomeworkAssignmentsInitializer {
  /** Default value: gen_random_uuid() */
  id?: HomeworkAssignmentsId;

  tenant_id: TenantsId;

  subject_id?: SubjectsId | null;

  grade_id?: GradesId | null;

  section_id?: SectionsId | null;

  title: string;

  description?: string | null;

  due_date: Date;

  assigned_by?: UsersId | null;

  /** Default value: '[]'::jsonb */
  attachments?: unknown | null;

  max_marks?: number | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.homework_assignments */
export interface HomeworkAssignmentsMutator {
  id?: HomeworkAssignmentsId;

  tenant_id?: TenantsId;

  subject_id?: SubjectsId | null;

  grade_id?: GradesId | null;

  section_id?: SectionsId | null;

  title?: string;

  description?: string | null;

  due_date?: Date;

  assigned_by?: UsersId | null;

  attachments?: unknown | null;

  max_marks?: number | null;

  created_at?: Date;
}
