// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';

/** Identifier type for public.host_families */
export type HostFamiliesId = string & { __brand: 'public.host_families' };

/** Represents the table public.host_families */
export default interface HostFamilies {
  id: HostFamiliesId;

  tenant_id: TenantsId;

  family_name: string;

  address: string;

  phone: string;

  background_checked: Date | null;
}

/** Represents the initializer for the table public.host_families */
export interface HostFamiliesInitializer {
  /** Default value: gen_random_uuid() */
  id?: HostFamiliesId;

  tenant_id: TenantsId;

  family_name: string;

  address: string;

  phone: string;

  background_checked?: Date | null;
}

/** Represents the mutator for the table public.host_families */
export interface HostFamiliesMutator {
  id?: HostFamiliesId;

  tenant_id?: TenantsId;

  family_name?: string;

  address?: string;

  phone?: string;

  background_checked?: Date | null;
}
