// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { StudentsId } from './Students';
import type { HostelsId } from './Hostels';
import type { HostelRoomsId } from './HostelRooms';
import type { default as AllocationStatus } from './AllocationStatus';

/** Identifier type for public.hostel_allocations */
export type HostelAllocationsId = string & { __brand: 'public.hostel_allocations' };

/** Represents the table public.hostel_allocations */
export default interface HostelAllocations {
  id: HostelAllocationsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  hostel_id: HostelsId;

  room_id: HostelRoomsId;

  bed_number: string;

  allocated_from: Date;

  allocated_to: Date;

  status: AllocationStatus;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.hostel_allocations */
export interface HostelAllocationsInitializer {
  /** Default value: gen_random_uuid() */
  id?: HostelAllocationsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  hostel_id: HostelsId;

  room_id: HostelRoomsId;

  bed_number: string;

  allocated_from: Date;

  allocated_to: Date;

  /** Default value: 'ACTIVE'::allocation_status */
  status?: AllocationStatus;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.hostel_allocations */
export interface HostelAllocationsMutator {
  id?: HostelAllocationsId;

  tenant_id?: TenantsId;

  student_id?: StudentsId;

  hostel_id?: HostelsId;

  room_id?: HostelRoomsId;

  bed_number?: string;

  allocated_from?: Date;

  allocated_to?: Date;

  status?: AllocationStatus;

  created_at?: Date;

  updated_at?: Date;
}
