// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { HostelsId } from './Hostels';
import type { default as RoomType } from './RoomType';
import type { default as RoomStatus } from './RoomStatus';

/** Identifier type for public.hostel_rooms */
export type HostelRoomsId = string & { __brand: 'public.hostel_rooms' };

/** Represents the table public.hostel_rooms */
export default interface HostelRooms {
  id: HostelRoomsId;

  tenant_id: TenantsId;

  hostel_id: HostelsId;

  room_number: string;

  floor: number;

  type: RoomType;

  total_beds: number;

  occupied_beds: number;

  amenities: unknown | null;

  status: RoomStatus;

  created_at: Date;
}

/** Represents the initializer for the table public.hostel_rooms */
export interface HostelRoomsInitializer {
  /** Default value: gen_random_uuid() */
  id?: HostelRoomsId;

  tenant_id: TenantsId;

  hostel_id: HostelsId;

  room_number: string;

  /** Default value: 0 */
  floor?: number;

  type: RoomType;

  total_beds: number;

  /** Default value: 0 */
  occupied_beds?: number;

  /** Default value: '[]'::jsonb */
  amenities?: unknown | null;

  /** Default value: 'AVAILABLE'::room_status */
  status?: RoomStatus;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.hostel_rooms */
export interface HostelRoomsMutator {
  id?: HostelRoomsId;

  tenant_id?: TenantsId;

  hostel_id?: HostelsId;

  room_number?: string;

  floor?: number;

  type?: RoomType;

  total_beds?: number;

  occupied_beds?: number;

  amenities?: unknown | null;

  status?: RoomStatus;

  created_at?: Date;
}
