// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { default as IdCardStatus } from './IdCardStatus';

/** Identifier type for public.id_cards */
export type IdCardsId = string & { __brand: 'public.id_cards' };

/** Represents the table public.id_cards */
export default interface IdCards {
  id: IdCardsId;

  tenant_id: TenantsId;

  person_id: string;

  person_type: string;

  valid_from: Date;

  valid_to: Date;

  qr_code: string | null;

  template_name: string | null;

  status: IdCardStatus;

  printed_at: Date | null;

  issued_at: Date | null;

  created_at: Date;
}

/** Represents the initializer for the table public.id_cards */
export interface IdCardsInitializer {
  /** Default value: gen_random_uuid() */
  id?: IdCardsId;

  tenant_id: TenantsId;

  person_id: string;

  person_type: string;

  valid_from: Date;

  valid_to: Date;

  qr_code?: string | null;

  template_name?: string | null;

  /** Default value: 'PENDING'::id_card_status */
  status?: IdCardStatus;

  printed_at?: Date | null;

  issued_at?: Date | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.id_cards */
export interface IdCardsMutator {
  id?: IdCardsId;

  tenant_id?: TenantsId;

  person_id?: string;

  person_type?: string;

  valid_from?: Date;

  valid_to?: Date;

  qr_code?: string | null;

  template_name?: string | null;

  status?: IdCardStatus;

  printed_at?: Date | null;

  issued_at?: Date | null;

  created_at?: Date;
}
