// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { StudentsId } from './Students';

/** Identifier type for public.immunizations */
export type ImmunizationsId = string & { __brand: 'public.immunizations' };

/** Represents the table public.immunizations */
export default interface Immunizations {
  id: ImmunizationsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  vaccine_name: string;

  dose_number: number;

  date_given: Date;

  next_due_date: Date | null;

  administered_by: string | null;

  batch_number: string | null;

  notes: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.immunizations */
export interface ImmunizationsInitializer {
  /** Default value: gen_random_uuid() */
  id?: ImmunizationsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  vaccine_name: string;

  /** Default value: 1 */
  dose_number?: number;

  date_given: Date;

  next_due_date?: Date | null;

  administered_by?: string | null;

  batch_number?: string | null;

  notes?: string | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.immunizations */
export interface ImmunizationsMutator {
  id?: ImmunizationsId;

  tenant_id?: TenantsId;

  student_id?: StudentsId;

  vaccine_name?: string;

  dose_number?: number;

  date_given?: Date;

  next_due_date?: Date | null;

  administered_by?: string | null;

  batch_number?: string | null;

  notes?: string | null;

  created_at?: Date;
}
