// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.institution_type */
enum InstitutionType {
  K12 = 'K12',
  COLLEGE = 'COLLEGE',
  UNIVERSITY = 'UNIVERSITY',
  COACHING = 'COACHING',
  HYBRID = 'HYBRID',
};

export default InstitutionType;
