// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { StudentsId } from './Students';
import type { HostFamiliesId } from './HostFamilies';

/** Identifier type for public.international_placements */
export type InternationalPlacementsId = string & { __brand: 'public.international_placements' };

/** Represents the table public.international_placements */
export default interface InternationalPlacements {
  id: InternationalPlacementsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  host_family_id: HostFamiliesId | null;

  placement_year: string;
}

/** Represents the initializer for the table public.international_placements */
export interface InternationalPlacementsInitializer {
  /** Default value: gen_random_uuid() */
  id?: InternationalPlacementsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  host_family_id?: HostFamiliesId | null;

  placement_year: string;
}

/** Represents the mutator for the table public.international_placements */
export interface InternationalPlacementsMutator {
  id?: InternationalPlacementsId;

  tenant_id?: TenantsId;

  student_id?: StudentsId;

  host_family_id?: HostFamiliesId | null;

  placement_year?: string;
}
