// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.lead_source */
enum LeadSource {
  WEBSITE = 'WEBSITE',
  REFERRAL = 'REFERRAL',
  WALK_IN = 'WALK_IN',
  ADVERTISEMENT = 'ADVERTISEMENT',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  OTHER = 'OTHER',
};

export default LeadSource;
