// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.leave_status */
enum LeaveStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
};

export default LeaveStatus;
