// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { default as LeaveType } from './LeaveType';

/** Identifier type for public.leave_policies */
export type LeavePoliciesId = string & { __brand: 'public.leave_policies' };

/** Represents the table public.leave_policies */
export default interface LeavePolicies {
  id: LeavePoliciesId;

  tenant_id: TenantsId;

  name: string;

  leave_type: LeaveType;

  max_days_per_year: number;

  carry_forward_max: number;

  min_service_days: number | null;

  is_half_day_allowed: boolean;

  is_paid_leave: boolean;

  description: string | null;

  is_active: boolean;

  created_at: Date;
}

/** Represents the initializer for the table public.leave_policies */
export interface LeavePoliciesInitializer {
  /** Default value: gen_random_uuid() */
  id?: LeavePoliciesId;

  tenant_id: TenantsId;

  name: string;

  leave_type: LeaveType;

  max_days_per_year: number;

  /** Default value: 0 */
  carry_forward_max?: number;

  /** Default value: 0 */
  min_service_days?: number | null;

  /** Default value: true */
  is_half_day_allowed?: boolean;

  /** Default value: true */
  is_paid_leave?: boolean;

  description?: string | null;

  /** Default value: true */
  is_active?: boolean;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.leave_policies */
export interface LeavePoliciesMutator {
  id?: LeavePoliciesId;

  tenant_id?: TenantsId;

  name?: string;

  leave_type?: LeaveType;

  max_days_per_year?: number;

  carry_forward_max?: number;

  min_service_days?: number | null;

  is_half_day_allowed?: boolean;

  is_paid_leave?: boolean;

  description?: string | null;

  is_active?: boolean;

  created_at?: Date;
}
