// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.lesson_plan_status */
enum LessonPlanStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  COMPLETED = 'COMPLETED',
};

export default LessonPlanStatus;
