// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { default as MessageChannel } from './MessageChannel';
import type { UsersId } from './Users';
import type { default as MessageStatus } from './MessageStatus';

/** Identifier type for public.messages */
export type MessagesId = string & { __brand: 'public.messages' };

/** Represents the table public.messages */
export default interface Messages {
  id: MessagesId;

  tenant_id: TenantsId;

  channel: MessageChannel;

  recipient_id: UsersId | null;

  recipient_phone: string | null;

  recipient_email: string | null;

  subject: string | null;

  body: string;

  template_id: string | null;

  status: MessageStatus;

  provider_message_id: string | null;

  error_message: string | null;

  metadata: unknown | null;

  sent_by: UsersId | null;

  sent_at: Date | null;

  delivered_at: Date | null;

  created_at: Date;
}

/** Represents the initializer for the table public.messages */
export interface MessagesInitializer {
  /** Default value: gen_random_uuid() */
  id?: MessagesId;

  tenant_id: TenantsId;

  channel: MessageChannel;

  recipient_id?: UsersId | null;

  recipient_phone?: string | null;

  recipient_email?: string | null;

  subject?: string | null;

  body: string;

  template_id?: string | null;

  /** Default value: 'QUEUED'::message_status */
  status?: MessageStatus;

  provider_message_id?: string | null;

  error_message?: string | null;

  metadata?: unknown | null;

  sent_by?: UsersId | null;

  sent_at?: Date | null;

  delivered_at?: Date | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.messages */
export interface MessagesMutator {
  id?: MessagesId;

  tenant_id?: TenantsId;

  channel?: MessageChannel;

  recipient_id?: UsersId | null;

  recipient_phone?: string | null;

  recipient_email?: string | null;

  subject?: string | null;

  body?: string;

  template_id?: string | null;

  status?: MessageStatus;

  provider_message_id?: string | null;

  error_message?: string | null;

  metadata?: unknown | null;

  sent_by?: UsersId | null;

  sent_at?: Date | null;

  delivered_at?: Date | null;

  created_at?: Date;
}
