// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.message_status */
enum MessageStatus {
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  READ = 'READ',
};

export default MessageStatus;
