// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { StudentsId } from './Students';
import type { UsersId } from './Users';

/** Identifier type for public.nurse_visit_logs */
export type NurseVisitLogsId = string & { __brand: 'public.nurse_visit_logs' };

/** Represents the table public.nurse_visit_logs */
export default interface NurseVisitLogs {
  id: NurseVisitLogsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  visit_date: Date;

  symptoms: string;

  treatment_provided: string;

  temperature: string | null;

  blood_pressure: string | null;

  sent_home: boolean;

  nurse_id: UsersId;

  created_at: Date;
}

/** Represents the initializer for the table public.nurse_visit_logs */
export interface NurseVisitLogsInitializer {
  /** Default value: gen_random_uuid() */
  id?: NurseVisitLogsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  /** Default value: now() */
  visit_date?: Date;

  symptoms: string;

  treatment_provided: string;

  temperature?: string | null;

  blood_pressure?: string | null;

  /** Default value: false */
  sent_home?: boolean;

  nurse_id: UsersId;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.nurse_visit_logs */
export interface NurseVisitLogsMutator {
  id?: NurseVisitLogsId;

  tenant_id?: TenantsId;

  student_id?: StudentsId;

  visit_date?: Date;

  symptoms?: string;

  treatment_provided?: string;

  temperature?: string | null;

  blood_pressure?: string | null;

  sent_home?: boolean;

  nurse_id?: UsersId;

  created_at?: Date;
}
