// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.payment_method */
enum PaymentMethod {
  CASH = 'CASH',
  UPI = 'UPI',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CHEQUE = 'CHEQUE',
  CARD = 'CARD',
  ONLINE = 'ONLINE',
};

export default PaymentMethod;
