// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.platform_broadcasts */
export type PlatformBroadcastsId = string & { __brand: 'public.platform_broadcasts' };

/** Represents the table public.platform_broadcasts */
export default interface PlatformBroadcasts {
  id: PlatformBroadcastsId;

  title: string;

  message: string;

  target_tiers: string[] | null;

  target_modules: string[] | null;

  is_active: boolean;

  type: string;

  expires_at: Date | null;

  created_at: Date;

  created_by: UsersId | null;
}

/** Represents the initializer for the table public.platform_broadcasts */
export interface PlatformBroadcastsInitializer {
  /** Default value: gen_random_uuid() */
  id?: PlatformBroadcastsId;

  title: string;

  message: string;

  target_tiers?: string[] | null;

  target_modules?: string[] | null;

  /** Default value: true */
  is_active?: boolean;

  /** Default value: 'INFO'::character varying */
  type?: string;

  expires_at?: Date | null;

  /** Default value: now() */
  created_at?: Date;

  created_by?: UsersId | null;
}

/** Represents the mutator for the table public.platform_broadcasts */
export interface PlatformBroadcastsMutator {
  id?: PlatformBroadcastsId;

  title?: string;

  message?: string;

  target_tiers?: string[] | null;

  target_modules?: string[] | null;

  is_active?: boolean;

  type?: string;

  expires_at?: Date | null;

  created_at?: Date;

  created_by?: UsersId | null;
}
