// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.quiz_status */
enum QuizStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  CLOSED = 'CLOSED',
};

export default QuizStatus;
