// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { PaymentsId } from './Payments';

/** Identifier type for public.receipts */
export type ReceiptsId = string & { __brand: 'public.receipts' };

/** Represents the table public.receipts */
export default interface Receipts {
  id: ReceiptsId;

  tenant_id: TenantsId;

  payment_id: PaymentsId;

  receipt_number: string;

  pdf_url: string | null;

  issued_at: Date;

  created_at: Date;
}

/** Represents the initializer for the table public.receipts */
export interface ReceiptsInitializer {
  /** Default value: gen_random_uuid() */
  id?: ReceiptsId;

  tenant_id: TenantsId;

  payment_id: PaymentsId;

  receipt_number: string;

  pdf_url?: string | null;

  /** Default value: now() */
  issued_at?: Date;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.receipts */
export interface ReceiptsMutator {
  id?: ReceiptsId;

  tenant_id?: TenantsId;

  payment_id?: PaymentsId;

  receipt_number?: string;

  pdf_url?: string | null;

  issued_at?: Date;

  created_at?: Date;
}
