// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.reservation_status */
enum ReservationStatus {
  ACTIVE = 'ACTIVE',
  FULFILLED = 'FULFILLED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
};

export default ReservationStatus;
