// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.room_type */
enum RoomType {
  SINGLE = 'SINGLE',
  DOUBLE = 'DOUBLE',
  TRIPLE = 'TRIPLE',
  DORMITORY = 'DORMITORY',
};

export default RoomType;
