// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { UsersId } from './Users';

/** Identifier type for public.staff_departments */
export type StaffDepartmentsId = string & { __brand: 'public.staff_departments' };

/** Represents the table public.staff_departments */
export default interface StaffDepartments {
  id: StaffDepartmentsId;

  tenant_id: TenantsId;

  name: string;

  code: string;

  head_of_dept_id: UsersId | null;

  description: string | null;

  is_active: boolean;

  created_at: Date;
}

/** Represents the initializer for the table public.staff_departments */
export interface StaffDepartmentsInitializer {
  /** Default value: gen_random_uuid() */
  id?: StaffDepartmentsId;

  tenant_id: TenantsId;

  name: string;

  code: string;

  head_of_dept_id?: UsersId | null;

  description?: string | null;

  /** Default value: true */
  is_active?: boolean;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.staff_departments */
export interface StaffDepartmentsMutator {
  id?: StaffDepartmentsId;

  tenant_id?: TenantsId;

  name?: string;

  code?: string;

  head_of_dept_id?: UsersId | null;

  description?: string | null;

  is_active?: boolean;

  created_at?: Date;
}
