// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.staff_status */
enum StaffStatus {
  ACTIVE = 'ACTIVE',
  ON_LEAVE = 'ON_LEAVE',
  RESIGNED = 'RESIGNED',
  TERMINATED = 'TERMINATED',
  PROBATION = 'PROBATION',
};

export default StaffStatus;
