// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { UsersId } from './Users';
import type { StaffDepartmentsId } from './StaffDepartments';
import type { DesignationsId } from './Designations';
import type { default as EmploymentType } from './EmploymentType';
import type { default as StaffStatus } from './StaffStatus';

/** Identifier type for public.staff_profiles */
export type StaffProfilesId = string & { __brand: 'public.staff_profiles' };

/** Represents the table public.staff_profiles */
export default interface StaffProfiles {
  id: StaffProfilesId;

  tenant_id: TenantsId;

  user_id: UsersId;

  employee_id: string;

  department_id: StaffDepartmentsId | null;

  designation_id: DesignationsId | null;

  employment_type: EmploymentType;

  status: StaffStatus;

  joining_date: Date;

  confirmation_date: Date | null;

  resignation_date: Date | null;

  date_of_birth: Date | null;

  qualification: string | null;

  experience_years: number | null;

  specialization: string | null;

  salary_basic: string | null;

  salary_hra: string | null;

  salary_da: string | null;

  salary_pf: string | null;

  salary_tax: string | null;

  salary_gross: string | null;

  salary_net: string | null;

  pan_number: string | null;

  aadhaar_number: string | null;

  bank_account: string | null;

  bank_name: string | null;

  bank_ifsc: string | null;

  address: string | null;

  emergency_contact: string | null;

  emergency_contact_name: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.staff_profiles */
export interface StaffProfilesInitializer {
  /** Default value: gen_random_uuid() */
  id?: StaffProfilesId;

  tenant_id: TenantsId;

  user_id: UsersId;

  employee_id: string;

  department_id?: StaffDepartmentsId | null;

  designation_id?: DesignationsId | null;

  /** Default value: 'FULL_TIME'::employment_type */
  employment_type?: EmploymentType;

  /** Default value: 'ACTIVE'::staff_status */
  status?: StaffStatus;

  joining_date: Date;

  confirmation_date?: Date | null;

  resignation_date?: Date | null;

  date_of_birth?: Date | null;

  qualification?: string | null;

  /** Default value: 0 */
  experience_years?: number | null;

  specialization?: string | null;

  /** Default value: '0'::numeric */
  salary_basic?: string | null;

  /** Default value: '0'::numeric */
  salary_hra?: string | null;

  /** Default value: '0'::numeric */
  salary_da?: string | null;

  /** Default value: '0'::numeric */
  salary_pf?: string | null;

  /** Default value: '0'::numeric */
  salary_tax?: string | null;

  /** Default value: '0'::numeric */
  salary_gross?: string | null;

  /** Default value: '0'::numeric */
  salary_net?: string | null;

  pan_number?: string | null;

  aadhaar_number?: string | null;

  bank_account?: string | null;

  bank_name?: string | null;

  bank_ifsc?: string | null;

  address?: string | null;

  emergency_contact?: string | null;

  emergency_contact_name?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.staff_profiles */
export interface StaffProfilesMutator {
  id?: StaffProfilesId;

  tenant_id?: TenantsId;

  user_id?: UsersId;

  employee_id?: string;

  department_id?: StaffDepartmentsId | null;

  designation_id?: DesignationsId | null;

  employment_type?: EmploymentType;

  status?: StaffStatus;

  joining_date?: Date;

  confirmation_date?: Date | null;

  resignation_date?: Date | null;

  date_of_birth?: Date | null;

  qualification?: string | null;

  experience_years?: number | null;

  specialization?: string | null;

  salary_basic?: string | null;

  salary_hra?: string | null;

  salary_da?: string | null;

  salary_pf?: string | null;

  salary_tax?: string | null;

  salary_gross?: string | null;

  salary_net?: string | null;

  pan_number?: string | null;

  aadhaar_number?: string | null;

  bank_account?: string | null;

  bank_name?: string | null;

  bank_ifsc?: string | null;

  address?: string | null;

  emergency_contact?: string | null;

  emergency_contact_name?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
