// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.student_status */
enum StudentStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ALUMNI = 'ALUMNI',
  TRANSFERRED = 'TRANSFERRED',
  SUSPENDED = 'SUSPENDED',
};

export default StudentStatus;
