// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { StudentsId } from './Students';
import type { UsersId } from './Users';

/** Identifier type for public.student_documents */
export type StudentDocumentsId = string & { __brand: 'public.student_documents' };

/** Represents the table public.student_documents */
export default interface StudentDocuments {
  id: StudentDocumentsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  document_type: string;

  file_name: string;

  file_url: string | null;

  file_size: number | null;

  mime_type: string | null;

  uploaded_by: UsersId | null;

  is_verified: boolean;

  verified_by: UsersId | null;

  verified_at: Date | null;

  notes: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.student_documents */
export interface StudentDocumentsInitializer {
  /** Default value: gen_random_uuid() */
  id?: StudentDocumentsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  document_type: string;

  file_name: string;

  file_url?: string | null;

  file_size?: number | null;

  mime_type?: string | null;

  uploaded_by?: UsersId | null;

  /** Default value: false */
  is_verified?: boolean;

  verified_by?: UsersId | null;

  verified_at?: Date | null;

  notes?: string | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.student_documents */
export interface StudentDocumentsMutator {
  id?: StudentDocumentsId;

  tenant_id?: TenantsId;

  student_id?: StudentsId;

  document_type?: string;

  file_name?: string;

  file_url?: string | null;

  file_size?: number | null;

  mime_type?: string | null;

  uploaded_by?: UsersId | null;

  is_verified?: boolean;

  verified_by?: UsersId | null;

  verified_at?: Date | null;

  notes?: string | null;

  created_at?: Date;
}
