// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { StudentsId } from './Students';
import type { RoutesId } from './Routes';
import type { StopsId } from './Stops';

/** Identifier type for public.student_transport */
export type StudentTransportId = string & { __brand: 'public.student_transport' };

/** Represents the table public.student_transport */
export default interface StudentTransport {
  id: StudentTransportId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  route_id: RoutesId;

  stop_id: StopsId;

  start_date: string;

  end_date: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.student_transport */
export interface StudentTransportInitializer {
  /** Default value: gen_random_uuid() */
  id?: StudentTransportId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  route_id: RoutesId;

  stop_id: StopsId;

  start_date: string;

  end_date?: string | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.student_transport */
export interface StudentTransportMutator {
  id?: StudentTransportId;

  tenant_id?: TenantsId;

  student_id?: StudentsId;

  route_id?: RoutesId;

  stop_id?: StopsId;

  start_date?: string;

  end_date?: string | null;

  created_at?: Date;
}
