// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { StudentsId } from './Students';

/** Identifier type for public.student_visas */
export type StudentVisasId = string & { __brand: 'public.student_visas' };

/** Represents the table public.student_visas */
export default interface StudentVisas {
  id: StudentVisasId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  visa_type: string;

  country_of_origin: string;

  passport_number: string;

  issue_date: Date;

  expiration_date: Date;

  created_at: Date;
}

/** Represents the initializer for the table public.student_visas */
export interface StudentVisasInitializer {
  /** Default value: gen_random_uuid() */
  id?: StudentVisasId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  visa_type: string;

  country_of_origin: string;

  passport_number: string;

  issue_date: Date;

  expiration_date: Date;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.student_visas */
export interface StudentVisasMutator {
  id?: StudentVisasId;

  tenant_id?: TenantsId;

  student_id?: StudentsId;

  visa_type?: string;

  country_of_origin?: string;

  passport_number?: string;

  issue_date?: Date;

  expiration_date?: Date;

  created_at?: Date;
}
