// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { ExamSchedulesId } from './ExamSchedules';
import type { StudentsId } from './Students';
import type { UsersId } from './Users';

/** Identifier type for public.student_results */
export type StudentResultsId = string & { __brand: 'public.student_results' };

/** Represents the table public.student_results */
export default interface StudentResults {
  id: StudentResultsId;

  tenant_id: TenantsId;

  exam_schedule_id: ExamSchedulesId;

  student_id: StudentsId;

  marks_obtained: string | null;

  grade: string | null;

  remarks: string | null;

  is_absent: boolean;

  entered_by: UsersId | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.student_results */
export interface StudentResultsInitializer {
  /** Default value: gen_random_uuid() */
  id?: StudentResultsId;

  tenant_id: TenantsId;

  exam_schedule_id: ExamSchedulesId;

  student_id: StudentsId;

  marks_obtained?: string | null;

  grade?: string | null;

  remarks?: string | null;

  /** Default value: false */
  is_absent?: boolean;

  entered_by?: UsersId | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.student_results */
export interface StudentResultsMutator {
  id?: StudentResultsId;

  tenant_id?: TenantsId;

  exam_schedule_id?: ExamSchedulesId;

  student_id?: StudentsId;

  marks_obtained?: string | null;

  grade?: string | null;

  remarks?: string | null;

  is_absent?: boolean;

  entered_by?: UsersId | null;

  created_at?: Date;

  updated_at?: Date;
}
