// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';

/** Identifier type for public.subjects */
export type SubjectsId = string & { __brand: 'public.subjects' };

/** Represents the table public.subjects */
export default interface Subjects {
  id: SubjectsId;

  tenant_id: TenantsId;

  name: string;

  code: string;

  description: string | null;

  is_elective: boolean;

  created_at: Date;
}

/** Represents the initializer for the table public.subjects */
export interface SubjectsInitializer {
  /** Default value: gen_random_uuid() */
  id?: SubjectsId;

  tenant_id: TenantsId;

  name: string;

  code: string;

  description?: string | null;

  /** Default value: false */
  is_elective?: boolean;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.subjects */
export interface SubjectsMutator {
  id?: SubjectsId;

  tenant_id?: TenantsId;

  name?: string;

  code?: string;

  description?: string | null;

  is_elective?: boolean;

  created_at?: Date;
}
