// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { AcademicYearsId } from './AcademicYears';
import type { default as TermType } from './TermType';

/** Identifier type for public.terms */
export type TermsId = string & { __brand: 'public.terms' };

/** Represents the table public.terms */
export default interface Terms {
  id: TermsId;

  tenant_id: TenantsId;

  academic_year_id: AcademicYearsId;

  name: string;

  type: TermType;

  start_date: Date;

  end_date: Date;

  created_at: Date;
}

/** Represents the initializer for the table public.terms */
export interface TermsInitializer {
  /** Default value: gen_random_uuid() */
  id?: TermsId;

  tenant_id: TenantsId;

  academic_year_id: AcademicYearsId;

  name: string;

  type: TermType;

  start_date: Date;

  end_date: Date;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.terms */
export interface TermsMutator {
  id?: TermsId;

  tenant_id?: TenantsId;

  academic_year_id?: AcademicYearsId;

  name?: string;

  type?: TermType;

  start_date?: Date;

  end_date?: Date;

  created_at?: Date;
}
