// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.term_type */
enum TermType {
  TERM_1 = 'TERM_1',
  TERM_2 = 'TERM_2',
  TERM_3 = 'TERM_3',
  ANNUAL = 'ANNUAL',
};

export default TermType;
