// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { TestSeriesId } from './TestSeries';
import type { StudentsId } from './Students';

/** Identifier type for public.test_series_results */
export type TestSeriesResultsId = string & { __brand: 'public.test_series_results' };

/** Represents the table public.test_series_results */
export default interface TestSeriesResults {
  id: TestSeriesResultsId;

  tenant_id: TenantsId;

  test_id: TestSeriesId;

  student_id: StudentsId;

  marks_obtained: number;

  rank: number | null;
}

/** Represents the initializer for the table public.test_series_results */
export interface TestSeriesResultsInitializer {
  /** Default value: gen_random_uuid() */
  id?: TestSeriesResultsId;

  tenant_id: TenantsId;

  test_id: TestSeriesId;

  student_id: StudentsId;

  marks_obtained: number;

  rank?: number | null;
}

/** Represents the mutator for the table public.test_series_results */
export interface TestSeriesResultsMutator {
  id?: TestSeriesResultsId;

  tenant_id?: TenantsId;

  test_id?: TestSeriesId;

  student_id?: StudentsId;

  marks_obtained?: number;

  rank?: number | null;
}
