// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { CoachingBatchesId } from './CoachingBatches';

/** Identifier type for public.test_series */
export type TestSeriesId = string & { __brand: 'public.test_series' };

/** Represents the table public.test_series */
export default interface TestSeries {
  id: TestSeriesId;

  tenant_id: TenantsId;

  batch_id: CoachingBatchesId;

  test_name: string;

  total_marks: number;

  scheduled_at: Date;
}

/** Represents the initializer for the table public.test_series */
export interface TestSeriesInitializer {
  /** Default value: gen_random_uuid() */
  id?: TestSeriesId;

  tenant_id: TenantsId;

  batch_id: CoachingBatchesId;

  test_name: string;

  total_marks: number;

  scheduled_at: Date;
}

/** Represents the mutator for the table public.test_series */
export interface TestSeriesMutator {
  id?: TestSeriesId;

  tenant_id?: TenantsId;

  batch_id?: CoachingBatchesId;

  test_name?: string;

  total_marks?: number;

  scheduled_at?: Date;
}
