// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { SectionsId } from './Sections';
import type { PeriodsId } from './Periods';
import type { SubjectsId } from './Subjects';
import type { UsersId } from './Users';
import type { default as DayOfWeek } from './DayOfWeek';

/** Identifier type for public.timetable_entries */
export type TimetableEntriesId = string & { __brand: 'public.timetable_entries' };

/** Represents the table public.timetable_entries */
export default interface TimetableEntries {
  id: TimetableEntriesId;

  tenant_id: TenantsId;

  section_id: SectionsId;

  period_id: PeriodsId;

  subject_id: SubjectsId;

  teacher_id: UsersId;

  day_of_week: DayOfWeek;

  room_number: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.timetable_entries */
export interface TimetableEntriesInitializer {
  /** Default value: gen_random_uuid() */
  id?: TimetableEntriesId;

  tenant_id: TenantsId;

  section_id: SectionsId;

  period_id: PeriodsId;

  subject_id: SubjectsId;

  teacher_id: UsersId;

  day_of_week: DayOfWeek;

  room_number?: string | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.timetable_entries */
export interface TimetableEntriesMutator {
  id?: TimetableEntriesId;

  tenant_id?: TenantsId;

  section_id?: SectionsId;

  period_id?: PeriodsId;

  subject_id?: SubjectsId;

  teacher_id?: UsersId;

  day_of_week?: DayOfWeek;

  room_number?: string | null;

  created_at?: Date;
}
