// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { default as DegreeType } from './DegreeType';

/** Identifier type for public.university_programs */
export type UniversityProgramsId = string & { __brand: 'public.university_programs' };

/** Represents the table public.university_programs */
export default interface UniversityPrograms {
  id: UniversityProgramsId;

  tenant_id: TenantsId;

  name: string;

  degree_type: DegreeType;

  duration_years: number;

  total_credits: number;

  created_at: Date;
}

/** Represents the initializer for the table public.university_programs */
export interface UniversityProgramsInitializer {
  /** Default value: gen_random_uuid() */
  id?: UniversityProgramsId;

  tenant_id: TenantsId;

  name: string;

  degree_type: DegreeType;

  duration_years: number;

  total_credits: number;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.university_programs */
export interface UniversityProgramsMutator {
  id?: UniversityProgramsId;

  tenant_id?: TenantsId;

  name?: string;

  degree_type?: DegreeType;

  duration_years?: number;

  total_credits?: number;

  created_at?: Date;
}
