// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { UniversityProgramsId } from './UniversityPrograms';

/** Identifier type for public.university_courses */
export type UniversityCoursesId = string & { __brand: 'public.university_courses' };

/** Represents the table public.university_courses */
export default interface UniversityCourses {
  id: UniversityCoursesId;

  tenant_id: TenantsId;

  program_id: UniversityProgramsId;

  code: string;

  title: string;

  credits: number;

  created_at: Date;
}

/** Represents the initializer for the table public.university_courses */
export interface UniversityCoursesInitializer {
  /** Default value: gen_random_uuid() */
  id?: UniversityCoursesId;

  tenant_id: TenantsId;

  program_id: UniversityProgramsId;

  code: string;

  title: string;

  credits: number;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.university_courses */
export interface UniversityCoursesMutator {
  id?: UniversityCoursesId;

  tenant_id?: TenantsId;

  program_id?: UniversityProgramsId;

  code?: string;

  title?: string;

  credits?: number;

  created_at?: Date;
}
