// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { VehiclesId } from './Vehicles';

/** Identifier type for public.vehicle_maintenance_logs */
export type VehicleMaintenanceLogsId = string & { __brand: 'public.vehicle_maintenance_logs' };

/** Represents the table public.vehicle_maintenance_logs */
export default interface VehicleMaintenanceLogs {
  id: VehicleMaintenanceLogsId;

  tenant_id: TenantsId;

  vehicle_id: VehiclesId;

  service_date: Date;

  service_type: string;

  description: string;

  cost: string | null;

  performed_by: string | null;

  next_due_date: Date | null;

  created_at: Date;
}

/** Represents the initializer for the table public.vehicle_maintenance_logs */
export interface VehicleMaintenanceLogsInitializer {
  /** Default value: gen_random_uuid() */
  id?: VehicleMaintenanceLogsId;

  tenant_id: TenantsId;

  vehicle_id: VehiclesId;

  /** Default value: now() */
  service_date?: Date;

  service_type: string;

  description: string;

  cost?: string | null;

  performed_by?: string | null;

  next_due_date?: Date | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.vehicle_maintenance_logs */
export interface VehicleMaintenanceLogsMutator {
  id?: VehicleMaintenanceLogsId;

  tenant_id?: TenantsId;

  vehicle_id?: VehiclesId;

  service_date?: Date;

  service_type?: string;

  description?: string;

  cost?: string | null;

  performed_by?: string | null;

  next_due_date?: Date | null;

  created_at?: Date;
}
