// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.visit_purpose */
enum VisitPurpose {
  MEETING = 'MEETING',
  ADMISSION = 'ADMISSION',
  DELIVERY = 'DELIVERY',
  INTERVIEW = 'INTERVIEW',
  PARENT_VISIT = 'PARENT_VISIT',
  VENDOR = 'VENDOR',
  OTHER = 'OTHER',
};

export default VisitPurpose;
