import crypto from 'crypto';
import { KMSClient, GenerateDataKeyCommand, DecryptCommand } from '@aws-sdk/client-kms';

const IV_LENGTH = 16;

function kmsKeyId(): string {
  const keyId = process.env.AWS_KMS_KEY_ID;
  if (process.env.NODE_ENV === 'production') {
    if (!keyId || keyId.toLowerCase().includes('mock') || keyId.toLowerCase().includes('dummy')) {
      throw new Error('AWS_KMS_KEY_ID must be configured with a real KMS key in production.');
    }
  }
  return keyId || 'mock-kms-key-id-for-development';
}

// Initialize AWS KMS Client
const kmsClient = new KMSClient({
  region: process.env.AWS_REGION || 'us-east-1',
});

export class EncryptionService {
  /**
   * Encrypts sensitive fields (like medical history, government IDs) before inserting into Postgres.
   * Utilizes AES-256-GCM with a unique Data Encryption Key (DEK) generated by AWS KMS per payload.
   */
  static async encrypt(text: string): Promise<string> {
    // 1. Ask AWS KMS to generate a new Data Encryption Key (DEK)
    const generateKeyCommand = new GenerateDataKeyCommand({
      KeyId: kmsKeyId(),
      KeySpec: 'AES_256',
    });
    
    // Fallback to local crypto if no real AWS creds (for dev/scaffolding mock)
    let plaintextKey: Buffer;
    let encryptedKey: string;
    
    try {
      const { Plaintext, CiphertextBlob } = await kmsClient.send(generateKeyCommand);
      plaintextKey = Buffer.from(Plaintext!);
      encryptedKey = Buffer.from(CiphertextBlob!).toString('base64');
    } catch (error) {
      if (process.env.NODE_ENV === 'production') {
        throw new Error(`AWS KMS encryption failed: ${error instanceof Error ? error.message : String(error)}`);
      }
      console.warn(JSON.stringify({ event: 'kms.encrypt_fallback', message: 'AWS KMS unavailable; using development mock key.' }));
      plaintextKey = crypto.randomBytes(32);
      encryptedKey = 'mocked-encrypted-key';
    }

    // 2. Encrypt the data locally using the Plaintext DEK
    const iv = crypto.randomBytes(IV_LENGTH);
    const cipher = crypto.createCipheriv('aes-256-gcm', plaintextKey, iv);
    
    let encryptedData = cipher.update(text, 'utf8', 'base64');
    encryptedData += cipher.final('base64');
    const authTag = cipher.getAuthTag().toString('base64');
    
    // 3. Destroy the Plaintext DEK from memory immediately
    plaintextKey.fill(0);

    // Return payload: [Encrypted KMS Key] : [IV] : [Auth Tag] : [Encrypted Data]
    return `${encryptedKey}:${iv.toString('base64')}:${authTag}:${encryptedData}`;
  }

  /**
   * Decrypts fields retrieved from Postgres on the fly for authorized users.
   */
  static async decrypt(text: string): Promise<string> {
    const parts = text.split(':');
    if (parts.length !== 4) {
      throw new Error('Invalid KMS-encrypted payload format');
    }

    const [encryptedKeyBase64, ivBase64, authTagBase64, encryptedDataBase64] = parts;
    const encryptedKey = Buffer.from(encryptedKeyBase64, 'base64');
    const iv = Buffer.from(ivBase64, 'base64');
    const authTag = Buffer.from(authTagBase64, 'base64');
    const encryptedData = Buffer.from(encryptedDataBase64, 'base64');

    // 1. Ask AWS KMS to decrypt the DEK
    let plaintextKey: Buffer;
    try {
      const decryptCommand = new DecryptCommand({ CiphertextBlob: encryptedKey });
      const { Plaintext } = await kmsClient.send(decryptCommand);
      plaintextKey = Buffer.from(Plaintext!);
    } catch (error) {
      if (process.env.NODE_ENV === 'production') {
        throw new Error(`AWS KMS decryption failed: ${error instanceof Error ? error.message : String(error)}`);
      }
      console.warn(JSON.stringify({ event: 'kms.decrypt_fallback', message: 'AWS KMS unavailable; using development mock key.' }));
      plaintextKey = crypto.randomBytes(32); // Note: This will fail to decrypt real mock data, just a fallback
    }

    // 2. Decrypt the data locally
    const decipher = crypto.createDecipheriv('aes-256-gcm', plaintextKey, iv);
    decipher.setAuthTag(authTag);
    
    let decrypted = decipher.update(encryptedData, undefined, 'utf8');
    decrypted += decipher.final('utf8');
    
    // 3. Destroy DEK
    plaintextKey.fill(0);

    return decrypted;
  }
}
