ALTER TABLE "users" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "academic_years" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "academic_years" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "grade_subjects" ADD COLUMN "school_id" uuid;--> statement-breakpoint
ALTER TABLE "grade_subjects" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "grade_subjects" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "grades" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "grades" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "sections" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "sections" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "subjects" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "subjects" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "terms" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "terms" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "guardians" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "guardians" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "students" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "students" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "concessions" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "concessions" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "fee_components" ADD COLUMN "school_id" uuid;--> statement-breakpoint
ALTER TABLE "fee_components" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "fee_components" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "fee_plans" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "fee_plans" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "fine_rules" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "fine_rules" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "invoices" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "invoices" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "payment_audit_logs" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "payment_audit_logs" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "payment_orders" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "payment_orders" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "payment_provider_events" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "payment_provider_events" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "receipts" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "receipts" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "admission_applications" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "admission_applications" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "admission_documents" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "admission_documents" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "admission_leads" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "admission_leads" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "attendance_records" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "attendance_records" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "periods" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "periods" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "substitution_requests" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "substitution_requests" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "substitutions" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "substitutions" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "timetable_entries" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "timetable_entries" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "driver_background_checks" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "driver_background_checks" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "live_gps_pings" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "live_gps_pings" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "routes" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "routes" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "stops" ADD COLUMN "school_id" uuid;--> statement-breakpoint
ALTER TABLE "stops" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "stops" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "student_transport" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "student_transport" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "vehicle_maintenance_logs" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "vehicle_maintenance_logs" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "vehicles" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "vehicles" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "consents" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "consents" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "exam_proctoring_logs" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "exam_proctoring_logs" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "exam_result_hashes" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "exam_result_hashes" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "exam_schedules" ADD COLUMN "school_id" uuid;--> statement-breakpoint
ALTER TABLE "exam_schedules" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "exam_schedules" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "exams" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "exams" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "student_results" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "student_results" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "designations" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "designations" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "leave_policies" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "leave_policies" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "leave_requests" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "leave_requests" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "staff_departments" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "staff_departments" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "staff_profiles" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "staff_profiles" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "book_issues" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "book_issues" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "book_reservations" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "book_reservations" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "books" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "books" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_deliveries" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_deliveries" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_subscriptions" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "webhook_subscriptions" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "hardware_tokens" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "hardware_tokens" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "integration_api_keys" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "integration_api_keys" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "integration_audit_logs" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "integration_audit_logs" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "integration_connections" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "integration_connections" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "hostel_allocations" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "hostel_allocations" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "hostel_fees" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "hostel_fees" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "hostel_rooms" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "hostel_rooms" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "hostels" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "hostels" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "mess_menus" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "mess_menus" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "assets" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "assets" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "consumables" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "consumables" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "stock_alerts" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "stock_alerts" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "visitors" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "visitors" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "health_incidents" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "health_incidents" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "health_records" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "immunizations" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "immunizations" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "medication_schedules" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "medication_schedules" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "nurse_visit_logs" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "nurse_visit_logs" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "academic_events" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "academic_events" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "quiz_attempts" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "quiz_attempts" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "quiz_questions" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "quiz_questions" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "quizzes" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "quizzes" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "homework_assignments" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "homework_assignments" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "homework_submissions" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "homework_submissions" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "lesson_plans" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "lesson_plans" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "certificate_templates" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "certificate_templates" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "digilocker_sync_logs" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "digilocker_sync_logs" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "id_cards" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "id_cards" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "issued_certificates" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "issued_certificates" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "alumni_events" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "alumni_events" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "alumni_profiles" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "alumni_profiles" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "alumni_registrations" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "alumni_registrations" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "message_logs" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "message_logs" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "message_templates" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "message_templates" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "consent_forms" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "consent_forms" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "consent_responses" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "consent_responses" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_workflows" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_workflows" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "workflows" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "workflows" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "student_documents" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "student_documents" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "field_permissions" ADD COLUMN "school_id" uuid;--> statement-breakpoint
ALTER TABLE "field_permissions" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "field_permissions" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_fields" ADD COLUMN "school_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_fields" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_fields" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_layouts" ADD COLUMN "school_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_layouts" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_layouts" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_migration_jobs" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_migration_jobs" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_objects" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_objects" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_records" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_records" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_schema_versions" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_schema_versions" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_values" ADD COLUMN "school_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_values" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "metadata_values" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "agent_approvals" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "agent_approvals" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "agent_audit_logs" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "agent_audit_logs" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "embeddings" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "embeddings" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "background_job_attempts" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "background_job_attempts" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "background_jobs" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "background_jobs" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "notification_delivery_events" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "notification_delivery_events" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "notification_outbox" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "notification_outbox" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "observability_events" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "observability_events" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "slo_definitions" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "slo_definitions" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "slo_measurements" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "slo_measurements" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "sre_incidents" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "sre_incidents" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "workflow_approval_delegations" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "workflow_approval_delegations" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "workflow_approval_events" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "workflow_approval_events" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "workflow_approval_requests" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "workflow_approval_requests" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "workflow_approval_reviews" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "workflow_approval_reviews" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "operator_console_action_logs" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "operator_console_action_logs" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "operator_console_runbooks" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "operator_console_runbooks" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "operator_console_snapshots" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "operator_console_snapshots" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "bi_dashboards" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "bi_dashboards" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "bi_datasets" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "bi_datasets" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "bi_metric_snapshots" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "bi_metric_snapshots" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "bi_report_definitions" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "bi_report_definitions" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "bi_report_runs" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "bi_report_runs" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "faculty_workload" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "faculty_workload" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "university_courses" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "university_courses" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "university_programs" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "university_programs" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "coaching_batches" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "coaching_batches" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "test_series" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "test_series" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "test_series_results" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "test_series_results" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "host_families" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "host_families" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "international_placements" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "international_placements" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "student_visas" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "student_visas" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "ai_token_logs" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "grading_rubrics" ADD COLUMN "school_id" uuid;--> statement-breakpoint
ALTER TABLE "grading_rubrics" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "grading_rubrics" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "grading_scales" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "grading_scales" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "appointments" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "appointments" ADD COLUMN "group_id" uuid;--> statement-breakpoint
ALTER TABLE "diary_entries" ADD COLUMN "owner_id" uuid;--> statement-breakpoint
ALTER TABLE "diary_entries" ADD COLUMN "group_id" uuid;