-- Reconciliation baseline — intentionally a no-op.
--
-- Why this exists:
--   The drizzle snapshot chain had drifted. meta/ held snapshots only through
--   0003, while migrations 0004–0015 were hand-authored without accompanying
--   snapshots. As a result `drizzle-kit generate` diffed the live schema against
--   the stale 0003 baseline and emitted a full-schema "recreate everything"
--   migration, making the generator unusable.
--
-- What this migration does:
--   Nothing at the SQL level. Its sole purpose is to attach an accurate
--   current-schema snapshot (meta/0016_snapshot.json, produced by
--   `drizzle-kit generate`) as the new latest baseline so future
--   `drizzle-kit generate` runs diff against reality and emit correct deltas.
--
-- Safety:
--   Every existing database (production Neon and local/test) is already at this
--   schema via migrations 0000–0015, so there is nothing to apply. A freshly
--   provisioned database applies 0000–0015 to reach this same state, then this
--   no-op. Applying it is therefore always safe and idempotent.
SELECT 1;
