'use client';

import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { getMyAttendance, MyAttendanceRecord } from '@/lib/services/parent/parent.service';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip as RechartsTooltip, Legend } from 'recharts';
import { Download, CalendarDays, CheckCircle2, XCircle, AlertCircle, ChevronLeft, ChevronRight } from 'lucide-react';
import jsPDF from 'jspdf';

const COLORS = {
    PRESENT: '#10b981', // Emerald 500
    ABSENT: '#ef4444',  // Red 500
    LATE: '#f59e0b',    // Amber 500
    HOLIDAY: '#94a3b8'  // Slate 400
};

export default function MyAttendancePage() {
    const now = new Date();
    const [month, setMonth] = useState(now.getMonth() + 1);
    const [year, setYear] = useState(now.getFullYear());
    const [attendance, setAttendance] = useState<MyAttendanceRecord[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        setLoading(true);
        getMyAttendance({ month, year }).then(r => {
            setAttendance(r);
            setLoading(false);
        });
    }, [month, year]);

    const present = attendance.filter(a => a.status === 'PRESENT').length;
    const absent = attendance.filter(a => a.status === 'ABSENT').length;
    const late = attendance.filter(a => a.status === 'LATE').length;
    const total = attendance.filter(a => a.status !== 'HOLIDAY').length;
    const percentage = total > 0 ? Math.round(((present + late) / total) * 100) : 0;

    const chartData = [
        { name: 'Present', value: present, color: COLORS.PRESENT },
        { name: 'Absent', value: absent, color: COLORS.ABSENT },
        { name: 'Late', value: late, color: COLORS.LATE },
    ].filter(d => d.value > 0);

    const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
    const daysInMonth = new Date(year, month, 0).getDate();
    const firstDayOfWeek = new Date(year, month - 1, 1).getDay();
    
    const calendarDays = Array.from({ length: daysInMonth }, (_, i) => {
        const dayNum = i + 1;
        const dateStr = `${year}-${String(month).padStart(2, '0')}-${String(dayNum).padStart(2, '0')}`;
        const record = attendance.find(a => new Date(a.date).getDate() === dayNum);
        return { day: dayNum, status: record?.status || null, date: dateStr };
    });

    const generatePDF = () => {
        const doc = new jsPDF();
        doc.setFontSize(22);
        doc.text(`Attendance Report: ${months[month - 1]} ${year}`, 14, 20);
        
        doc.setFontSize(12);
        doc.setTextColor(100);
        doc.text("Generated by ScholarMind SIS", 14, 30);
        
        let yPos = 45;
        doc.setTextColor(0);
        doc.setFontSize(14);
        doc.text("Summary Statistics", 14, yPos);
        yPos += 10;
        
        doc.setFontSize(11);
        doc.text(`Total Working Days: ${total}`, 14, yPos);
        doc.text(`Present: ${present}`, 80, yPos);
        doc.text(`Absent: ${absent}`, 130, yPos);
        doc.text(`Attendance: ${percentage}%`, 170, yPos);
        
        yPos += 15;
        doc.setFontSize(14);
        doc.text("Daily Records", 14, yPos);
        yPos += 8;
        
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("Date", 14, yPos);
        doc.text("Status", 80, yPos);
        
        yPos += 4;
        doc.line(14, yPos, 195, yPos);
        yPos += 8;
        
        doc.setTextColor(0);
        calendarDays.filter(d => d.status).forEach(d => {
            if (yPos > 280) {
                doc.addPage();
                yPos = 20;
            }
            doc.text(d.date, 14, yPos);
            doc.text(d.status || '-', 80, yPos);
            yPos += 8;
        });

        doc.save(`Attendance_${months[month - 1]}_${year}.pdf`);
    };

    return (
        <div className="space-y-8 max-w-7xl mx-auto pb-12">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center border-b pb-6">
                <div>
                    <h1 className="text-2xl font-semibold tracking-tight text-slate-900">Attendance Register</h1>
                    <p className="text-sm text-slate-500 mt-1">Monitor daily presence and term participation</p>
                </div>
                <div className="mt-4 md:mt-0 flex items-center bg-white border shadow-sm rounded-md p-1">
                    <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => { if (month === 1) { setMonth(12); setYear(year - 1); } else setMonth(month - 1); }}>
                        <ChevronLeft className="h-4 w-4" />
                    </Button>
                    <div className="px-4 text-sm font-medium w-40 text-center text-slate-700">
                        {months[month - 1]} {year}
                    </div>
                    <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => { if (month === 12) { setMonth(1); setYear(year + 1); } else setMonth(month + 1); }}>
                        <ChevronRight className="h-4 w-4" />
                    </Button>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                <Card className="border-slate-200 shadow-sm">
                    <CardContent className="p-6">
                        <div className="flex items-center justify-between mb-4">
                            <div className="text-sm font-medium text-slate-500">Present</div>
                            <CheckCircle2 className="h-5 w-5 text-emerald-500" />
                        </div>
                        <div className="text-3xl font-bold text-slate-900">{present} <span className="text-sm font-normal text-slate-400">days</span></div>
                    </CardContent>
                </Card>
                <Card className="border-slate-200 shadow-sm">
                    <CardContent className="p-6">
                        <div className="flex items-center justify-between mb-4">
                            <div className="text-sm font-medium text-slate-500">Absent</div>
                            <XCircle className="h-5 w-5 text-red-500" />
                        </div>
                        <div className="text-3xl font-bold text-slate-900">{absent} <span className="text-sm font-normal text-slate-400">days</span></div>
                    </CardContent>
                </Card>
                <Card className="border-slate-200 shadow-sm">
                    <CardContent className="p-6">
                        <div className="flex items-center justify-between mb-4">
                            <div className="text-sm font-medium text-slate-500">Working Days</div>
                            <CalendarDays className="h-5 w-5 text-blue-500" />
                        </div>
                        <div className="text-3xl font-bold text-slate-900">{total} <span className="text-sm font-normal text-slate-400">days</span></div>
                    </CardContent>
                </Card>
                <Card className="border-slate-200 shadow-sm relative overflow-hidden">
                    <div className={`absolute inset-0 opacity-10 ${percentage >= 85 ? 'bg-emerald-500' : percentage >= 75 ? 'bg-amber-500' : 'bg-red-500'}`} />
                    <CardContent className="p-6 relative">
                        <div className="flex items-center justify-between mb-4">
                            <div className="text-sm font-medium text-slate-700">Attendance Rate</div>
                            <AlertCircle className={`h-5 w-5 ${percentage >= 85 ? 'text-emerald-600' : percentage >= 75 ? 'text-amber-600' : 'text-red-600'}`} />
                        </div>
                        <div className={`text-3xl font-bold ${percentage >= 85 ? 'text-emerald-700' : percentage >= 75 ? 'text-amber-700' : 'text-red-700'}`}>
                            {percentage}%
                        </div>
                    </CardContent>
                </Card>
            </div>

            <div className="grid lg:grid-cols-3 gap-6">
                <Card className="lg:col-span-2 border-slate-200 shadow-sm">
                    <CardHeader className="bg-slate-50 border-b px-6 py-4 flex flex-row items-center justify-between">
                        <CardTitle className="text-base font-semibold text-slate-800 flex items-center">
                            <CalendarDays className="w-4 h-4 mr-2" /> Daily Log
                        </CardTitle>
                        <Button size="sm" variant="outline" className="h-8 text-xs font-medium bg-white" onClick={generatePDF}>
                            <Download className="w-4 h-4 mr-2" /> Export Log
                        </Button>
                    </CardHeader>
                    <CardContent className="p-6">
                        {loading ? (
                            <div className="h-64 flex items-center justify-center text-sm text-slate-400">Syncing register...</div>
                        ) : (
                            <>
                                <div className="grid grid-cols-7 gap-2 mb-2">
                                    {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(d => (
                                        <div key={d} className="text-center text-[10px] uppercase tracking-wider text-slate-400 font-semibold py-2">
                                            {d}
                                        </div>
                                    ))}
                                    {Array.from({ length: firstDayOfWeek }).map((_, i) => (
                                        <div key={`empty-${i}`} className="aspect-square rounded-md bg-slate-50/50 border border-slate-100" />
                                    ))}
                                    {calendarDays.map(({ day, status }) => (
                                        <div key={day} className={`
                                            aspect-square flex flex-col items-center justify-center rounded-md text-sm font-medium border transition-all
                                            ${status === 'PRESENT' ? 'bg-emerald-50 text-emerald-700 border-emerald-200 shadow-sm' :
                                              status === 'ABSENT' ? 'bg-red-50 text-red-700 border-red-200 shadow-sm' :
                                              status === 'LATE' ? 'bg-amber-50 text-amber-700 border-amber-200 shadow-sm' :
                                              'bg-white text-slate-400 border-slate-100'}
                                        `}>
                                            <span>{day}</span>
                                            {status && (
                                                <span className="text-[9px] mt-1 tracking-tight font-semibold opacity-70 uppercase">
                                                    {status.substring(0,3)}
                                                </span>
                                            )}
                                        </div>
                                    ))}
                                </div>
                            </>
                        )}
                    </CardContent>
                </Card>

                <Card className="border-slate-200 shadow-sm">
                    <CardHeader className="bg-slate-50 border-b px-6 py-4">
                        <CardTitle className="text-base font-semibold text-slate-800">Distribution</CardTitle>
                    </CardHeader>
                    <CardContent className="p-6">
                        {total === 0 ? (
                            <div className="h-48 flex items-center justify-center text-sm text-slate-400">No data for this month</div>
                        ) : (
                            <div className="h-64">
                                <ResponsiveContainer width="100%" height="100%">
                                    <PieChart>
                                        <Pie
                                            data={chartData}
                                            cx="50%"
                                            cy="50%"
                                            innerRadius={60}
                                            outerRadius={80}
                                            paddingAngle={2}
                                            dataKey="value"
                                        >
                                            {chartData.map((entry, index) => (
                                                <Cell key={`cell-${index}`} fill={entry.color} />
                                            ))}
                                        </Pie>
                                        <RechartsTooltip 
                                            contentStyle={{ borderRadius: '6px', fontSize: '12px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                                            itemStyle={{ color: '#334155', fontWeight: 500 }}
                                        />
                                        <Legend verticalAlign="bottom" height={36} iconType="circle" wrapperStyle={{ fontSize: '12px' }}/>
                                    </PieChart>
                                </ResponsiveContainer>
                            </div>
                        )}
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
