import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';

export default async function AlertsPage() {
    return (
        <div className="space-y-6 max-w-4xl mx-auto">
            <div className="flex justify-between items-center pb-4 border-b border-gray-200">
                <div>
                    <h1 className="text-2xl font-bold tracking-tight text-gray-900 flex items-center gap-2">
                        <span className="text-rose-500">🔔</span> Real-Time Smart Alerts
                    </h1>
                    <p className="text-gray-500 mt-1">Autonomous notifications generated by ScholarMind AI Agents.</p>
                </div>
                <button className="text-sm font-medium text-gray-600 bg-white border border-gray-300 px-4 py-2 rounded-lg hover:bg-gray-50 transition-colors">
                    Notification Preferences
                </button>
            </div>

            <div className="space-y-4">
                {/* Critical Alert */}
                <Card className="border-rose-200 border-l-4 border-l-rose-500 shadow-sm">
                    <CardContent className="p-5 flex items-start gap-4">
                        <div className="w-10 h-10 rounded-full bg-rose-100 flex items-center justify-center text-xl shrink-0">
                            🏃
                        </div>
                        <div className="flex-1">
                            <div className="flex justify-between items-start">
                                <h3 className="font-semibold text-gray-900 text-lg leading-tight">Unexpected Absence Detected</h3>
                                <span className="text-xs text-gray-500 font-medium">Just Now</span>
                            </div>
                            <p className="text-sm text-gray-600 mt-1">
                                <span className="font-semibold text-gray-700">AttendAgent</span> has flagged that Aarav was marked absent for the 1st period (Mathematics), despite swiping into the main campus gate at 08:12 AM.
                            </p>
                            <div className="mt-4 flex gap-3">
                                <button className="text-xs font-semibold text-white bg-rose-600 hover:bg-rose-700 px-4 py-2 rounded transition-colors shadow-sm">
                                    Acknowledge & Escalate
                                </button>
                                <button className="text-xs font-medium text-gray-600 border border-gray-300 px-4 py-2 rounded hover:bg-gray-50 transition-colors cursor-pointer">
                                    I am aware
                                </button>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                {/* Financial Alert */}
                <Card className="border-amber-200 border-l-4 border-l-amber-500 shadow-sm">
                    <CardContent className="p-5 flex items-start gap-4">
                        <div className="w-10 h-10 rounded-full bg-amber-100 flex items-center justify-center text-xl shrink-0">
                            💳
                        </div>
                        <div className="flex-1">
                            <div className="flex justify-between items-start">
                                <h3 className="font-semibold text-gray-900 text-lg leading-tight">Payment Deadline Approaching</h3>
                                <span className="text-xs text-gray-500 font-medium">2 days ago</span>
                            </div>
                            <p className="text-sm text-gray-600 mt-1">
                                <span className="font-semibold text-gray-700">FeeAgent</span> reminds you that the Q3 Hostel Installment (₹25,000) is due in 3 days. A late fee of ₹500 will apply thereafter.
                            </p>
                            <div className="mt-4 flex gap-3">
                                <button className="text-xs font-semibold text-white bg-amber-600 hover:bg-amber-700 px-4 py-2 rounded transition-colors shadow-sm">
                                    Pay Now (Stripe)
                                </button>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                {/* Academic Alert */}
                <Card className="border-indigo-200 border-l-4 border-l-indigo-500 shadow-sm opacity-80 hover:opacity-100 transition-opacity">
                    <CardContent className="p-5 flex items-start gap-4">
                        <div className="w-10 h-10 rounded-full bg-indigo-100 flex items-center justify-center text-xl shrink-0">
                            📈
                        </div>
                        <div className="flex-1">
                            <div className="flex justify-between items-start">
                                <h3 className="font-semibold text-gray-900 text-lg leading-tight">Academic Milestone Reached</h3>
                                <span className="text-xs text-gray-500 font-medium">1 week ago</span>
                            </div>
                            <p className="text-sm text-gray-600 mt-1">
                                <span className="font-semibold text-gray-700">AcademAgent</span> reports that Aarav scored in the top 5% of the class for the Data Structures Midterm. 
                            </p>
                        </div>
                    </CardContent>
                </Card>
                
                <div className="text-center pt-8">
                    <p className="text-xs text-gray-400 font-medium">End of automated alerts history.</p>
                </div>
            </div>
        </div>
    );
}
