// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { AdmissionApplicationsId } from './AdmissionApplications';
import type { UsersId } from './Users';

/** Identifier type for public.admission_documents */
export type AdmissionDocumentsId = string & { __brand: 'public.admission_documents' };

/** Represents the table public.admission_documents */
export default interface AdmissionDocuments {
  id: AdmissionDocumentsId;

  tenant_id: TenantsId;

  application_id: AdmissionApplicationsId;

  document_type: string;

  file_name: string;

  file_url: string;

  file_size: string | null;

  is_verified: Date | null;

  verified_by: UsersId | null;

  created_at: Date;
}

/** Represents the initializer for the table public.admission_documents */
export interface AdmissionDocumentsInitializer {
  /** Default value: gen_random_uuid() */
  id?: AdmissionDocumentsId;

  tenant_id: TenantsId;

  application_id: AdmissionApplicationsId;

  document_type: string;

  file_name: string;

  file_url: string;

  file_size?: string | null;

  is_verified?: Date | null;

  verified_by?: UsersId | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.admission_documents */
export interface AdmissionDocumentsMutator {
  id?: AdmissionDocumentsId;

  tenant_id?: TenantsId;

  application_id?: AdmissionApplicationsId;

  document_type?: string;

  file_name?: string;

  file_url?: string;

  file_size?: string | null;

  is_verified?: Date | null;

  verified_by?: UsersId | null;

  created_at?: Date;
}
