// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { default as LeadSource } from './LeadSource';
import type { default as PipelineStage } from './PipelineStage';
import type { UsersId } from './Users';

/** Identifier type for public.admission_leads */
export type AdmissionLeadsId = string & { __brand: 'public.admission_leads' };

/** Represents the table public.admission_leads */
export default interface AdmissionLeads {
  id: AdmissionLeadsId;

  tenant_id: TenantsId;

  child_first_name: string;

  child_last_name: string;

  child_dob: Date | null;

  applying_for_grade: string;

  parent_name: string;

  parent_email: string;

  parent_phone: string;

  source: LeadSource;

  stage: PipelineStage;

  assigned_to: UsersId | null;

  notes: string | null;

  previous_school: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.admission_leads */
export interface AdmissionLeadsInitializer {
  /** Default value: gen_random_uuid() */
  id?: AdmissionLeadsId;

  tenant_id: TenantsId;

  child_first_name: string;

  child_last_name: string;

  child_dob?: Date | null;

  applying_for_grade: string;

  parent_name: string;

  parent_email: string;

  parent_phone: string;

  /** Default value: 'WEBSITE'::lead_source */
  source?: LeadSource;

  /** Default value: 'NEW'::pipeline_stage */
  stage?: PipelineStage;

  assigned_to?: UsersId | null;

  notes?: string | null;

  previous_school?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.admission_leads */
export interface AdmissionLeadsMutator {
  id?: AdmissionLeadsId;

  tenant_id?: TenantsId;

  child_first_name?: string;

  child_last_name?: string;

  child_dob?: Date | null;

  applying_for_grade?: string;

  parent_name?: string;

  parent_email?: string;

  parent_phone?: string;

  source?: LeadSource;

  stage?: PipelineStage;

  assigned_to?: UsersId | null;

  notes?: string | null;

  previous_school?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
