// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.alert_severity */
enum AlertSeverity {
  CRITICAL = 'CRITICAL',
  WARNING = 'WARNING',
  INFO = 'INFO',
};

export default AlertSeverity;
