// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.allocation_status */
enum AllocationStatus {
  ACTIVE = 'ACTIVE',
  VACATED = 'VACATED',
  PENDING = 'PENDING',
};

export default AllocationStatus;
