// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.alumni_event_status */
enum AlumniEventStatus {
  UPCOMING = 'UPCOMING',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
};

export default AlumniEventStatus;
