// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';

/** Identifier type for public.alumni_profiles */
export type AlumniProfilesId = string & { __brand: 'public.alumni_profiles' };

/** Represents the table public.alumni_profiles */
export default interface AlumniProfiles {
  id: AlumniProfilesId;

  tenant_id: TenantsId;

  name: string;

  email: string;

  phone: string | null;

  batch: string;

  graduation_year: number | null;

  current_company: string | null;

  designation: string | null;

  location: string | null;

  linkedin: string | null;

  photo: string | null;

  is_verified: boolean;

  created_at: Date;
}

/** Represents the initializer for the table public.alumni_profiles */
export interface AlumniProfilesInitializer {
  /** Default value: gen_random_uuid() */
  id?: AlumniProfilesId;

  tenant_id: TenantsId;

  name: string;

  email: string;

  phone?: string | null;

  batch: string;

  graduation_year?: number | null;

  current_company?: string | null;

  designation?: string | null;

  location?: string | null;

  linkedin?: string | null;

  photo?: string | null;

  /** Default value: false */
  is_verified?: boolean;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.alumni_profiles */
export interface AlumniProfilesMutator {
  id?: AlumniProfilesId;

  tenant_id?: TenantsId;

  name?: string;

  email?: string;

  phone?: string | null;

  batch?: string;

  graduation_year?: number | null;

  current_company?: string | null;

  designation?: string | null;

  location?: string | null;

  linkedin?: string | null;

  photo?: string | null;

  is_verified?: boolean;

  created_at?: Date;
}
