// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { default as AssetCategory } from './AssetCategory';
import type { default as AssetCondition } from './AssetCondition';

/** Identifier type for public.assets */
export type AssetsId = string & { __brand: 'public.assets' };

/** Represents the table public.assets */
export default interface Assets {
  id: AssetsId;

  tenant_id: TenantsId;

  name: string;

  category: AssetCategory;

  serial_number: string | null;

  purchase_date: Date | null;

  purchase_price: string | null;

  vendor: string | null;

  location: string | null;

  assigned_to: string | null;

  condition: AssetCondition;

  last_maintenance_date: Date | null;

  warranty_expiry: Date | null;

  notes: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.assets */
export interface AssetsInitializer {
  /** Default value: gen_random_uuid() */
  id?: AssetsId;

  tenant_id: TenantsId;

  name: string;

  category: AssetCategory;

  serial_number?: string | null;

  purchase_date?: Date | null;

  purchase_price?: string | null;

  vendor?: string | null;

  location?: string | null;

  assigned_to?: string | null;

  /** Default value: 'GOOD'::asset_condition */
  condition?: AssetCondition;

  last_maintenance_date?: Date | null;

  warranty_expiry?: Date | null;

  notes?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.assets */
export interface AssetsMutator {
  id?: AssetsId;

  tenant_id?: TenantsId;

  name?: string;

  category?: AssetCategory;

  serial_number?: string | null;

  purchase_date?: Date | null;

  purchase_price?: string | null;

  vendor?: string | null;

  location?: string | null;

  assigned_to?: string | null;

  condition?: AssetCondition;

  last_maintenance_date?: Date | null;

  warranty_expiry?: Date | null;

  notes?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
