// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.asset_condition */
enum AssetCondition {
  EXCELLENT = 'EXCELLENT',
  GOOD = 'GOOD',
  FAIR = 'FAIR',
  NEEDS_REPAIR = 'NEEDS_REPAIR',
  DISPOSED = 'DISPOSED',
};

export default AssetCondition;
