// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.attempt_status */
enum AttemptStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  GRADED = 'GRADED',
};

export default AttemptStatus;
