// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { BooksId } from './Books';
import type { UsersId } from './Users';
import type { StudentsId } from './Students';
import type { default as IssueStatus } from './IssueStatus';

/** Identifier type for public.book_issues */
export type BookIssuesId = string & { __brand: 'public.book_issues' };

/** Represents the table public.book_issues */
export default interface BookIssues {
  id: BookIssuesId;

  tenant_id: TenantsId;

  book_id: BooksId;

  issued_to_user_id: UsersId;

  issued_to_student_id: StudentsId | null;

  issue_date: Date;

  due_date: Date;

  return_date: Date | null;

  status: IssueStatus;

  fine_amount: string | null;

  fine_reason: string | null;

  is_fine_paid: boolean;

  issued_by: UsersId | null;

  returned_to: UsersId | null;

  remarks: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.book_issues */
export interface BookIssuesInitializer {
  /** Default value: gen_random_uuid() */
  id?: BookIssuesId;

  tenant_id: TenantsId;

  book_id: BooksId;

  issued_to_user_id: UsersId;

  issued_to_student_id?: StudentsId | null;

  issue_date: Date;

  due_date: Date;

  return_date?: Date | null;

  /** Default value: 'ISSUED'::issue_status */
  status?: IssueStatus;

  /** Default value: '0'::numeric */
  fine_amount?: string | null;

  fine_reason?: string | null;

  /** Default value: false */
  is_fine_paid?: boolean;

  issued_by?: UsersId | null;

  returned_to?: UsersId | null;

  remarks?: string | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.book_issues */
export interface BookIssuesMutator {
  id?: BookIssuesId;

  tenant_id?: TenantsId;

  book_id?: BooksId;

  issued_to_user_id?: UsersId;

  issued_to_student_id?: StudentsId | null;

  issue_date?: Date;

  due_date?: Date;

  return_date?: Date | null;

  status?: IssueStatus;

  fine_amount?: string | null;

  fine_reason?: string | null;

  is_fine_paid?: boolean;

  issued_by?: UsersId | null;

  returned_to?: UsersId | null;

  remarks?: string | null;

  created_at?: Date;
}
