// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { default as BookCategory } from './BookCategory';

/** Identifier type for public.books */
export type BooksId = string & { __brand: 'public.books' };

/** Represents the table public.books */
export default interface Books {
  id: BooksId;

  tenant_id: TenantsId;

  title: string;

  author: string;

  isbn: string | null;

  publisher: string | null;

  edition: string | null;

  year: number | null;

  category: BookCategory;

  subject: string | null;

  language: string | null;

  location: string | null;

  total_copies: number;

  available_copies: number;

  price: string | null;

  description: string | null;

  cover_url: string | null;

  is_active: boolean;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.books */
export interface BooksInitializer {
  /** Default value: gen_random_uuid() */
  id?: BooksId;

  tenant_id: TenantsId;

  title: string;

  author: string;

  isbn?: string | null;

  publisher?: string | null;

  edition?: string | null;

  year?: number | null;

  /** Default value: 'TEXTBOOK'::book_category */
  category?: BookCategory;

  subject?: string | null;

  /** Default value: 'English'::character varying */
  language?: string | null;

  location?: string | null;

  /** Default value: 1 */
  total_copies?: number;

  /** Default value: 1 */
  available_copies?: number;

  price?: string | null;

  description?: string | null;

  cover_url?: string | null;

  /** Default value: true */
  is_active?: boolean;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.books */
export interface BooksMutator {
  id?: BooksId;

  tenant_id?: TenantsId;

  title?: string;

  author?: string;

  isbn?: string | null;

  publisher?: string | null;

  edition?: string | null;

  year?: number | null;

  category?: BookCategory;

  subject?: string | null;

  language?: string | null;

  location?: string | null;

  total_copies?: number;

  available_copies?: number;

  price?: string | null;

  description?: string | null;

  cover_url?: string | null;

  is_active?: boolean;

  created_at?: Date;

  updated_at?: Date;
}
