// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { BooksId } from './Books';
import type { UsersId } from './Users';
import type { default as ReservationStatus } from './ReservationStatus';

/** Identifier type for public.book_reservations */
export type BookReservationsId = string & { __brand: 'public.book_reservations' };

/** Represents the table public.book_reservations */
export default interface BookReservations {
  id: BookReservationsId;

  tenant_id: TenantsId;

  book_id: BooksId;

  user_id: UsersId;

  reserved_at: Date;

  expires_at: Date | null;

  status: ReservationStatus;

  created_at: Date;
}

/** Represents the initializer for the table public.book_reservations */
export interface BookReservationsInitializer {
  /** Default value: gen_random_uuid() */
  id?: BookReservationsId;

  tenant_id: TenantsId;

  book_id: BooksId;

  user_id: UsersId;

  /** Default value: now() */
  reserved_at?: Date;

  expires_at?: Date | null;

  /** Default value: 'ACTIVE'::reservation_status */
  status?: ReservationStatus;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.book_reservations */
export interface BookReservationsMutator {
  id?: BookReservationsId;

  tenant_id?: TenantsId;

  book_id?: BooksId;

  user_id?: UsersId;

  reserved_at?: Date;

  expires_at?: Date | null;

  status?: ReservationStatus;

  created_at?: Date;
}
