// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.book_category */
enum BookCategory {
  TEXTBOOK = 'TEXTBOOK',
  REFERENCE = 'REFERENCE',
  FICTION = 'FICTION',
  NON_FICTION = 'NON_FICTION',
  MAGAZINE = 'MAGAZINE',
  NEWSPAPER = 'NEWSPAPER',
  JOURNAL = 'JOURNAL',
};

export default BookCategory;
