// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.certificate_status */
enum CertificateStatus {
  DRAFT = 'DRAFT',
  ISSUED = 'ISSUED',
  REVOKED = 'REVOKED',
};

export default CertificateStatus;
