// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.certificate_type */
enum CertificateType {
  TRANSFER = 'TRANSFER',
  CHARACTER = 'CHARACTER',
  BONAFIDE = 'BONAFIDE',
  MIGRATION = 'MIGRATION',
  REPORT_CARD = 'REPORT_CARD',
  MARKSHEET = 'MARKSHEET',
  CUSTOM = 'CUSTOM',
};

export default CertificateType;
