// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { default as CertificateType } from './CertificateType';

/** Identifier type for public.certificate_templates */
export type CertificateTemplatesId = string & { __brand: 'public.certificate_templates' };

/** Represents the table public.certificate_templates */
export default interface CertificateTemplates {
  id: CertificateTemplatesId;

  tenant_id: TenantsId;

  name: string;

  type: CertificateType;

  html_template: string | null;

  variables: unknown | null;

  is_active: boolean;

  created_at: Date;
}

/** Represents the initializer for the table public.certificate_templates */
export interface CertificateTemplatesInitializer {
  /** Default value: gen_random_uuid() */
  id?: CertificateTemplatesId;

  tenant_id: TenantsId;

  name: string;

  type: CertificateType;

  html_template?: string | null;

  /** Default value: '[]'::jsonb */
  variables?: unknown | null;

  /** Default value: true */
  is_active?: boolean;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.certificate_templates */
export interface CertificateTemplatesMutator {
  id?: CertificateTemplatesId;

  tenant_id?: TenantsId;

  name?: string;

  type?: CertificateType;

  html_template?: string | null;

  variables?: unknown | null;

  is_active?: boolean;

  created_at?: Date;
}
