// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';

/** Identifier type for public.coaching_batches */
export type CoachingBatchesId = string & { __brand: 'public.coaching_batches' };

/** Represents the table public.coaching_batches */
export default interface CoachingBatches {
  id: CoachingBatchesId;

  tenant_id: TenantsId;

  name: string;

  target_exam: string;

  start_date: Date;

  end_date: Date;

  is_active: boolean;

  created_at: Date;
}

/** Represents the initializer for the table public.coaching_batches */
export interface CoachingBatchesInitializer {
  /** Default value: gen_random_uuid() */
  id?: CoachingBatchesId;

  tenant_id: TenantsId;

  name: string;

  target_exam: string;

  start_date: Date;

  end_date: Date;

  /** Default value: true */
  is_active?: boolean;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.coaching_batches */
export interface CoachingBatchesMutator {
  id?: CoachingBatchesId;

  tenant_id?: TenantsId;

  name?: string;

  target_exam?: string;

  start_date?: Date;

  end_date?: Date;

  is_active?: boolean;

  created_at?: Date;
}
