// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as SubscriptionTier } from './SubscriptionTier';

/** Identifier type for public.companies */
export type CompaniesId = string & { __brand: 'public.companies' };

/** Represents the table public.companies */
export default interface Companies {
  id: CompaniesId;

  name: string;

  stripe_customer_id: string | null;

  stripe_subscription_id: string | null;

  stripe_price_id: string | null;

  stripe_current_period_end: Date | null;

  billing_status: string;

  subscription_tier: SubscriptionTier;

  active_modules: string[] | null;

  region: string;

  domain_mask: string | null;

  theme_color: string | null;

  is_active: boolean;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.companies */
export interface CompaniesInitializer {
  /** Default value: gen_random_uuid() */
  id?: CompaniesId;

  name: string;

  stripe_customer_id?: string | null;

  stripe_subscription_id?: string | null;

  stripe_price_id?: string | null;

  stripe_current_period_end?: Date | null;

  /** Default value: 'TRIALING'::character varying */
  billing_status?: string;

  /** Default value: 'CORE'::subscription_tier */
  subscription_tier?: SubscriptionTier;

  /** Default value: '{ATTENDANCE,FEES,COMMUNICATION}'::text[] */
  active_modules?: string[] | null;

  /** Default value: 'US-EAST'::character varying */
  region?: string;

  domain_mask?: string | null;

  /** Default value: '#4F46E5'::character varying */
  theme_color?: string | null;

  /** Default value: true */
  is_active?: boolean;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.companies */
export interface CompaniesMutator {
  id?: CompaniesId;

  name?: string;

  stripe_customer_id?: string | null;

  stripe_subscription_id?: string | null;

  stripe_price_id?: string | null;

  stripe_current_period_end?: Date | null;

  billing_status?: string;

  subscription_tier?: SubscriptionTier;

  active_modules?: string[] | null;

  region?: string;

  domain_mask?: string | null;

  theme_color?: string | null;

  is_active?: boolean;

  created_at?: Date;

  updated_at?: Date;
}
