// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.concession_type */
enum ConcessionType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED = 'FIXED',
  SIBLING = 'SIBLING',
  MERIT = 'MERIT',
  STAFF_CHILD = 'STAFF_CHILD',
  CUSTOM = 'CUSTOM',
};

export default ConcessionType;
