// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.consumable_category */
enum ConsumableCategory {
  STATIONERY = 'STATIONERY',
  CLEANING = 'CLEANING',
  SPORTS = 'SPORTS',
  LAB_SUPPLIES = 'LAB_SUPPLIES',
  FIRST_AID = 'FIRST_AID',
  OFFICE = 'OFFICE',
};

export default ConsumableCategory;
