// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.consent_channel */
enum ConsentChannel {
  SMS = 'SMS',
  WHATSAPP = 'WHATSAPP',
  EMAIL = 'EMAIL',
};

export default ConsentChannel;
