// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { UsersId } from './Users';

/** Identifier type for public.consent_forms */
export type ConsentFormsId = string & { __brand: 'public.consent_forms' };

/** Represents the table public.consent_forms */
export default interface ConsentForms {
  id: ConsentFormsId;

  tenant_id: TenantsId;

  title: string;

  description: string | null;

  form_type: string;

  audience: string;

  due_date: Date | null;

  created_by: UsersId | null;

  is_active: boolean;

  created_at: Date;
}

/** Represents the initializer for the table public.consent_forms */
export interface ConsentFormsInitializer {
  /** Default value: gen_random_uuid() */
  id?: ConsentFormsId;

  tenant_id: TenantsId;

  title: string;

  description?: string | null;

  form_type: string;

  /** Default value: 'ALL'::character varying */
  audience?: string;

  due_date?: Date | null;

  created_by?: UsersId | null;

  /** Default value: true */
  is_active?: boolean;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.consent_forms */
export interface ConsentFormsMutator {
  id?: ConsentFormsId;

  tenant_id?: TenantsId;

  title?: string;

  description?: string | null;

  form_type?: string;

  audience?: string;

  due_date?: Date | null;

  created_by?: UsersId | null;

  is_active?: boolean;

  created_at?: Date;
}
