// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.consent_response */
enum ConsentResponse {
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
};

export default ConsentResponse;
