// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { default as ConsumableCategory } from './ConsumableCategory';

/** Identifier type for public.consumables */
export type ConsumablesId = string & { __brand: 'public.consumables' };

/** Represents the table public.consumables */
export default interface Consumables {
  id: ConsumablesId;

  tenant_id: TenantsId;

  name: string;

  category: ConsumableCategory;

  unit: string;

  current_stock: number;

  minimum_stock: number;

  reorder_level: number;

  unit_price: string | null;

  last_restock_date: Date | null;

  supplier: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.consumables */
export interface ConsumablesInitializer {
  /** Default value: gen_random_uuid() */
  id?: ConsumablesId;

  tenant_id: TenantsId;

  name: string;

  category: ConsumableCategory;

  unit: string;

  /** Default value: 0 */
  current_stock?: number;

  /** Default value: 0 */
  minimum_stock?: number;

  /** Default value: 0 */
  reorder_level?: number;

  unit_price?: string | null;

  last_restock_date?: Date | null;

  supplier?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.consumables */
export interface ConsumablesMutator {
  id?: ConsumablesId;

  tenant_id?: TenantsId;

  name?: string;

  category?: ConsumableCategory;

  unit?: string;

  current_stock?: number;

  minimum_stock?: number;

  reorder_level?: number;

  unit_price?: string | null;

  last_restock_date?: Date | null;

  supplier?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
