// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.day_of_week */
enum DayOfWeek {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
};

export default DayOfWeek;
