// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.degree_type */
enum DegreeType {
  BACHELOR = 'BACHELOR',
  MASTER = 'MASTER',
  PHD = 'PHD',
  DIPLOMA = 'DIPLOMA',
};

export default DegreeType;
