// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.delivery_status */
enum DeliveryStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  RETRYING = 'RETRYING',
};

export default DeliveryStatus;
