// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.employment_type */
enum EmploymentType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACT = 'CONTRACT',
  VISITING = 'VISITING',
};

export default EmploymentType;
