// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.event_type */
enum EventType {
  HOLIDAY = 'HOLIDAY',
  EXAM = 'EXAM',
  PTM = 'PTM',
  SPORTS_DAY = 'SPORTS_DAY',
  CULTURAL = 'CULTURAL',
  ACADEMIC = 'ACADEMIC',
  OTHER = 'OTHER',
};

export default EventType;
