// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.exam_type */
enum ExamType {
  UNIT_TEST = 'UNIT_TEST',
  MID_TERM = 'MID_TERM',
  FINAL = 'FINAL',
  PRACTICE = 'PRACTICE',
  BOARD_PREP = 'BOARD_PREP',
};

export default ExamType;
