// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ExamsId } from './Exams';
import type { GradesId } from './Grades';
import type { SubjectsId } from './Subjects';

/** Identifier type for public.exam_schedules */
export type ExamSchedulesId = string & { __brand: 'public.exam_schedules' };

/** Represents the table public.exam_schedules */
export default interface ExamSchedules {
  id: ExamSchedulesId;

  exam_id: ExamsId;

  grade_id: GradesId;

  subject_id: SubjectsId;

  exam_date: Date;

  start_time: string;

  end_time: string;

  max_marks: string;

  passing_marks: string;

  room_number: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.exam_schedules */
export interface ExamSchedulesInitializer {
  /** Default value: gen_random_uuid() */
  id?: ExamSchedulesId;

  exam_id: ExamsId;

  grade_id: GradesId;

  subject_id: SubjectsId;

  exam_date: Date;

  start_time: string;

  end_time: string;

  max_marks: string;

  passing_marks: string;

  room_number?: string | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.exam_schedules */
export interface ExamSchedulesMutator {
  id?: ExamSchedulesId;

  exam_id?: ExamsId;

  grade_id?: GradesId;

  subject_id?: SubjectsId;

  exam_date?: Date;

  start_time?: string;

  end_time?: string;

  max_marks?: string;

  passing_marks?: string;

  room_number?: string | null;

  created_at?: Date;
}
