// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { AcademicYearsId } from './AcademicYears';
import type { default as ExamType } from './ExamType';

/** Identifier type for public.exams */
export type ExamsId = string & { __brand: 'public.exams' };

/** Represents the table public.exams */
export default interface Exams {
  id: ExamsId;

  tenant_id: TenantsId;

  academic_year_id: AcademicYearsId;

  name: string;

  type: ExamType;

  start_date: Date;

  end_date: Date;

  description: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.exams */
export interface ExamsInitializer {
  /** Default value: gen_random_uuid() */
  id?: ExamsId;

  tenant_id: TenantsId;

  academic_year_id: AcademicYearsId;

  name: string;

  type: ExamType;

  start_date: Date;

  end_date: Date;

  description?: string | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.exams */
export interface ExamsMutator {
  id?: ExamsId;

  tenant_id?: TenantsId;

  academic_year_id?: AcademicYearsId;

  name?: string;

  type?: ExamType;

  start_date?: Date;

  end_date?: Date;

  description?: string | null;

  created_at?: Date;
}
