// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { UsersId } from './Users';
import type { UniversityCoursesId } from './UniversityCourses';

/** Identifier type for public.faculty_workload */
export type FacultyWorkloadId = string & { __brand: 'public.faculty_workload' };

/** Represents the table public.faculty_workload */
export default interface FacultyWorkload {
  id: FacultyWorkloadId;

  tenant_id: TenantsId;

  faculty_id: UsersId;

  course_id: UniversityCoursesId;

  semester: string;

  assigned_hours: number;

  created_at: Date;
}

/** Represents the initializer for the table public.faculty_workload */
export interface FacultyWorkloadInitializer {
  /** Default value: gen_random_uuid() */
  id?: FacultyWorkloadId;

  tenant_id: TenantsId;

  faculty_id: UsersId;

  course_id: UniversityCoursesId;

  semester: string;

  assigned_hours: number;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.faculty_workload */
export interface FacultyWorkloadMutator {
  id?: FacultyWorkloadId;

  tenant_id?: TenantsId;

  faculty_id?: UsersId;

  course_id?: UniversityCoursesId;

  semester?: string;

  assigned_hours?: number;

  created_at?: Date;
}
