// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { FeePlansId } from './FeePlans';
import type { default as FeeFrequency } from './FeeFrequency';

/** Identifier type for public.fee_components */
export type FeeComponentsId = string & { __brand: 'public.fee_components' };

/** Represents the table public.fee_components */
export default interface FeeComponents {
  id: FeeComponentsId;

  fee_plan_id: FeePlansId;

  name: string;

  amount: string;

  frequency: FeeFrequency;

  is_optional: boolean;

  created_at: Date;
}

/** Represents the initializer for the table public.fee_components */
export interface FeeComponentsInitializer {
  /** Default value: gen_random_uuid() */
  id?: FeeComponentsId;

  fee_plan_id: FeePlansId;

  name: string;

  amount: string;

  frequency: FeeFrequency;

  /** Default value: false */
  is_optional?: boolean;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.fee_components */
export interface FeeComponentsMutator {
  id?: FeeComponentsId;

  fee_plan_id?: FeePlansId;

  name?: string;

  amount?: string;

  frequency?: FeeFrequency;

  is_optional?: boolean;

  created_at?: Date;
}
