// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { AcademicYearsId } from './AcademicYears';

/** Identifier type for public.fee_plans */
export type FeePlansId = string & { __brand: 'public.fee_plans' };

/** Represents the table public.fee_plans */
export default interface FeePlans {
  id: FeePlansId;

  tenant_id: TenantsId;

  academic_year_id: AcademicYearsId;

  name: string;

  description: string | null;

  is_active: boolean;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.fee_plans */
export interface FeePlansInitializer {
  /** Default value: gen_random_uuid() */
  id?: FeePlansId;

  tenant_id: TenantsId;

  academic_year_id: AcademicYearsId;

  name: string;

  description?: string | null;

  /** Default value: true */
  is_active?: boolean;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.fee_plans */
export interface FeePlansMutator {
  id?: FeePlansId;

  tenant_id?: TenantsId;

  academic_year_id?: AcademicYearsId;

  name?: string;

  description?: string | null;

  is_active?: boolean;

  created_at?: Date;

  updated_at?: Date;
}
