// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.gender */
enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
};

export default Gender;
