// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';

/** Identifier type for public.grades */
export type GradesId = string & { __brand: 'public.grades' };

/** Represents the table public.grades */
export default interface Grades {
  id: GradesId;

  tenant_id: TenantsId;

  name: string;

  numeric_value: number | null;

  display_order: number;

  created_at: Date;
}

/** Represents the initializer for the table public.grades */
export interface GradesInitializer {
  /** Default value: gen_random_uuid() */
  id?: GradesId;

  tenant_id: TenantsId;

  name: string;

  numeric_value?: number | null;

  display_order: number;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.grades */
export interface GradesMutator {
  id?: GradesId;

  tenant_id?: TenantsId;

  name?: string;

  numeric_value?: number | null;

  display_order?: number;

  created_at?: Date;
}
