// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { HqGroupsId } from './HqGroups';

/** Identifier type for public.group_policies */
export type GroupPoliciesId = string & { __brand: 'public.group_policies' };

/** Represents the table public.group_policies */
export default interface GroupPolicies {
  id: GroupPoliciesId;

  group_id: HqGroupsId;

  policy_name: string;

  policy_key: string;

  policy_value: string;

  is_hard_block: boolean;

  document_url: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.group_policies */
export interface GroupPoliciesInitializer {
  /** Default value: gen_random_uuid() */
  id?: GroupPoliciesId;

  group_id: HqGroupsId;

  policy_name: string;

  /** Default value: ''::character varying */
  policy_key?: string;

  /** Default value: ''::text */
  policy_value?: string;

  /** Default value: true */
  is_hard_block?: boolean;

  document_url?: string | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.group_policies */
export interface GroupPoliciesMutator {
  id?: GroupPoliciesId;

  group_id?: HqGroupsId;

  policy_name?: string;

  policy_key?: string;

  policy_value?: string;

  is_hard_block?: boolean;

  document_url?: string | null;

  created_at?: Date;
}
