// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { UsersId } from './Users';
import type { StudentsId } from './Students';
import type { default as GuardianRelation } from './GuardianRelation';

/** Identifier type for public.guardians */
export type GuardiansId = string & { __brand: 'public.guardians' };

/** Represents the table public.guardians */
export default interface Guardians {
  id: GuardiansId;

  tenant_id: TenantsId;

  user_id: UsersId | null;

  student_id: StudentsId;

  relation: GuardianRelation;

  first_name: string;

  last_name: string;

  email: string | null;

  phone: string | null;

  alternate_phone: string | null;

  occupation: string | null;

  annual_income: string | null;

  address: string | null;

  is_emergency_contact: boolean;

  is_primary: boolean;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.guardians */
export interface GuardiansInitializer {
  /** Default value: gen_random_uuid() */
  id?: GuardiansId;

  tenant_id: TenantsId;

  user_id?: UsersId | null;

  student_id: StudentsId;

  relation: GuardianRelation;

  first_name: string;

  last_name: string;

  email?: string | null;

  phone?: string | null;

  alternate_phone?: string | null;

  occupation?: string | null;

  annual_income?: string | null;

  address?: string | null;

  /** Default value: false */
  is_emergency_contact?: boolean;

  /** Default value: false */
  is_primary?: boolean;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.guardians */
export interface GuardiansMutator {
  id?: GuardiansId;

  tenant_id?: TenantsId;

  user_id?: UsersId | null;

  student_id?: StudentsId;

  relation?: GuardianRelation;

  first_name?: string;

  last_name?: string;

  email?: string | null;

  phone?: string | null;

  alternate_phone?: string | null;

  occupation?: string | null;

  annual_income?: string | null;

  address?: string | null;

  is_emergency_contact?: boolean;

  is_primary?: boolean;

  created_at?: Date;

  updated_at?: Date;
}
