// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.health_incident_type */
enum HealthIncidentType {
  INJURY = 'INJURY',
  ILLNESS = 'ILLNESS',
  ALLERGY = 'ALLERGY',
  EMERGENCY = 'EMERGENCY',
  OTHER = 'OTHER',
};

export default HealthIncidentType;
