// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { StudentsId } from './Students';

/** Identifier type for public.health_records */
export type HealthRecordsId = string & { __brand: 'public.health_records' };

/** Represents the table public.health_records */
export default interface HealthRecords {
  id: HealthRecordsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  blood_group: string | null;

  height: string | null;

  weight: string | null;

  allergies: unknown | null;

  conditions: unknown | null;

  medications: unknown | null;

  emergency_contact: string | null;

  emergency_phone: string | null;

  doctor_name: string | null;

  doctor_phone: string | null;

  insurance_id: string | null;

  insurance_provider: string | null;

  notes: string | null;

  updated_at: Date;
}

/** Represents the initializer for the table public.health_records */
export interface HealthRecordsInitializer {
  /** Default value: gen_random_uuid() */
  id?: HealthRecordsId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  blood_group?: string | null;

  height?: string | null;

  weight?: string | null;

  /** Default value: '[]'::jsonb */
  allergies?: unknown | null;

  /** Default value: '[]'::jsonb */
  conditions?: unknown | null;

  /** Default value: '[]'::jsonb */
  medications?: unknown | null;

  emergency_contact?: string | null;

  emergency_phone?: string | null;

  doctor_name?: string | null;

  doctor_phone?: string | null;

  insurance_id?: string | null;

  insurance_provider?: string | null;

  notes?: string | null;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.health_records */
export interface HealthRecordsMutator {
  id?: HealthRecordsId;

  tenant_id?: TenantsId;

  student_id?: StudentsId;

  blood_group?: string | null;

  height?: string | null;

  weight?: string | null;

  allergies?: unknown | null;

  conditions?: unknown | null;

  medications?: unknown | null;

  emergency_contact?: string | null;

  emergency_phone?: string | null;

  doctor_name?: string | null;

  doctor_phone?: string | null;

  insurance_id?: string | null;

  insurance_provider?: string | null;

  notes?: string | null;

  updated_at?: Date;
}
