// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { HomeworkAssignmentsId } from './HomeworkAssignments';
import type { StudentsId } from './Students';
import type { UsersId } from './Users';

/** Identifier type for public.homework_submissions */
export type HomeworkSubmissionsId = string & { __brand: 'public.homework_submissions' };

/** Represents the table public.homework_submissions */
export default interface HomeworkSubmissions {
  id: HomeworkSubmissionsId;

  tenant_id: TenantsId;

  assignment_id: HomeworkAssignmentsId;

  student_id: StudentsId;

  submitted_at: Date;

  content: string | null;

  attachments: unknown | null;

  marks: number | null;

  feedback: string | null;

  graded_by: UsersId | null;

  graded_at: Date | null;
}

/** Represents the initializer for the table public.homework_submissions */
export interface HomeworkSubmissionsInitializer {
  /** Default value: gen_random_uuid() */
  id?: HomeworkSubmissionsId;

  tenant_id: TenantsId;

  assignment_id: HomeworkAssignmentsId;

  student_id: StudentsId;

  /** Default value: now() */
  submitted_at?: Date;

  content?: string | null;

  /** Default value: '[]'::jsonb */
  attachments?: unknown | null;

  marks?: number | null;

  feedback?: string | null;

  graded_by?: UsersId | null;

  graded_at?: Date | null;
}

/** Represents the mutator for the table public.homework_submissions */
export interface HomeworkSubmissionsMutator {
  id?: HomeworkSubmissionsId;

  tenant_id?: TenantsId;

  assignment_id?: HomeworkAssignmentsId;

  student_id?: StudentsId;

  submitted_at?: Date;

  content?: string | null;

  attachments?: unknown | null;

  marks?: number | null;

  feedback?: string | null;

  graded_by?: UsersId | null;

  graded_at?: Date | null;
}
