// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.hostel_type */
enum HostelType {
  BOYS = 'BOYS',
  GIRLS = 'GIRLS',
  CO_ED = 'CO_ED',
};

export default HostelType;
