// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { default as HostelType } from './HostelType';
import type { UsersId } from './Users';

/** Identifier type for public.hostels */
export type HostelsId = string & { __brand: 'public.hostels' };

/** Represents the table public.hostels */
export default interface Hostels {
  id: HostelsId;

  tenant_id: TenantsId;

  name: string;

  type: HostelType;

  warden_id: UsersId | null;

  total_rooms: number;

  total_beds: number;

  occupied_beds: number;

  address: string | null;

  phone: string | null;

  is_active: boolean;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.hostels */
export interface HostelsInitializer {
  /** Default value: gen_random_uuid() */
  id?: HostelsId;

  tenant_id: TenantsId;

  name: string;

  type: HostelType;

  warden_id?: UsersId | null;

  /** Default value: 0 */
  total_rooms?: number;

  /** Default value: 0 */
  total_beds?: number;

  /** Default value: 0 */
  occupied_beds?: number;

  address?: string | null;

  phone?: string | null;

  /** Default value: true */
  is_active?: boolean;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.hostels */
export interface HostelsMutator {
  id?: HostelsId;

  tenant_id?: TenantsId;

  name?: string;

  type?: HostelType;

  warden_id?: UsersId | null;

  total_rooms?: number;

  total_beds?: number;

  occupied_beds?: number;

  address?: string | null;

  phone?: string | null;

  is_active?: boolean;

  created_at?: Date;

  updated_at?: Date;
}
