// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.hq_groups */
export type HqGroupsId = string & { __brand: 'public.hq_groups' };

/** Represents the table public.hq_groups */
export default interface HqGroups {
  id: HqGroupsId;

  name: string;

  hq_city: string;

  is_active: boolean;

  created_at: Date;
}

/** Represents the initializer for the table public.hq_groups */
export interface HqGroupsInitializer {
  /** Default value: gen_random_uuid() */
  id?: HqGroupsId;

  name: string;

  hq_city: string;

  /** Default value: true */
  is_active?: boolean;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.hq_groups */
export interface HqGroupsMutator {
  id?: HqGroupsId;

  name?: string;

  hq_city?: string;

  is_active?: boolean;

  created_at?: Date;
}
