// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.id_card_status */
enum IdCardStatus {
  PENDING = 'PENDING',
  PRINTED = 'PRINTED',
  ISSUED = 'ISSUED',
};

export default IdCardStatus;
