// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { StudentsId } from './Students';
import type { FeePlansId } from './FeePlans';
import type { default as InvoiceStatus } from './InvoiceStatus';

/** Identifier type for public.invoices */
export type InvoicesId = string & { __brand: 'public.invoices' };

/** Represents the table public.invoices */
export default interface Invoices {
  id: InvoicesId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  fee_plan_id: FeePlansId;

  invoice_number: string;

  total_amount: string;

  paid_amount: string;

  due_date: Date;

  status: InvoiceStatus;

  description: string | null;

  line_items: string | null;

  embedding: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.invoices */
export interface InvoicesInitializer {
  /** Default value: gen_random_uuid() */
  id?: InvoicesId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  fee_plan_id: FeePlansId;

  invoice_number: string;

  total_amount: string;

  /** Default value: '0'::numeric */
  paid_amount?: string;

  due_date: Date;

  /** Default value: 'PENDING'::invoice_status */
  status?: InvoiceStatus;

  description?: string | null;

  line_items?: string | null;

  embedding?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.invoices */
export interface InvoicesMutator {
  id?: InvoicesId;

  tenant_id?: TenantsId;

  student_id?: StudentsId;

  fee_plan_id?: FeePlansId;

  invoice_number?: string;

  total_amount?: string;

  paid_amount?: string;

  due_date?: Date;

  status?: InvoiceStatus;

  description?: string | null;

  line_items?: string | null;

  embedding?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
