// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.invoice_status */
enum InvoiceStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  PARTIAL = 'PARTIAL',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
  WAIVED = 'WAIVED',
};

export default InvoiceStatus;
