// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { CertificateTemplatesId } from './CertificateTemplates';
import type { StudentsId } from './Students';
import type { UsersId } from './Users';
import type { default as CertificateStatus } from './CertificateStatus';

/** Identifier type for public.issued_certificates */
export type IssuedCertificatesId = string & { __brand: 'public.issued_certificates' };

/** Represents the table public.issued_certificates */
export default interface IssuedCertificates {
  id: IssuedCertificatesId;

  tenant_id: TenantsId;

  template_id: CertificateTemplatesId;

  student_id: StudentsId;

  certificate_number: string;

  issued_date: Date;

  issued_by: UsersId | null;

  data: unknown | null;

  status: CertificateStatus;

  revoked_at: Date | null;

  revoke_reason: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.issued_certificates */
export interface IssuedCertificatesInitializer {
  /** Default value: gen_random_uuid() */
  id?: IssuedCertificatesId;

  tenant_id: TenantsId;

  template_id: CertificateTemplatesId;

  student_id: StudentsId;

  certificate_number: string;

  issued_date: Date;

  issued_by?: UsersId | null;

  /** Default value: '{}'::jsonb */
  data?: unknown | null;

  /** Default value: 'DRAFT'::certificate_status */
  status?: CertificateStatus;

  revoked_at?: Date | null;

  revoke_reason?: string | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.issued_certificates */
export interface IssuedCertificatesMutator {
  id?: IssuedCertificatesId;

  tenant_id?: TenantsId;

  template_id?: CertificateTemplatesId;

  student_id?: StudentsId;

  certificate_number?: string;

  issued_date?: Date;

  issued_by?: UsersId | null;

  data?: unknown | null;

  status?: CertificateStatus;

  revoked_at?: Date | null;

  revoke_reason?: string | null;

  created_at?: Date;
}
