// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.issue_status */
enum IssueStatus {
  ISSUED = 'ISSUED',
  RETURNED = 'RETURNED',
  OVERDUE = 'OVERDUE',
  LOST = 'LOST',
};

export default IssueStatus;
