// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { StaffProfilesId } from './StaffProfiles';
import type { default as LeaveType } from './LeaveType';
import type { default as LeaveStatus } from './LeaveStatus';
import type { UsersId } from './Users';

/** Identifier type for public.leave_requests */
export type LeaveRequestsId = string & { __brand: 'public.leave_requests' };

/** Represents the table public.leave_requests */
export default interface LeaveRequests {
  id: LeaveRequestsId;

  tenant_id: TenantsId;

  staff_id: StaffProfilesId;

  leave_type: LeaveType;

  from_date: Date;

  to_date: Date;

  total_days: string;

  reason: string;

  status: LeaveStatus;

  approved_by: UsersId | null;

  approved_at: Date | null;

  rejection_reason: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.leave_requests */
export interface LeaveRequestsInitializer {
  /** Default value: gen_random_uuid() */
  id?: LeaveRequestsId;

  tenant_id: TenantsId;

  staff_id: StaffProfilesId;

  leave_type: LeaveType;

  from_date: Date;

  to_date: Date;

  total_days: string;

  reason: string;

  /** Default value: 'PENDING'::leave_status */
  status?: LeaveStatus;

  approved_by?: UsersId | null;

  approved_at?: Date | null;

  rejection_reason?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.leave_requests */
export interface LeaveRequestsMutator {
  id?: LeaveRequestsId;

  tenant_id?: TenantsId;

  staff_id?: StaffProfilesId;

  leave_type?: LeaveType;

  from_date?: Date;

  to_date?: Date;

  total_days?: string;

  reason?: string;

  status?: LeaveStatus;

  approved_by?: UsersId | null;

  approved_at?: Date | null;

  rejection_reason?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
