// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.leave_type */
enum LeaveType {
  CL = 'CL',
  SL = 'SL',
  EL = 'EL',
  ML = 'ML',
  PL = 'PL',
  COMP_OFF = 'COMP_OFF',
  LWP = 'LWP',
};

export default LeaveType;
