// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { SubjectsId } from './Subjects';
import type { GradesId } from './Grades';
import type { UsersId } from './Users';
import type { default as LessonPlanStatus } from './LessonPlanStatus';

/** Identifier type for public.lesson_plans */
export type LessonPlansId = string & { __brand: 'public.lesson_plans' };

/** Represents the table public.lesson_plans */
export default interface LessonPlans {
  id: LessonPlansId;

  tenant_id: TenantsId;

  subject_id: SubjectsId | null;

  grade_id: GradesId | null;

  teacher_id: UsersId | null;

  topic: string;

  objectives: string | null;

  activities: string | null;

  resources: string | null;

  assessment_plan: string | null;

  duration: number | null;

  week_number: number | null;

  status: LessonPlanStatus;

  approved_by: UsersId | null;

  approved_at: Date | null;

  completed_at: Date | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.lesson_plans */
export interface LessonPlansInitializer {
  /** Default value: gen_random_uuid() */
  id?: LessonPlansId;

  tenant_id: TenantsId;

  subject_id?: SubjectsId | null;

  grade_id?: GradesId | null;

  teacher_id?: UsersId | null;

  topic: string;

  objectives?: string | null;

  activities?: string | null;

  resources?: string | null;

  assessment_plan?: string | null;

  duration?: number | null;

  week_number?: number | null;

  /** Default value: 'DRAFT'::lesson_plan_status */
  status?: LessonPlanStatus;

  approved_by?: UsersId | null;

  approved_at?: Date | null;

  completed_at?: Date | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.lesson_plans */
export interface LessonPlansMutator {
  id?: LessonPlansId;

  tenant_id?: TenantsId;

  subject_id?: SubjectsId | null;

  grade_id?: GradesId | null;

  teacher_id?: UsersId | null;

  topic?: string;

  objectives?: string | null;

  activities?: string | null;

  resources?: string | null;

  assessment_plan?: string | null;

  duration?: number | null;

  week_number?: number | null;

  status?: LessonPlanStatus;

  approved_by?: UsersId | null;

  approved_at?: Date | null;

  completed_at?: Date | null;

  created_at?: Date;

  updated_at?: Date;
}
