// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { VehiclesId } from './Vehicles';

/** Identifier type for public.live_gps_pings */
export type LiveGpsPingsId = string & { __brand: 'public.live_gps_pings' };

/** Represents the table public.live_gps_pings */
export default interface LiveGpsPings {
  id: LiveGpsPingsId;

  tenant_id: TenantsId;

  vehicle_id: VehiclesId;

  latitude: string;

  longitude: string;

  speed_kmh: string | null;

  ping_time: Date;
}

/** Represents the initializer for the table public.live_gps_pings */
export interface LiveGpsPingsInitializer {
  /** Default value: gen_random_uuid() */
  id?: LiveGpsPingsId;

  tenant_id: TenantsId;

  vehicle_id: VehiclesId;

  latitude: string;

  longitude: string;

  speed_kmh?: string | null;

  /** Default value: now() */
  ping_time?: Date;
}

/** Represents the mutator for the table public.live_gps_pings */
export interface LiveGpsPingsMutator {
  id?: LiveGpsPingsId;

  tenant_id?: TenantsId;

  vehicle_id?: VehiclesId;

  latitude?: string;

  longitude?: string;

  speed_kmh?: string | null;

  ping_time?: Date;
}
