// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.marketing_leads */
export type MarketingLeadsId = string & { __brand: 'public.marketing_leads' };

/** Represents the table public.marketing_leads */
export default interface MarketingLeads {
  id: MarketingLeadsId;

  contact_name: string;

  contact_email: string;

  school_name: string;

  student_capacity: number;

  pain_points: string | null;

  status: string;

  created_at: Date;
}

/** Represents the initializer for the table public.marketing_leads */
export interface MarketingLeadsInitializer {
  /** Default value: gen_random_uuid() */
  id?: MarketingLeadsId;

  contact_name: string;

  contact_email: string;

  school_name: string;

  student_capacity: number;

  pain_points?: string | null;

  /** Default value: 'NEW'::character varying */
  status?: string;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.marketing_leads */
export interface MarketingLeadsMutator {
  id?: MarketingLeadsId;

  contact_name?: string;

  contact_email?: string;

  school_name?: string;

  student_capacity?: number;

  pain_points?: string | null;

  status?: string;

  created_at?: Date;
}
