// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { StudentsId } from './Students';

/** Identifier type for public.medication_schedules */
export type MedicationSchedulesId = string & { __brand: 'public.medication_schedules' };

/** Represents the table public.medication_schedules */
export default interface MedicationSchedules {
  id: MedicationSchedulesId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  medication_name: string;

  dosage: string;

  times_per_day: number;

  time_slots: unknown;

  instruction_notes: string | null;

  prescribed_by: string | null;

  is_active: boolean;

  created_at: Date;
}

/** Represents the initializer for the table public.medication_schedules */
export interface MedicationSchedulesInitializer {
  /** Default value: gen_random_uuid() */
  id?: MedicationSchedulesId;

  tenant_id: TenantsId;

  student_id: StudentsId;

  medication_name: string;

  dosage: string;

  times_per_day: number;

  time_slots: unknown;

  instruction_notes?: string | null;

  prescribed_by?: string | null;

  /** Default value: true */
  is_active?: boolean;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.medication_schedules */
export interface MedicationSchedulesMutator {
  id?: MedicationSchedulesId;

  tenant_id?: TenantsId;

  student_id?: StudentsId;

  medication_name?: string;

  dosage?: string;

  times_per_day?: number;

  time_slots?: unknown;

  instruction_notes?: string | null;

  prescribed_by?: string | null;

  is_active?: boolean;

  created_at?: Date;
}
