// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { MessageTemplatesId } from './MessageTemplates';
import type { default as MsgTemplateChannel } from './MsgTemplateChannel';
import type { UsersId } from './Users';
import type { default as MsgTemplateStatus } from './MsgTemplateStatus';

/** Identifier type for public.message_logs */
export type MessageLogsId = string & { __brand: 'public.message_logs' };

/** Represents the table public.message_logs */
export default interface MessageLogs {
  id: MessageLogsId;

  tenant_id: TenantsId;

  template_id: MessageTemplatesId | null;

  channel: MsgTemplateChannel;

  recipients: unknown | null;

  message: string;

  subject: string | null;

  sent_by: UsersId | null;

  sent_at: Date;

  status: MsgTemplateStatus;

  delivery_count: number | null;

  failure_count: number | null;
}

/** Represents the initializer for the table public.message_logs */
export interface MessageLogsInitializer {
  /** Default value: gen_random_uuid() */
  id?: MessageLogsId;

  tenant_id: TenantsId;

  template_id?: MessageTemplatesId | null;

  channel: MsgTemplateChannel;

  /** Default value: '[]'::jsonb */
  recipients?: unknown | null;

  message: string;

  subject?: string | null;

  sent_by?: UsersId | null;

  /** Default value: now() */
  sent_at?: Date;

  /** Default value: 'QUEUED'::msg_template_status */
  status?: MsgTemplateStatus;

  /** Default value: 0 */
  delivery_count?: number | null;

  /** Default value: 0 */
  failure_count?: number | null;
}

/** Represents the mutator for the table public.message_logs */
export interface MessageLogsMutator {
  id?: MessageLogsId;

  tenant_id?: TenantsId;

  template_id?: MessageTemplatesId | null;

  channel?: MsgTemplateChannel;

  recipients?: unknown | null;

  message?: string;

  subject?: string | null;

  sent_by?: UsersId | null;

  sent_at?: Date;

  status?: MsgTemplateStatus;

  delivery_count?: number | null;

  failure_count?: number | null;
}
