// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { HostelsId } from './Hostels';

/** Identifier type for public.mess_menus */
export type MessMenusId = string & { __brand: 'public.mess_menus' };

/** Represents the table public.mess_menus */
export default interface MessMenus {
  id: MessMenusId;

  tenant_id: TenantsId;

  hostel_id: HostelsId;

  day: string;

  breakfast: string | null;

  lunch: string | null;

  snacks: string | null;

  dinner: string | null;

  updated_at: Date;
}

/** Represents the initializer for the table public.mess_menus */
export interface MessMenusInitializer {
  /** Default value: gen_random_uuid() */
  id?: MessMenusId;

  tenant_id: TenantsId;

  hostel_id: HostelsId;

  day: string;

  breakfast?: string | null;

  lunch?: string | null;

  snacks?: string | null;

  dinner?: string | null;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.mess_menus */
export interface MessMenusMutator {
  id?: MessMenusId;

  tenant_id?: TenantsId;

  hostel_id?: HostelsId;

  day?: string;

  breakfast?: string | null;

  lunch?: string | null;

  snacks?: string | null;

  dinner?: string | null;

  updated_at?: Date;
}
