// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { default as MsgTemplateChannel } from './MsgTemplateChannel';

/** Identifier type for public.message_templates */
export type MessageTemplatesId = string & { __brand: 'public.message_templates' };

/** Represents the table public.message_templates */
export default interface MessageTemplates {
  id: MessageTemplatesId;

  tenant_id: TenantsId;

  name: string;

  channel: MsgTemplateChannel;

  subject: string | null;

  body: string;

  variables: unknown | null;

  is_active: boolean;

  created_at: Date;
}

/** Represents the initializer for the table public.message_templates */
export interface MessageTemplatesInitializer {
  /** Default value: gen_random_uuid() */
  id?: MessageTemplatesId;

  tenant_id: TenantsId;

  name: string;

  channel: MsgTemplateChannel;

  subject?: string | null;

  body: string;

  /** Default value: '[]'::jsonb */
  variables?: unknown | null;

  /** Default value: true */
  is_active?: boolean;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.message_templates */
export interface MessageTemplatesMutator {
  id?: MessageTemplatesId;

  tenant_id?: TenantsId;

  name?: string;

  channel?: MsgTemplateChannel;

  subject?: string | null;

  body?: string;

  variables?: unknown | null;

  is_active?: boolean;

  created_at?: Date;
}
