// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.message_channel */
enum MessageChannel {
  SMS = 'SMS',
  WHATSAPP = 'WHATSAPP',
  EMAIL = 'EMAIL',
  IN_APP = 'IN_APP',
  PUSH = 'PUSH',
};

export default MessageChannel;
