// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.msg_template_channel */
enum MsgTemplateChannel {
  SMS = 'SMS',
  WHATSAPP = 'WHATSAPP',
  EMAIL = 'EMAIL',
};

export default MsgTemplateChannel;
