// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.msg_template_status */
enum MsgTemplateStatus {
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
};

export default MsgTemplateStatus;
