// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { HqGroupsId } from './HqGroups';
import type { TenantsId } from './Tenants';

/** Identifier type for public.multi_campus_hierarchy */
export type MultiCampusHierarchyId = string & { __brand: 'public.multi_campus_hierarchy' };

/** Represents the table public.multi_campus_hierarchy */
export default interface MultiCampusHierarchy {
  id: MultiCampusHierarchyId;

  group_id: HqGroupsId;

  tenant_id: TenantsId;

  region: string;

  campus_type: string;
}

/** Represents the initializer for the table public.multi_campus_hierarchy */
export interface MultiCampusHierarchyInitializer {
  /** Default value: gen_random_uuid() */
  id?: MultiCampusHierarchyId;

  group_id: HqGroupsId;

  tenant_id: TenantsId;

  region: string;

  campus_type: string;
}

/** Represents the mutator for the table public.multi_campus_hierarchy */
export interface MultiCampusHierarchyMutator {
  id?: MultiCampusHierarchyId;

  group_id?: HqGroupsId;

  tenant_id?: TenantsId;

  region?: string;

  campus_type?: string;
}
