// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { InvoicesId } from './Invoices';
import type { StudentsId } from './Students';
import type { default as PaymentMethod } from './PaymentMethod';
import type { default as PaymentStatus } from './PaymentStatus';

/** Identifier type for public.payments */
export type PaymentsId = string & { __brand: 'public.payments' };

/** Represents the table public.payments */
export default interface Payments {
  id: PaymentsId;

  tenant_id: TenantsId;

  invoice_id: InvoicesId;

  student_id: StudentsId;

  amount: string;

  method: PaymentMethod;

  status: PaymentStatus;

  transaction_id: string | null;

  razorpay_payment_id: string | null;

  cheque_number: string | null;

  bank_name: string | null;

  notes: string | null;

  paid_at: Date;

  created_at: Date;
}

/** Represents the initializer for the table public.payments */
export interface PaymentsInitializer {
  /** Default value: gen_random_uuid() */
  id?: PaymentsId;

  tenant_id: TenantsId;

  invoice_id: InvoicesId;

  student_id: StudentsId;

  amount: string;

  method: PaymentMethod;

  /** Default value: 'COMPLETED'::payment_status */
  status?: PaymentStatus;

  transaction_id?: string | null;

  razorpay_payment_id?: string | null;

  cheque_number?: string | null;

  bank_name?: string | null;

  notes?: string | null;

  /** Default value: now() */
  paid_at?: Date;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.payments */
export interface PaymentsMutator {
  id?: PaymentsId;

  tenant_id?: TenantsId;

  invoice_id?: InvoicesId;

  student_id?: StudentsId;

  amount?: string;

  method?: PaymentMethod;

  status?: PaymentStatus;

  transaction_id?: string | null;

  razorpay_payment_id?: string | null;

  cheque_number?: string | null;

  bank_name?: string | null;

  notes?: string | null;

  paid_at?: Date;

  created_at?: Date;
}
