// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.payment_status */
enum PaymentStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
};

export default PaymentStatus;
