// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';

/** Identifier type for public.periods */
export type PeriodsId = string & { __brand: 'public.periods' };

/** Represents the table public.periods */
export default interface Periods {
  id: PeriodsId;

  tenant_id: TenantsId;

  name: string;

  start_time: string;

  end_time: string;

  display_order: number;

  is_break: number;

  created_at: Date;
}

/** Represents the initializer for the table public.periods */
export interface PeriodsInitializer {
  /** Default value: gen_random_uuid() */
  id?: PeriodsId;

  tenant_id: TenantsId;

  name: string;

  start_time: string;

  end_time: string;

  display_order: number;

  /** Default value: 0 */
  is_break?: number;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.periods */
export interface PeriodsMutator {
  id?: PeriodsId;

  tenant_id?: TenantsId;

  name?: string;

  start_time?: string;

  end_time?: string;

  display_order?: number;

  is_break?: number;

  created_at?: Date;
}
