// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.pipeline_stage */
enum PipelineStage {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  FORM_SUBMITTED = 'FORM_SUBMITTED',
  DOCUMENTS_PENDING = 'DOCUMENTS_PENDING',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  INTERVIEW_DONE = 'INTERVIEW_DONE',
  OFFERED = 'OFFERED',
  ACCEPTED = 'ACCEPTED',
  ENROLLED = 'ENROLLED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
};

export default PipelineStage;
