// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';
import type { CompaniesId } from './Companies';
import type { TenantsId } from './Tenants';

/** Identifier type for public.platform_audit_logs */
export type PlatformAuditLogsId = string & { __brand: 'public.platform_audit_logs' };

/** Represents the table public.platform_audit_logs */
export default interface PlatformAuditLogs {
  id: PlatformAuditLogsId;

  actor_id: UsersId | null;

  target_company_id: CompaniesId | null;

  target_tenant_id: TenantsId | null;

  action_type: string;

  metadata: string | null;

  ip_address: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.platform_audit_logs */
export interface PlatformAuditLogsInitializer {
  /** Default value: gen_random_uuid() */
  id?: PlatformAuditLogsId;

  actor_id?: UsersId | null;

  target_company_id?: CompaniesId | null;

  target_tenant_id?: TenantsId | null;

  action_type: string;

  metadata?: string | null;

  ip_address?: string | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.platform_audit_logs */
export interface PlatformAuditLogsMutator {
  id?: PlatformAuditLogsId;

  actor_id?: UsersId | null;

  target_company_id?: CompaniesId | null;

  target_tenant_id?: TenantsId | null;

  action_type?: string;

  metadata?: string | null;

  ip_address?: string | null;

  created_at?: Date;
}
