// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.question_type */
enum QuestionType {
  MCQ = 'MCQ',
  TRUE_FALSE = 'TRUE_FALSE',
  SHORT_ANSWER = 'SHORT_ANSWER',
};

export default QuestionType;
