// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { SubjectsId } from './Subjects';
import type { GradesId } from './Grades';
import type { SectionsId } from './Sections';
import type { UsersId } from './Users';
import type { default as QuizStatus } from './QuizStatus';

/** Identifier type for public.quizzes */
export type QuizzesId = string & { __brand: 'public.quizzes' };

/** Represents the table public.quizzes */
export default interface Quizzes {
  id: QuizzesId;

  tenant_id: TenantsId;

  title: string;

  subject_id: SubjectsId | null;

  grade_id: GradesId | null;

  section_id: SectionsId | null;

  created_by: UsersId | null;

  duration: number;

  total_marks: number;

  status: QuizStatus;

  start_time: Date | null;

  end_time: Date | null;

  instructions: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.quizzes */
export interface QuizzesInitializer {
  /** Default value: gen_random_uuid() */
  id?: QuizzesId;

  tenant_id: TenantsId;

  title: string;

  subject_id?: SubjectsId | null;

  grade_id?: GradesId | null;

  section_id?: SectionsId | null;

  created_by?: UsersId | null;

  duration: number;

  total_marks: number;

  /** Default value: 'DRAFT'::quiz_status */
  status?: QuizStatus;

  start_time?: Date | null;

  end_time?: Date | null;

  instructions?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.quizzes */
export interface QuizzesMutator {
  id?: QuizzesId;

  tenant_id?: TenantsId;

  title?: string;

  subject_id?: SubjectsId | null;

  grade_id?: GradesId | null;

  section_id?: SectionsId | null;

  created_by?: UsersId | null;

  duration?: number;

  total_marks?: number;

  status?: QuizStatus;

  start_time?: Date | null;

  end_time?: Date | null;

  instructions?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
