// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { QuizzesId } from './Quizzes';
import type { default as QuestionType } from './QuestionType';

/** Identifier type for public.quiz_questions */
export type QuizQuestionsId = string & { __brand: 'public.quiz_questions' };

/** Represents the table public.quiz_questions */
export default interface QuizQuestions {
  id: QuizQuestionsId;

  tenant_id: TenantsId;

  quiz_id: QuizzesId;

  text: string;

  type: QuestionType;

  options: unknown | null;

  correct_answer: string;

  marks: number;

  ordering: number;
}

/** Represents the initializer for the table public.quiz_questions */
export interface QuizQuestionsInitializer {
  /** Default value: gen_random_uuid() */
  id?: QuizQuestionsId;

  tenant_id: TenantsId;

  quiz_id: QuizzesId;

  text: string;

  type: QuestionType;

  /** Default value: '[]'::jsonb */
  options?: unknown | null;

  correct_answer: string;

  marks: number;

  /** Default value: 0 */
  ordering?: number;
}

/** Represents the mutator for the table public.quiz_questions */
export interface QuizQuestionsMutator {
  id?: QuizQuestionsId;

  tenant_id?: TenantsId;

  quiz_id?: QuizzesId;

  text?: string;

  type?: QuestionType;

  options?: unknown | null;

  correct_answer?: string;

  marks?: number;

  ordering?: number;
}
