// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { QuizzesId } from './Quizzes';
import type { StudentsId } from './Students';
import type { default as AttemptStatus } from './AttemptStatus';

/** Identifier type for public.quiz_attempts */
export type QuizAttemptsId = string & { __brand: 'public.quiz_attempts' };

/** Represents the table public.quiz_attempts */
export default interface QuizAttempts {
  id: QuizAttemptsId;

  tenant_id: TenantsId;

  quiz_id: QuizzesId;

  student_id: StudentsId;

  answers: unknown | null;

  score: number | null;

  total_marks: number | null;

  percentage: number | null;

  started_at: Date;

  submitted_at: Date | null;

  status: AttemptStatus;
}

/** Represents the initializer for the table public.quiz_attempts */
export interface QuizAttemptsInitializer {
  /** Default value: gen_random_uuid() */
  id?: QuizAttemptsId;

  tenant_id: TenantsId;

  quiz_id: QuizzesId;

  student_id: StudentsId;

  /** Default value: '{}'::jsonb */
  answers?: unknown | null;

  score?: number | null;

  total_marks?: number | null;

  percentage?: number | null;

  /** Default value: now() */
  started_at?: Date;

  submitted_at?: Date | null;

  /** Default value: 'IN_PROGRESS'::attempt_status */
  status?: AttemptStatus;
}

/** Represents the mutator for the table public.quiz_attempts */
export interface QuizAttemptsMutator {
  id?: QuizAttemptsId;

  tenant_id?: TenantsId;

  quiz_id?: QuizzesId;

  student_id?: StudentsId;

  answers?: unknown | null;

  score?: number | null;

  total_marks?: number | null;

  percentage?: number | null;

  started_at?: Date;

  submitted_at?: Date | null;

  status?: AttemptStatus;
}
