// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.room_status */
enum RoomStatus {
  AVAILABLE = 'AVAILABLE',
  FULL = 'FULL',
  MAINTENANCE = 'MAINTENANCE',
};

export default RoomStatus;
