// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { VehiclesId } from './Vehicles';

/** Identifier type for public.routes */
export type RoutesId = string & { __brand: 'public.routes' };

/** Represents the table public.routes */
export default interface Routes {
  id: RoutesId;

  tenant_id: TenantsId;

  vehicle_id: VehiclesId;

  name: string;

  description: string | null;

  morning_departure_time: string | null;

  afternoon_departure_time: string | null;

  monthly_fee: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.routes */
export interface RoutesInitializer {
  /** Default value: gen_random_uuid() */
  id?: RoutesId;

  tenant_id: TenantsId;

  vehicle_id: VehiclesId;

  name: string;

  description?: string | null;

  morning_departure_time?: string | null;

  afternoon_departure_time?: string | null;

  monthly_fee?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.routes */
export interface RoutesMutator {
  id?: RoutesId;

  tenant_id?: TenantsId;

  vehicle_id?: VehiclesId;

  name?: string;

  description?: string | null;

  morning_departure_time?: string | null;

  afternoon_departure_time?: string | null;

  monthly_fee?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
