// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { GradesId } from './Grades';
import type { AcademicYearsId } from './AcademicYears';

/** Identifier type for public.sections */
export type SectionsId = string & { __brand: 'public.sections' };

/** Represents the table public.sections */
export default interface Sections {
  id: SectionsId;

  tenant_id: TenantsId;

  grade_id: GradesId;

  academic_year_id: AcademicYearsId;

  name: string;

  capacity: number | null;

  class_teacher_id: string | null;

  room_number: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.sections */
export interface SectionsInitializer {
  /** Default value: gen_random_uuid() */
  id?: SectionsId;

  tenant_id: TenantsId;

  grade_id: GradesId;

  academic_year_id: AcademicYearsId;

  name: string;

  /** Default value: 60 */
  capacity?: number | null;

  class_teacher_id?: string | null;

  room_number?: string | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.sections */
export interface SectionsMutator {
  id?: SectionsId;

  tenant_id?: TenantsId;

  grade_id?: GradesId;

  academic_year_id?: AcademicYearsId;

  name?: string;

  capacity?: number | null;

  class_teacher_id?: string | null;

  room_number?: string | null;

  created_at?: Date;
}
