// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { default as StockAlertType } from './StockAlertType';
import type { default as AlertSeverity } from './AlertSeverity';

/** Identifier type for public.stock_alerts */
export type StockAlertsId = string & { __brand: 'public.stock_alerts' };

/** Represents the table public.stock_alerts */
export default interface StockAlerts {
  id: StockAlertsId;

  tenant_id: TenantsId;

  item_id: string;

  item_type: string;

  alert_type: StockAlertType;

  severity: AlertSeverity;

  message: string;

  is_resolved: boolean;

  resolved_at: Date | null;

  created_at: Date;
}

/** Represents the initializer for the table public.stock_alerts */
export interface StockAlertsInitializer {
  /** Default value: gen_random_uuid() */
  id?: StockAlertsId;

  tenant_id: TenantsId;

  item_id: string;

  item_type: string;

  alert_type: StockAlertType;

  severity: AlertSeverity;

  message: string;

  /** Default value: false */
  is_resolved?: boolean;

  resolved_at?: Date | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.stock_alerts */
export interface StockAlertsMutator {
  id?: StockAlertsId;

  tenant_id?: TenantsId;

  item_id?: string;

  item_type?: string;

  alert_type?: StockAlertType;

  severity?: AlertSeverity;

  message?: string;

  is_resolved?: boolean;

  resolved_at?: Date | null;

  created_at?: Date;
}
