// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.stock_alert_type */
enum StockAlertType {
  LOW_STOCK = 'LOW_STOCK',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  EXPIRING_SOON = 'EXPIRING_SOON',
  MAINTENANCE_DUE = 'MAINTENANCE_DUE',
};

export default StockAlertType;
