// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { RoutesId } from './Routes';

/** Identifier type for public.stops */
export type StopsId = string & { __brand: 'public.stops' };

/** Represents the table public.stops */
export default interface Stops {
  id: StopsId;

  route_id: RoutesId;

  name: string;

  address: string | null;

  latitude: string | null;

  longitude: string | null;

  pickup_time: string | null;

  drop_time: string | null;

  display_order: number;

  created_at: Date;
}

/** Represents the initializer for the table public.stops */
export interface StopsInitializer {
  /** Default value: gen_random_uuid() */
  id?: StopsId;

  route_id: RoutesId;

  name: string;

  address?: string | null;

  latitude?: string | null;

  longitude?: string | null;

  pickup_time?: string | null;

  drop_time?: string | null;

  display_order: number;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.stops */
export interface StopsMutator {
  id?: StopsId;

  route_id?: RoutesId;

  name?: string;

  address?: string | null;

  latitude?: string | null;

  longitude?: string | null;

  pickup_time?: string | null;

  drop_time?: string | null;

  display_order?: number;

  created_at?: Date;
}
