// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { UsersId } from './Users';
import type { default as Gender } from './Gender';
import type { default as BloodGroup } from './BloodGroup';
import type { GradesId } from './Grades';
import type { SectionsId } from './Sections';
import type { default as StudentStatus } from './StudentStatus';

/** Identifier type for public.students */
export type StudentsId = string & { __brand: 'public.students' };

/** Represents the table public.students */
export default interface Students {
  id: StudentsId;

  tenant_id: TenantsId;

  user_id: UsersId | null;

  admission_number: string;

  first_name: string;

  last_name: string;

  date_of_birth: Date;

  gender: Gender;

  blood_group: BloodGroup | null;

  nationality: string | null;

  religion: string | null;

  category: string | null;

  aadhaar_number: string | null;

  apaar_id: string | null;

  address: string | null;

  city: string | null;

  state: string | null;

  pincode: string | null;

  photo_url: string | null;

  grade_id: GradesId;

  section_id: SectionsId;

  roll_number: number | null;

  admission_date: Date;

  status: StudentStatus;

  previous_school: string | null;

  medical_notes: string | null;

  embedding: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.students */
export interface StudentsInitializer {
  /** Default value: gen_random_uuid() */
  id?: StudentsId;

  tenant_id: TenantsId;

  user_id?: UsersId | null;

  admission_number: string;

  first_name: string;

  last_name: string;

  date_of_birth: Date;

  gender: Gender;

  blood_group?: BloodGroup | null;

  /** Default value: 'Indian'::character varying */
  nationality?: string | null;

  religion?: string | null;

  category?: string | null;

  aadhaar_number?: string | null;

  apaar_id?: string | null;

  address?: string | null;

  city?: string | null;

  state?: string | null;

  pincode?: string | null;

  photo_url?: string | null;

  grade_id: GradesId;

  section_id: SectionsId;

  roll_number?: number | null;

  admission_date: Date;

  /** Default value: 'ACTIVE'::student_status */
  status?: StudentStatus;

  previous_school?: string | null;

  medical_notes?: string | null;

  embedding?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.students */
export interface StudentsMutator {
  id?: StudentsId;

  tenant_id?: TenantsId;

  user_id?: UsersId | null;

  admission_number?: string;

  first_name?: string;

  last_name?: string;

  date_of_birth?: Date;

  gender?: Gender;

  blood_group?: BloodGroup | null;

  nationality?: string | null;

  religion?: string | null;

  category?: string | null;

  aadhaar_number?: string | null;

  apaar_id?: string | null;

  address?: string | null;

  city?: string | null;

  state?: string | null;

  pincode?: string | null;

  photo_url?: string | null;

  grade_id?: GradesId;

  section_id?: SectionsId;

  roll_number?: number | null;

  admission_date?: Date;

  status?: StudentStatus;

  previous_school?: string | null;

  medical_notes?: string | null;

  embedding?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
