// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.subscription_tier */
enum SubscriptionTier {
  CORE = 'CORE',
  AI_PRO = 'AI_PRO',
  ENTERPRISE = 'ENTERPRISE',
};

export default SubscriptionTier;
