// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { TimetableEntriesId } from './TimetableEntries';
import type { UsersId } from './Users';

/** Identifier type for public.substitutions */
export type SubstitutionsId = string & { __brand: 'public.substitutions' };

/** Represents the table public.substitutions */
export default interface Substitutions {
  id: SubstitutionsId;

  tenant_id: TenantsId;

  timetable_entry_id: TimetableEntriesId;

  original_teacher_id: UsersId;

  substitute_teacher_id: UsersId;

  date: string;

  reason: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.substitutions */
export interface SubstitutionsInitializer {
  /** Default value: gen_random_uuid() */
  id?: SubstitutionsId;

  tenant_id: TenantsId;

  timetable_entry_id: TimetableEntriesId;

  original_teacher_id: UsersId;

  substitute_teacher_id: UsersId;

  date: string;

  reason?: string | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.substitutions */
export interface SubstitutionsMutator {
  id?: SubstitutionsId;

  tenant_id?: TenantsId;

  timetable_entry_id?: TimetableEntriesId;

  original_teacher_id?: UsersId;

  substitute_teacher_id?: UsersId;

  date?: string;

  reason?: string | null;

  created_at?: Date;
}
