// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CompaniesId } from './Companies';
import type { default as InstitutionType } from './InstitutionType';

/** Identifier type for public.tenants */
export type TenantsId = string & { __brand: 'public.tenants' };

/** Represents the table public.tenants */
export default interface Tenants {
  id: TenantsId;

  company_id: CompaniesId | null;

  name: string;

  code: string;

  domain: string | null;

  institution_type: InstitutionType;

  logo_url: string | null;

  address: string | null;

  city: string | null;

  state: string | null;

  pincode: string | null;

  phone: string | null;

  email: string | null;

  website: string | null;

  affiliation_board: string | null;

  affiliation_number: string | null;

  udise_code: string | null;

  is_active: boolean;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.tenants */
export interface TenantsInitializer {
  /** Default value: gen_random_uuid() */
  id?: TenantsId;

  company_id?: CompaniesId | null;

  name: string;

  code: string;

  domain?: string | null;

  /** Default value: 'K12'::institution_type */
  institution_type?: InstitutionType;

  logo_url?: string | null;

  address?: string | null;

  city?: string | null;

  state?: string | null;

  pincode?: string | null;

  phone?: string | null;

  email?: string | null;

  website?: string | null;

  affiliation_board?: string | null;

  affiliation_number?: string | null;

  udise_code?: string | null;

  /** Default value: true */
  is_active?: boolean;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.tenants */
export interface TenantsMutator {
  id?: TenantsId;

  company_id?: CompaniesId | null;

  name?: string;

  code?: string;

  domain?: string | null;

  institution_type?: InstitutionType;

  logo_url?: string | null;

  address?: string | null;

  city?: string | null;

  state?: string | null;

  pincode?: string | null;

  phone?: string | null;

  email?: string | null;

  website?: string | null;

  affiliation_board?: string | null;

  affiliation_number?: string | null;

  udise_code?: string | null;

  is_active?: boolean;

  created_at?: Date;

  updated_at?: Date;
}
