// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.user_role */
enum UserRole {
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  SCHOOL_ADMIN = 'SCHOOL_ADMIN',
  PRINCIPAL = 'PRINCIPAL',
  ACCOUNTANT = 'ACCOUNTANT',
  ADMISSION_COUNSELOR = 'ADMISSION_COUNSELOR',
  TEACHER = 'TEACHER',
  TRANSPORT_MANAGER = 'TRANSPORT_MANAGER',
  PARENT = 'PARENT',
  STUDENT = 'STUDENT',
};

export default UserRole;
