// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { default as UserRole } from './UserRole';

/** Identifier type for public.users */
export type UsersId = string & { __brand: 'public.users' };

/** Represents the table public.users */
export default interface Users {
  id: UsersId;

  tenant_id: TenantsId;

  email: string;

  password_hash: string;

  first_name: string;

  last_name: string;

  role: UserRole;

  phone: string | null;

  avatar_url: string | null;

  is_active: boolean;

  last_login_at: Date | null;

  mfa_secret: string | null;

  mfa_enabled: boolean;

  mfa_backup_codes: string[] | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.users */
export interface UsersInitializer {
  /** Default value: gen_random_uuid() */
  id?: UsersId;

  tenant_id: TenantsId;

  email: string;

  password_hash: string;

  first_name: string;

  last_name: string;

  role: UserRole;

  phone?: string | null;

  avatar_url?: string | null;

  /** Default value: true */
  is_active?: boolean;

  last_login_at?: Date | null;

  mfa_secret?: string | null;

  /** Default value: false */
  mfa_enabled?: boolean;

  mfa_backup_codes?: string[] | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.users */
export interface UsersMutator {
  id?: UsersId;

  tenant_id?: TenantsId;

  email?: string;

  password_hash?: string;

  first_name?: string;

  last_name?: string;

  role?: UserRole;

  phone?: string | null;

  avatar_url?: string | null;

  is_active?: boolean;

  last_login_at?: Date | null;

  mfa_secret?: string | null;

  mfa_enabled?: boolean;

  mfa_backup_codes?: string[] | null;

  created_at?: Date;

  updated_at?: Date;
}
