// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';

/** Identifier type for public.vehicles */
export type VehiclesId = string & { __brand: 'public.vehicles' };

/** Represents the table public.vehicles */
export default interface Vehicles {
  id: VehiclesId;

  tenant_id: TenantsId;

  vehicle_number: string;

  type: string;

  capacity: number;

  driver_name: string;

  driver_phone: string;

  driver_license: string | null;

  conductor_name: string | null;

  conductor_phone: string | null;

  insurance_expiry: string | null;

  fitness_expiry: string | null;

  gps_device_id: string | null;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.vehicles */
export interface VehiclesInitializer {
  /** Default value: gen_random_uuid() */
  id?: VehiclesId;

  tenant_id: TenantsId;

  vehicle_number: string;

  type: string;

  capacity: number;

  driver_name: string;

  driver_phone: string;

  driver_license?: string | null;

  conductor_name?: string | null;

  conductor_phone?: string | null;

  insurance_expiry?: string | null;

  fitness_expiry?: string | null;

  gps_device_id?: string | null;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.vehicles */
export interface VehiclesMutator {
  id?: VehiclesId;

  tenant_id?: TenantsId;

  vehicle_number?: string;

  type?: string;

  capacity?: number;

  driver_name?: string;

  driver_phone?: string;

  driver_license?: string | null;

  conductor_name?: string | null;

  conductor_phone?: string | null;

  insurance_expiry?: string | null;

  fitness_expiry?: string | null;

  gps_device_id?: string | null;

  created_at?: Date;

  updated_at?: Date;
}
