// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { default as VisitPurpose } from './VisitPurpose';
import type { default as VisitorStatus } from './VisitorStatus';
import type { UsersId } from './Users';

/** Identifier type for public.visitors */
export type VisitorsId = string & { __brand: 'public.visitors' };

/** Represents the table public.visitors */
export default interface Visitors {
  id: VisitorsId;

  tenant_id: TenantsId;

  name: string;

  phone: string;

  email: string | null;

  company: string | null;

  purpose: VisitPurpose;

  purpose_details: string | null;

  host_name: string;

  host_department: string;

  photo: string | null;

  id_proof: string;

  id_number: string;

  vehicle_number: string | null;

  check_in_time: Date;

  check_out_time: Date | null;

  status: VisitorStatus;

  visitor_pass: string | null;

  pre_approved_by: UsersId | null;

  pre_approved_date: Date | null;

  created_at: Date;
}

/** Represents the initializer for the table public.visitors */
export interface VisitorsInitializer {
  /** Default value: gen_random_uuid() */
  id?: VisitorsId;

  tenant_id: TenantsId;

  name: string;

  phone: string;

  email?: string | null;

  company?: string | null;

  purpose: VisitPurpose;

  purpose_details?: string | null;

  host_name: string;

  host_department: string;

  photo?: string | null;

  id_proof: string;

  id_number: string;

  vehicle_number?: string | null;

  /** Default value: now() */
  check_in_time?: Date;

  check_out_time?: Date | null;

  /** Default value: 'CHECKED_IN'::visitor_status */
  status?: VisitorStatus;

  visitor_pass?: string | null;

  pre_approved_by?: UsersId | null;

  pre_approved_date?: Date | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.visitors */
export interface VisitorsMutator {
  id?: VisitorsId;

  tenant_id?: TenantsId;

  name?: string;

  phone?: string;

  email?: string | null;

  company?: string | null;

  purpose?: VisitPurpose;

  purpose_details?: string | null;

  host_name?: string;

  host_department?: string;

  photo?: string | null;

  id_proof?: string;

  id_number?: string;

  vehicle_number?: string | null;

  check_in_time?: Date;

  check_out_time?: Date | null;

  status?: VisitorStatus;

  visitor_pass?: string | null;

  pre_approved_by?: UsersId | null;

  pre_approved_date?: Date | null;

  created_at?: Date;
}
