// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.visitor_status */
enum VisitorStatus {
  CHECKED_IN = 'CHECKED_IN',
  CHECKED_OUT = 'CHECKED_OUT',
  PRE_APPROVED = 'PRE_APPROVED',
};

export default VisitorStatus;
