// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { TenantsId } from './Tenants';
import type { default as WebhookStatus } from './WebhookStatus';

/** Identifier type for public.webhook_subscriptions */
export type WebhookSubscriptionsId = string & { __brand: 'public.webhook_subscriptions' };

/** Represents the table public.webhook_subscriptions */
export default interface WebhookSubscriptions {
  id: WebhookSubscriptionsId;

  tenant_id: TenantsId;

  name: string;

  url: string;

  secret: string;

  events: unknown;

  status: WebhookStatus;

  headers: unknown | null;

  retry_count: number;

  timeout_ms: number;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.webhook_subscriptions */
export interface WebhookSubscriptionsInitializer {
  /** Default value: gen_random_uuid() */
  id?: WebhookSubscriptionsId;

  tenant_id: TenantsId;

  name: string;

  url: string;

  secret: string;

  events: unknown;

  /** Default value: 'ACTIVE'::webhook_status */
  status?: WebhookStatus;

  headers?: unknown | null;

  /** Default value: 3 */
  retry_count?: number;

  /** Default value: 5000 */
  timeout_ms?: number;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table public.webhook_subscriptions */
export interface WebhookSubscriptionsMutator {
  id?: WebhookSubscriptionsId;

  tenant_id?: TenantsId;

  name?: string;

  url?: string;

  secret?: string;

  events?: unknown;

  status?: WebhookStatus;

  headers?: unknown | null;

  retry_count?: number;

  timeout_ms?: number;

  created_at?: Date;

  updated_at?: Date;
}
