// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { WebhookSubscriptionsId } from './WebhookSubscriptions';
import type { default as DeliveryStatus } from './DeliveryStatus';

/** Identifier type for public.webhook_deliveries */
export type WebhookDeliveriesId = string & { __brand: 'public.webhook_deliveries' };

/** Represents the table public.webhook_deliveries */
export default interface WebhookDeliveries {
  id: WebhookDeliveriesId;

  subscription_id: WebhookSubscriptionsId;

  event: string;

  payload: unknown;

  status: DeliveryStatus;

  response_code: number | null;

  response_body: string | null;

  attempts: number;

  last_attempt_at: Date | null;

  next_retry_at: Date | null;

  error: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.webhook_deliveries */
export interface WebhookDeliveriesInitializer {
  /** Default value: gen_random_uuid() */
  id?: WebhookDeliveriesId;

  subscription_id: WebhookSubscriptionsId;

  event: string;

  payload: unknown;

  /** Default value: 'PENDING'::delivery_status */
  status?: DeliveryStatus;

  response_code?: number | null;

  response_body?: string | null;

  /** Default value: 0 */
  attempts?: number;

  last_attempt_at?: Date | null;

  next_retry_at?: Date | null;

  error?: string | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.webhook_deliveries */
export interface WebhookDeliveriesMutator {
  id?: WebhookDeliveriesId;

  subscription_id?: WebhookSubscriptionsId;

  event?: string;

  payload?: unknown;

  status?: DeliveryStatus;

  response_code?: number | null;

  response_body?: string | null;

  attempts?: number;

  last_attempt_at?: Date | null;

  next_retry_at?: Date | null;

  error?: string | null;

  created_at?: Date;
}
