// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.webhook_status */
enum WebhookStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PAUSED = 'PAUSED',
};

export default WebhookStatus;
